#!/usr/bin/env python3
###############################################################################
# Copyright (C) 2026 Advanced Micro Devices, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
###############################################################################
"""Turn one AIE layer's pipeline output into a linkable ``lib<layer>.a``.

``run_aie_pipeline`` writes ``host.cc`` / ``kernel.cc`` / ``routing.cc`` into
``layers/NN_op/aie/`` and stops. What it emits is only::

    void host_canonicalized(XAie_DevInst* dev, void* t0, void* t1, void* t2);

-- the DMA/lock/launch body. There is no device init, no buffer allocation, no
caller, and no compiled kernel ELF, so there is nothing to archive and nothing
a host program could call. That is why those folders have artifacts but no
``.a``.

This module supplies the two missing pieces, per layer:

1. **An op entry** -- the generated analogue of ``conv2dstem.cc``'s
   ``stem_run()``. ``stem_run`` is hand-written for one op; the pipeline never
   sees it, because ``run_aie_pipeline`` is driven by tensor shapes and a
   kernel-body string rather than by a C++ source file. So the same wrapping is
   generated here, from the same template the aiehlc frontend emits for
   ``__aie_launch`` (``aout/worklocal/host.cc``)::

       dev = __Runtime_explicit_init_partition(startCol, nCols);
       __Runtime_set_kernel_elf(_binary_kernel_<func>_start);
       __Runtime_sync_for_dev(dev, t, size);     // per buffer
       host_canonicalized(dev, t0, t1, ...);
       __Runtime_explicit_teardown(dev);

2. **The archive.** ``hostcompile.sh`` run with the layer's ``aie/`` as its
   working directory builds ``kernel.cc`` into the core ELF, embeds it
   (``ld -r -b binary`` -> ``_binary_kernel_<func>_*``), compiles every ``.cc``
   in the directory, sees that ``host.cc`` has no ``main()``, and therefore
   archives rather than links (``HOST_ENTRY_KIND=library``, skill
   **hostlibrarymode**). ``app_source.txt`` names the result, so a layer called
   ``09_conv2d`` yields ``lib09_conv2d.a``.

Best-effort by design: a box without the Vitis cross toolchain is a normal
place to run the earlier stages, so a missing toolchain returns
``{"ok": False, "reason": ...}`` rather than raising.
"""
from __future__ import annotations

import os
import re
import subprocess
from pathlib import Path

__all__ = ["emit_op_entry", "build_archive", "archive_for", "LAYER_ENTRY_SUFFIX"]

#: Appended to the layer stem to form the generated entry's symbol:
#: ``09_conv2d`` -> ``aie_09_conv2d_run``. C identifiers cannot start with a
#: digit, hence the ``aie_`` prefix.
LAYER_ENTRY_SUFFIX = "_run"

#: Marks the appended block so a re-run replaces it instead of stacking copies.
_ENTRY_MARK = "/* ---- aie_layer_lib op entry ---- */"

_ENTRY_TMPL = _ENTRY_MARK + """
/* Generated by src/frontend/tvmrelay/aie_layer_lib.py -- do not edit.
 *
 * Op entry for AIE layer {stem}.
 *
 * run_aie_pipeline emits only host_canonicalized(), the DMA/lock/launch body.
 * This is the surrounding call sequence that makes it usable from a host
 * program -- device partition, kernel ELF selection, cache sync per buffer,
 * teardown -- generated from the same shape the aiehlc frontend emits for
 * __aie_launch. It is the generated counterpart of conv2dstem.cc's stem_run().
 *
 * Buffers must come from __Runtime_alloc_buffer (64-byte aligned, DMA-capable);
 * a plain malloc'd pointer has no alignment guarantee and the shim DMA gather
 * will not accept it.
 *
 *   kernel  : {func}
 *   mesh    : {rows} x {cols}, columns [{start_col}, {end_col}]
 *   tensors : {tensor_note}
 *
 * Appended to host.cc rather than written as its own file: hostcompile.sh
 * compiles a FIXED set (host.cc, routing.cc, kernel_*.cc, the runtime), not
 * every .cc in the directory, so a standalone file would be silently left out
 * of the archive. host.cc already includes aie_runtime.h and defines
 * host_canonicalized above, so no declaration is needed here.
 */

/* Embedded by `ld -r -b binary` when hostcompile.sh builds kernel.cc
 * (script/kc.sh: _binary_kernel_<func_name>_{{start,end,size}}). */
extern "C" unsigned char _binary_kernel_{func}_start[];

/*
 * Run this layer on the mesh. Returns 0 on success.
 *
 * Sizes are passed alongside the pointers because the cache maintenance is
 * per-buffer: __Runtime_sync_for_dev has to know how much to flush, and the
 * shapes are baked into host_canonicalized rather than being readable from it.
 */
extern "C" int {entry}({entry_params}) {{
    XAie_DevInst* dev = __Runtime_explicit_init_partition({start_col}, {cols});
    if (!dev)
        return -1;
    __Runtime_set_kernel_elf(_binary_kernel_{func}_start);
{syncs}
    host_canonicalized(dev{canon_args});
{post_syncs}
    __Runtime_explicit_teardown(dev);
    return 0;
}}
"""


def _c_ident(stem: str) -> str:
    """``09_conv2d`` -> ``aie_09_conv2d``. C identifiers cannot lead with a digit."""
    return "aie_" + re.sub(r"[^0-9a-zA-Z_]", "_", stem)


def archive_for(aie_dir, stem: str) -> Path:
    """Where :func:`build_archive` puts the library for *stem*."""
    return Path(aie_dir) / "build" / f"lib{stem}.a"


def emit_op_entry(aie_dir, stem: str, func_name: str, specs, mesh,
                  start_col: int = 0) -> Path:
    """Append the op entry to ``host.cc``. Returns the path written.

    *specs* is ``run_aie_pipeline``'s tensor list -- ``(shape, bits, is_input)``
    per buffer, in the order ``host_canonicalized`` takes them.

    Appends rather than writing a sibling file because ``hostcompile.sh``
    compiles a fixed set of sources; a separate ``.cc`` would never reach the
    archive. Re-running is safe: an existing block is replaced, not stacked.
    """
    aie_dir = Path(aie_dir)
    host = aie_dir / "host.cc"
    if not host.is_file():
        raise FileNotFoundError(f"{host} not found; run_aie_pipeline emits it")
    n = len(specs)
    if n == 0:
        raise ValueError(f"{stem}: no tensor specs; nothing to pass to the kernel")

    rows, cols = int(mesh[0]), int(mesh[1])
    entry = _c_ident(stem) + LAYER_ENTRY_SUFFIX

    params = ", ".join(f"void* t{i}, size_t s{i}" for i in range(n))
    canon_params = "".join(f", void* t{i}" for i in range(n))
    canon_args = "".join(f", t{i}" for i in range(n))

    # Inputs are flushed before the launch; outputs invalidated after it. An
    # output flushed up front would be a no-op, and an input invalidated
    # afterwards would discard nothing -- but getting the direction wrong on an
    # OUTPUT means the host reads stale cache lines instead of what the AIE
    # wrote, which looks exactly like a compute bug.
    syncs, post = [], []
    note = []
    for i, (shape, bits, is_in) in enumerate(specs):
        dims = "x".join(str(int(d)) for d in shape)
        note.append(f"t{i} {dims} {'in' if is_in else 'out'} ({int(bits)}-bit)")
        (syncs if is_in else post).append(
            f"    __Runtime_sync_for_dev(dev, t{i}, s{i});" if is_in
            else f"    __Runtime_sync_for_cpu(dev, t{i}, s{i});")

    text = _ENTRY_TMPL.format(
        stem=stem, func=func_name, entry=entry, entry_params=params,
        canon_params=canon_params, canon_args=canon_args,
        rows=rows, cols=cols, start_col=start_col, end_col=start_col + cols - 1,
        cols_=cols, tensor_note="; ".join(note),
        syncs="\n".join(syncs), post_syncs="\n".join(post))

    body = host.read_text()
    cut = body.find(_ENTRY_MARK)
    if cut != -1:                       # drop a previous block before appending
        body = body[:cut].rstrip() + "\n"
    host.write_text(body.rstrip() + "\n\n" + text)
    return host


def build_archive(aie_dir, stem: str, repo_root, *, aie_version: int = 5,
                  verbose: bool = True) -> dict:
    """Run ``hostcompile.sh`` in *aie_dir* to produce ``lib<stem>.a``.

    Returns ``{"ok", "archive"|"reason", "entry", "log"}``. Never raises for a
    missing toolchain -- the earlier stages are useful without it.
    """
    aie_dir, repo_root = Path(aie_dir), Path(repo_root)
    script = repo_root / "script" / "hostcompile.sh"
    if not (aie_dir / "host.cc").is_file():
        return {"ok": False, "reason": "no host.cc (run_aie_pipeline did not emit one)"}
    if not script.is_file():
        return {"ok": False, "reason": f"missing {script}"}

    # hostcompile.sh names the archive from app_source.txt's basename.
    (aie_dir / "app_source.txt").write_text(f"{stem}.cc\n")

    env = dict(os.environ)
    env.setdefault("AIE_GEN", str(aie_version))
    proc = subprocess.run(
        ["bash", str(script), "--aie-version", str(aie_version)],
        cwd=str(aie_dir), env=env, capture_output=True, text=True)

    archive = archive_for(aie_dir, stem)
    if not archive.is_file():
        # Keep the log: a toolchain failure here is otherwise invisible, and
        # the usual cause (no Vitis on PATH) reads clearly in the last lines.
        log = aie_dir / "hostcompile.log"
        log.write_text(proc.stdout + "\n" + proc.stderr)
        tail = (proc.stderr.strip().splitlines() or
                proc.stdout.strip().splitlines() or ["(no output)"])[-1]
        return {"ok": False, "reason": f"hostcompile.sh did not produce "
                                       f"{archive.name}: {tail}", "log": str(log)}

    if verbose:
        print(f"  [aiegraph]   -> {archive.name} "
              f"({archive.stat().st_size / 1024:,.0f} KB)")
    return {"ok": True, "archive": str(archive)}
