###############################################################################
# Copyright (C) 2026 Advanced Micro Devices, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
###############################################################################
"""Build a stem-conv layer's ``aie/`` from ``conv2dstem.cc`` with aiehlc.

The generic aiegraph backend (``run_aie_pipeline`` + ``kernels.conv_bn_body``)
emits a placeholder Q7 conv: int16 accumulator, dummy quant params, NCHW
indexing. For ResNet-18's stem -- layer 01,
``contrib_conv2d_NCHWc_subtract_add_subtract_fixed_point_multiply_per_axi`` --
the repo already has the real thing: ``src/aietensorop/conv2dstem/conv2dstem.cc``
(int32 accumulator, TVM's per-channel ``fixed_point_multiply`` requant, the
OIHW3i4o / NCHW4c bridges in ``conv2d_stem_nchwc``), verified bit-exact against
this very layer by ``test_conv2d.cc``.

So a layer whose geometry is exactly that one is built the way
``test_conv2d.cc`` is: ``source script/aiehlc.sh --runtime-source-file
conv2dstem.cc``. ``test_conv2d.cc`` only adds a ``main()`` around
``#include "conv2dstem.cc"``, and the two builds' ``kernel.cc`` /
``routing.cc`` are byte-identical (``host.cc`` differs by exactly that
``main()``). Without ``main()`` aiehlc archives ``libconv2dstem.a`` (skill:
hostlibrarymode), which lands in ``aie/build/`` where ``arm_build``'s
``AIE_LAYER_LIBS`` wildcard picks it up.

``aiehlc.sh`` writes ``aout/`` relative to the **cwd** and ``rm -rf``s it first,
so it runs in a scratch directory and ``aout/worklocal/`` is copied into the
layer's ``aie/`` afterwards. The layer's data headers that aiehlc copies along
(``conv2d_stem_in_weight.h`` / ``_out_golden.h``, ~6 MB of ``layeriohex`` dump)
are left out: the library never includes them.
"""

from __future__ import annotations

import shutil
import subprocess
import tempfile
import time
from pathlib import Path

__all__ = ["STEM_SOURCE", "matches_stem", "build_stem_layer", "entry_symbol"]

#: Repo root: .../src/frontend/tvmrelay/aie_stem_lib.py -> up three.
_REPO = Path(__file__).resolve().parents[3]

#: The source aiehlc compiles for a stem layer -- the same file
#: ``test_conv2d.cc`` ``#include``s.
STEM_SOURCE = _REPO / "src" / "aietensorop" / "conv2dstem" / "conv2dstem.cc"

#: Not artifacts of the build: data headers aiehlc's ``*.h`` glob copies from
#: the source directory. Nothing in the library includes them.
_SKIP = ("conv2d_stem_in_weight.h", "conv2d_stem_out_golden.h")


def matches_stem(rec: dict) -> bool:
    """True when an aiegraph conv record is exactly the conv2dstem geometry.

    Exact match on every field, against ``byoc.aie_patterns.STEM_GEOMETRY``
    (the one definition the BYOC gate also uses): ``conv2dstem.cc`` bakes the
    geometry into its ``#define``s, its GemmSpace descriptors and its
    ``static_assert``s, so "close" is not runnable.
    """
    from frontend.tvmrelay.byoc.aie_patterns import STEM_GEOMETRY as g

    return ((rec.get("H"), rec.get("W")) == tuple(g["in_hw"])
            and rec.get("Cin") == g["in_c"] and rec.get("Cout") == g["out_c"]
            and rec.get("K") == g["kernel"][0]
            and rec.get("stride") == g["strides"][0])


def entry_symbol(func_name: str) -> str:
    """The AIE entry that replaces TVM kernel *func_name* in ``graph_driver.c``."""
    return f"aie_{func_name}"


#: Appended to the layer's ``aie/host.cc`` (``hostcompile.sh`` compiles a fixed
#: source set, so a sibling .cc would be dropped -- same rule as
#: ``aie_layer_lib.emit_op_entry``). It has TVM's packed-call signature, so
#: ``graph_driver.c`` swaps the kernel's NAME and nothing else, and it does
#: exactly what ``test_conv2d.cc``'s ``main()`` does with the layeriohex dump:
#: fold the six int32 param arrays into ``conv2dstem_qparam[64]`` (refusing a
#: live second zero-point), then ``conv2d_stem_nchwc()``. The ``[aie-offload]``
#: lines are how a console log proves layer 01 really ran on the array.
_ENTRY_TMPL = r"""
/* ═══════════════════════════════════════════════════════════════════════════
 * TVM packed-call entry for layer {index:02d} -- generated by
 * frontend/tvmrelay/aie_stem_lib.py, appended to aiehlc's host.cc.
 *
 * Replaces {func_name}
 * in graph_driver.c (under -DGRAPH_AIE_OFFLOAD). Args, in TVM's order:
 *   0 int8  [1,1,230,230,3]  activation, zero-point padded
 *   1 int8  [16,1,7,7,3,4]   weights, OIHW3i4o
 *   2 int32 [64] zero-point   3 int32 [64] bias      4 int32 [64] zero-point
 *   5 int32 [64] multiplier   6 int32 [64] unused     7 int32 [64] shift
 *   8 uint8 [1,16,112,112,4] output, NCHW4c
 * Same fold as test_conv2d.cc:fold_qparams(), same call: conv2d_stem_nchwc().
 * ═══════════════════════════════════════════════════════════════════════════ */
#include <stdio.h>

/* TVMValue is an 8-byte union whose v_handle is a DLTensor*, and DLTensor's
 * first field is `void *data` (graph_driver.c sets byte_offset = 0). */
static inline void *aie_l{index:02d}_data(void *args, int i) {{
    return *(void **)(((void **)args)[i]);
}}

extern "C" int32_t {entry}(void *args, int32_t *type_codes, int32_t num_args,
                            void *out_ret_value, int32_t *out_ret_tcode,
                            void *resource_handle) {{
    (void)type_codes; (void)out_ret_value; (void)out_ret_tcode; (void)resource_handle;
    printf("[aie-offload] layer {index:02d} {short}: ENTER aiehlc conv2dstem "
           "(conv2d_stem_nchwc on the AIE mesh), %d args\n", (int)num_args);
    if (num_args != 9) {{
        printf("[aie-offload] layer {index:02d}: want 9 args, got %d\n", (int)num_args);
        return -1;
    }}
    const int8_t *ifm = (const int8_t *)aie_l{index:02d}_data(args, 0);
    const int8_t *wts = (const int8_t *)aie_l{index:02d}_data(args, 1);
    const int32_t *zp_a = (const int32_t *)aie_l{index:02d}_data(args, 2);
    const int32_t *bias = (const int32_t *)aie_l{index:02d}_data(args, 3);
    const int32_t *zp_b = (const int32_t *)aie_l{index:02d}_data(args, 4);
    const int32_t *mult = (const int32_t *)aie_l{index:02d}_data(args, 5);
    const int32_t *unused = (const int32_t *)aie_l{index:02d}_data(args, 6);
    const int32_t *shift = (const int32_t *)aie_l{index:02d}_data(args, 7);
    uint8_t *ofm = (uint8_t *)aie_l{index:02d}_data(args, 8);

    static conv2dstem_qparam qp[CONV2DSTEM_NUM_FILTERS];
    for (int oc = 0; oc < CONV2DSTEM_NUM_FILTERS; oc++) {{
        if (zp_b[oc] != 0 || unused[oc] != 0) {{
            printf("[aie-offload] layer {index:02d}: channel %d has a second "
                   "zero-point (%d) / live unused param (%d); refusing\n",
                   oc, (int)zp_b[oc], (int)unused[oc]);
            return CONV2DSTEM_ERR_BAD_QPARAM;
        }}
        qp[oc].bias = bias[oc];
        qp[oc].zero_point = zp_a[oc];
        qp[oc].multiplier = mult[oc];
        qp[oc].shift = shift[oc];
    }}

    const int rc = conv2d_stem_nchwc(ifm, wts, qp, ofm);
    uint32_t sum = 0;
    for (int i = 0; i < CONV2DSTEM_OFM_NCHWC_ELEMS; i++)
        sum = sum * 31u + ofm[i];
    printf("[aie-offload] layer {index:02d}: EXIT rc=%d, ofm[0..7]= "
           "%02x %02x %02x %02x %02x %02x %02x %02x, hash=%08x\n", rc,
           ofm[0], ofm[1], ofm[2], ofm[3], ofm[4], ofm[5], ofm[6], ofm[7],
           (unsigned)sum);
    return rc == CONV2DSTEM_OK ? 0 : -1;
}}
"""


def _install_entry(aie_dir: Path, index: int, func_name: str,
                   verbose: bool) -> dict:
    """Append the packed-call entry to ``host.cc`` and re-archive. Returns
    ``{"ok", "entry", "archive"|None, "reason"?}``."""
    from frontend.tvmrelay import aie_layer_lib

    entry = entry_symbol(func_name)
    short = func_name.replace("tvmgen_default_fused_", "")[:40]
    host = aie_dir / "host.cc"
    host.write_text(host.read_text() + _ENTRY_TMPL.format(
        index=index, func_name=func_name, entry=entry, short=short))
    stale = aie_dir / "build" / f"lib{STEM_SOURCE.stem}.a"
    if stale.exists():
        stale.unlink()             # so an old archive cannot pass for this one
    built = aie_layer_lib.build_archive(aie_dir, STEM_SOURCE.stem, _REPO,
                                        verbose=verbose)
    return {"ok": built.get("ok", False), "entry": entry,
            "archive": built.get("archive"), "reason": built.get("reason")}


def build_stem_layer(aie_dir: Path, *, index: int = 1, func_name: str = "",
                     aie_version: int = 5, verbose: bool = True) -> dict:
    """aiehlc-build ``conv2dstem.cc`` and install its output as *aie_dir*.

    With *func_name* (the TVM kernel symbol this layer calls), also appends
    the packed-call entry ``aie_<func_name>`` to ``host.cc`` and re-archives,
    so ``graph_driver.c`` can call the AIE in that kernel's place.

    Returns ``{"ok", "files", "archive"|None, "entry"?, "reason"?, "log"}``.
    Never raises for a build failure -- the caller records it in
    ``partition.json``. *aie_dir* is replaced wholesale, so no file from an
    earlier (generic) build survives next to the real one.
    """
    aie_dir = Path(aie_dir)
    log = aie_dir.parent / "aiehlc_stem.log"
    scratch = Path(tempfile.mkdtemp(prefix="aiehlc_stem_"))
    cmd = (f'source "{_REPO}/script/aiehlc.sh" --aie-version {aie_version} '
           f'--runtime-source-file "{STEM_SOURCE}"')
    start = time.time()
    try:
        with log.open("w") as fh:
            rc = subprocess.run(["bash", "-c", cmd], cwd=str(scratch),
                                stdout=fh, stderr=subprocess.STDOUT).returncode
        work = scratch / "aout" / "worklocal"
        if rc != 0 or not (work / "host.cc").is_file():
            return {"ok": False, "files": [], "archive": None, "log": str(log),
                    "reason": f"aiehlc.sh rc={rc}; see {log.name}"}
        if aie_dir.exists():
            shutil.rmtree(aie_dir)
        shutil.copytree(work, aie_dir, symlinks=True,
                        ignore=lambda _d, names: [n for n in names if n in _SKIP])
    finally:
        shutil.rmtree(scratch, ignore_errors=True)

    entry = None
    if func_name:
        inst = _install_entry(aie_dir, index, func_name, verbose=False)
        if not inst["ok"]:
            return {"ok": False, "files": sorted(p.name for p in aie_dir.iterdir()),
                    "archive": None, "log": str(log),
                    "reason": f"re-archive with the entry failed: {inst['reason']}"}
        entry = inst["entry"]

    archive = aie_dir / "build" / f"lib{STEM_SOURCE.stem}.a"
    files = sorted(p.name for p in aie_dir.iterdir())
    if verbose:
        size = (f"{archive.stat().st_size / 1024:,.0f} KB" if archive.is_file()
                else "no archive")
        print(f"  [aiegraph]   aiehlc {STEM_SOURCE.name} -> {archive.name} "
              f"({size}, {time.time() - start:.0f}s)")
    return {"ok": True, "files": files, "log": str(log), "entry": entry,
            "archive": str(archive) if archive.is_file() else None}
