/******************************************************************************
 * Copyright (C) 2026 Advanced Micro Devices, Inc. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Host-side numerics check for conv2dstem, with NO AIE toolchain involved.
 *
 * conv2dstem.cc cannot be compiled by a normal compiler -- it is an aiehlc
 * runtime source containing `__global__` kernels and a `<<<mesh>>>` launch. So
 * the parts that have to be numerically right (the staging/packing layout, the
 * int32 accumulator, and the fused epilogue) are reproduced here EXACTLY as
 * they appear there, and checked against the TVM-verified reference output
 * generated by stem_ref.py.
 *
 * This catches, on an x86 host in seconds:
 *   - the int16 -> int32 accumulator fix (peak |acc| measures 257,339)
 *   - the param-in-pad-channel packing round-trip
 *   - the requantize/ReLU/uint8 epilogue, term for term
 *
 * It does NOT exercise the AIE DMA, mesh tiling or routing -- only arithmetic.
 *
 * Build and run:
 *   gcc -O2 -o /tmp/verify_pack src/aietensorop/conv2dstem/ref/verify_pack.c
 *   /tmp/verify_pack worklocal/stem_fixture
 ******************************************************************************/
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ── Geometry: must mirror conv2dstem.cc ────────────────────────────────── */
#define INPUT_H 224
#define INPUT_W 224
#define INPUT_C 3
#define INPUT_C_ALIGN 4
#define KERNEL_H 7
#define KERNEL_W 7
#define NUM_FILTERS 64
#define STRIDE 2
#define PAD 3
#define OUTPUT_H 112
#define OUTPUT_W 112
#define INPUT_H_PAD (INPUT_H + 2 * PAD)
#define INPUT_W_PAD (INPUT_W + 2 * PAD)
#define K (KERNEL_H * KERNEL_W * INPUT_C_ALIGN)

#define SP_C 4
#define SP_REAL_C 3
#define SP_PARAM_TAP_OFF (SP_C - 1)

#define IFM_ELEMS (INPUT_H * INPUT_W * INPUT_C)
#define WTS_ELEMS (NUM_FILTERS * KERNEL_H * KERNEL_W * INPUT_C)
#define IFM_PAD_ELEMS (INPUT_H_PAD * INPUT_W_PAD * INPUT_C_ALIGN)
#define WTS_BT_ELEMS (NUM_FILTERS * K)
#define OFM_ELEMS (OUTPUT_H * OUTPUT_W * NUM_FILTERS)

typedef struct {
    int32_t bias, zero_point, multiplier, shift;
} qparam;

/* ── Copied verbatim from conv2dstem.cc ─────────────────────────────────── */
static inline int32_t rd_param_i32(const int8_t *brow, int idx) {
    uint32_t v = 0;
    for (int b = 0; b < 4; b++) {
        const int tap = idx * 4 + b;
        v |= (uint32_t)(uint8_t)brow[tap * SP_C + SP_PARAM_TAP_OFF] << (8 * b);
    }
    return (int32_t)v;
}

static void stage_ifm(const int8_t *ifm, int8_t *g_ifm_pad) {
    memset(g_ifm_pad, 0, IFM_PAD_ELEMS);
    for (int h = 0; h < INPUT_H; h++)
        for (int w = 0; w < INPUT_W; w++) {
            const int src = (h * INPUT_W + w) * INPUT_C;
            const int dst = ((h + PAD) * INPUT_W_PAD + (w + PAD)) * INPUT_C_ALIGN;
            for (int c = 0; c < INPUT_C; c++)
                g_ifm_pad[dst + c] = ifm[src + c];
        }
}

static void stage_weights(const int8_t *wts, const qparam *qp, int8_t *g_wts_bt) {
    memset(g_wts_bt, 0, WTS_BT_ELEMS);
    for (int f = 0; f < NUM_FILTERS; f++) {
        for (int kh = 0; kh < KERNEL_H; kh++)
            for (int kw = 0; kw < KERNEL_W; kw++) {
                const int src = ((f * KERNEL_H + kh) * KERNEL_W + kw) * INPUT_C;
                const int dst = f * K + (kh * KERNEL_W + kw) * INPUT_C_ALIGN;
                for (int c = 0; c < INPUT_C; c++)
                    g_wts_bt[dst + c] = wts[src + c];
            }
        int8_t *brow = &g_wts_bt[f * K];
        const int32_t fields[4] = {qp[f].bias, qp[f].zero_point, qp[f].multiplier, qp[f].shift};
        for (int i = 0; i < 4; i++) {
            const uint32_t u = (uint32_t)fields[i];
            for (int b = 0; b < 4; b++)
                brow[(i * 4 + b) * INPUT_C_ALIGN + SP_PARAM_TAP_OFF] = (int8_t)((u >> (8 * b)) & 0xFF);
        }
    }
}

static int64_t g_peak_acc = 0;

static void scalar_conv2d_ref(const int8_t *ifm_pad, const int8_t *wts_bt, uint8_t *ref) {
    for (int oh = 0; oh < OUTPUT_H; oh++)
        for (int ow = 0; ow < OUTPUT_W; ow++)
            for (int f = 0; f < NUM_FILTERS; f++) {
                int32_t acc = 0;
                for (int kh = 0; kh < KERNEL_H; kh++)
                    for (int kw = 0; kw < KERNEL_W; kw++)
                        for (int c = 0; c < INPUT_C; c++) {
                            const int ih = oh * STRIDE + kh;
                            const int iw = ow * STRIDE + kw;
                            const int kk = (kh * KERNEL_W + kw) * INPUT_C_ALIGN + c;
                            const int8_t iv = ifm_pad[(ih * INPUT_W_PAD + iw) * INPUT_C_ALIGN + c];
                            const int8_t fv = wts_bt[f * K + kk];
                            acc += (int32_t)iv * (int32_t)fv;
                        }
                if (acc > g_peak_acc)
                    g_peak_acc = acc;
                if (-acc > g_peak_acc)
                    g_peak_acc = -acc;
                const int8_t *brow = &wts_bt[f * K];
                acc += rd_param_i32(brow, 0);
                acc -= rd_param_i32(brow, 1);
                const int32_t mult = rd_param_i32(brow, 2);
                const int sh = (int)rd_param_i32(brow, 3);
                int64_t v = ((int64_t)acc * (int64_t)mult + ((int64_t)1 << (sh + 30))) >> (sh + 31);
                if (v > 255)
                    v = 255;
                else if (v < 0)
                    v = 0;
                ref[(oh * OUTPUT_W + ow) * NUM_FILTERS + f] = (uint8_t)v;
            }
}

/* ── Harness ────────────────────────────────────────────────────────────── */
static void *slurp(const char *dir, const char *name, size_t want) {
    char path[1024];
    snprintf(path, sizeof path, "%s/%s", dir, name);
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "cannot open %s\n", path);
        exit(2);
    }
    void *buf = malloc(want);
    const size_t got = fread(buf, 1, want, f);
    fclose(f);
    if (got != want) {
        fprintf(stderr, "%s: read %zu bytes, expected %zu\n", path, got, want);
        exit(2);
    }
    return buf;
}

int main(int argc, char **argv) {
    const char *dir = argc > 1 ? argv[1] : "worklocal/stem_fixture";

    int8_t *ifm = slurp(dir, "ifm.bin", IFM_ELEMS);
    int8_t *wts = slurp(dir, "wts.bin", WTS_ELEMS);
    qparam *qp = slurp(dir, "params.bin", NUM_FILTERS * sizeof(qparam));
    uint8_t *expect = slurp(dir, "ofm_ref.bin", OFM_ELEMS);

    int8_t *ifm_pad = malloc(IFM_PAD_ELEMS);
    int8_t *wts_bt = malloc(WTS_BT_ELEMS);
    uint8_t *got = malloc(OFM_ELEMS);

    stage_ifm(ifm, ifm_pad);
    stage_weights(wts, qp, wts_bt);

    /* Packing must round-trip, or every later number is meaningless. */
    int pack_bad = 0;
    for (int f = 0; f < NUM_FILTERS; f++) {
        const int8_t *brow = &wts_bt[f * K];
        if (rd_param_i32(brow, 0) != qp[f].bias || rd_param_i32(brow, 1) != qp[f].zero_point ||
            rd_param_i32(brow, 2) != qp[f].multiplier || rd_param_i32(brow, 3) != qp[f].shift)
            pack_bad++;
    }
    printf("param pack round-trip : %s (%d/%d channels bad)\n", pack_bad ? "FAIL" : "OK", pack_bad, NUM_FILTERS);

    scalar_conv2d_ref(ifm_pad, wts_bt, got);

    long mism = 0;
    int shown = 0;
    for (long i = 0; i < OFM_ELEMS; i++)
        if (got[i] != expect[i]) {
            if (shown < 8) {
                const long oh = i / (OUTPUT_W * NUM_FILTERS);
                const long ow = (i / NUM_FILTERS) % OUTPUT_W;
                const long f = i % NUM_FILTERS;
                printf("  MISMATCH [oh=%ld,ow=%ld,f=%ld] got=%u expected=%u\n", oh, ow, f, got[i], expect[i]);
                shown++;
            }
            mism++;
        }

    printf("peak |accumulator|    : %lld  (int16 max 32767 -> %s)\n", (long long)g_peak_acc,
           g_peak_acc > 32767 ? "int32 REQUIRED" : "would fit int16");
    printf("output vs TVM ref     : %s (%ld / %d mismatched)\n", mism ? "FAIL" : "PASS", mism, OFM_ELEMS);
    return (mism || pack_bad) ? 1 : 0;
}
