#!/bin/bash
#
# COPYRIGHT NOTICE
# Copyright 1986-1999, 2001-2011 Xilinx, Inc. All Rights Reserved.
#
# This is a modified copy of the Vitis aiesimulator # launcher script.
#
# Change 1 (near top): Replace the `. setupEnv.sh` relative-source with
#   direct RDI_* variable derivation from $XILINX_VITIS_AIETOOLS, because
#   setupEnv.sh uses `dirname "$0"` to locate itself, which breaks when the
#   script lives outside the Vitis bin directory.
#
# Change 2 (near bottom, before setsid): Inject $AIEHLC_RUNTIME_LIB_DIR at the
#   front of LD_LIBRARY_PATH right before the simulator is launched, so that
#   our libaiehlc_runtime.so is found before the Vitis-bundled version regardless of what chess_env_LNa64.sh prepended.

# AIEHLC: Change 1
if [ -z "${XILINX_VITIS_AIETOOLS:-}" ]; then
    if [ -n "${XILINX_VITIS:-}" ] && [ -d "${XILINX_VITIS}/aietools" ]; then
        export XILINX_VITIS_AIETOOLS="${XILINX_VITIS}/aietools"
    else
        echo "AEG: XILINX_VITIS_AIETOOLS is not set and XILINX_VITIS not found." >&2
        echo "     Source script/envaie2pst50.sh (or equivalent) first." >&2
        exit 1
    fi
fi
export RDI_BINROOT="${XILINX_VITIS_AIETOOLS}/bin"
export RDI_APPROOT="${XILINX_VITIS_AIETOOLS}"
export RDI_BASEROOT="$(dirname "${XILINX_VITIS_AIETOOLS}")"
export RDI_INSTALLROOT="$(dirname "${RDI_BASEROOT}")"
export RDI_INSTALLVER="$(basename "${RDI_APPROOT}")"
export _RDI_SETENV_RUN=1
# (end AIEHLC change 1)

export RDI_NO_JRE=1
export RDI_DATA_DEPENDENCY=XILINX_VIVADO

#LD_LIBRARY_PATH=${RDI_APPROOT}/tps/lnx64/openmpi/lib:$LD_LIBRARY_PATH
#export LD_LIBRARY_PATH

export XILINX_VITIS_AIETOOLS=${RDI_APPROOT}

export _RDI_NEEDS_PYTHON=True

if [ -z "${PATH}" ]; then
  export TMP_PATH=""
  export PATH=${XILINX_VITIS_AIETOOLS}/tps/lnx64/gcc/bin/
else
  export TMP_PATH=${PATH}
  export PATH=${XILINX_VITIS_AIETOOLS}/tps/lnx64/gcc/bin/:${PATH}
fi

if [ -z "${LD_LIBRARY_PATH}" ]; then
  export TMP_LD_LIBRARY_PATH=""
  export LD_LIBRARY_PATH=${XILINX_VITIS_AIETOOLS}/tps/lnx64/gcc/lib64
else
  export TMP_LD_LIBRARY_PATH=${LD_LIBRARY_PATH}
  export LD_LIBRARY_PATH=${XILINX_VITIS_AIETOOLS}/tps/lnx64/gcc/lib64/:${LD_LIBRARY_PATH}
fi

##
# Launch the loader and specify the executable to launch
##
#
# Loader arguments:
#   -exec   -- Name of executable to launch
#   select correct binary
##
vcdoptions=
aiesimulator_options=
aiearch=aie
progname=aiesimmsm
dbgsuffix=
mt_model_enabled=false
mt_model_option=false
aie_sim_log_info=false
aie_sim_log_warn=false
aie_sim_log_debug=false
vaiml_memdump=false
vaiml_hang_detect=false

function set_aiearch() {
   if [ ! -d "$1" ]; then
      echo "[ERROR]: $1 directory does not exist"
      exit 1
   fi

   if [ -f $1/.target ]; then
      if [ $(< ${1}/.target) != "hw" ]; then
          >&2 echo "Error: The work directory '$1' is not generated for target hw."
          exit 1
      fi
   else
       >&2 echo "Error: File '$1/.target' does not exist."
       exit 1
   fi

   scscim_cofig_path="$1/config/scsim_config.json"
   if [ -f "$scscim_cofig_path" ]; then
      aiearch=$(grep -o '"aiearch": "[^"]*' $scscim_cofig_path | grep -o '[^"]*$')
   else
      echo "[ERROR]: AIE Simulator config Json file missing, file: $scscim_cofig_path"
      exit 1
   fi
   vcdoptions+="--pkg-dir $1 "
   aiesimulator_options=" --pkg-dir $1 --aiearch-version ${aiearch} $aiesimulator_options "
}

function config_mt_model() {
   if [ ! $# -eq 0 ]; then
      num_threads=`grep -nr "MTMAXTHREADS" "$1" | cut -d = -f2`
      if [ ! -z "$num_threads" ]; then
         export SIM_MULTI_CORES=$num_threads
      fi
   fi
}

function config_func_mode() {
   if [ ! $# -eq 0 ]; then
      aie_func_mode=`grep -nr "AIE_FUNCTIONAL_MODE" "$1" | cut -d = -f2`
      if [ ! -z "$aie_func_mode" ]; then
         export AIE_FUNC_MODE=$aie_func_mode
      fi
      # Currently for AIE2 only
      if [[ "${aie_func_mode}" == "core" ]]; then
         $XILINX_VITIS/aietools/data/aiesim/scripts/gen_core_func.py
      fi
   fi
}

while [[ $# -gt 0 ]]; do
   key="$1"
   case "$key" in
   -trace|--trace|--trace=*|-profile|--profile|--profile=*|--profile-only=*)
   dbgsuffix="_dbg"
   # Set port to zero to allocates TCL server port randomly.
   # This will allow multiple copies of aiesimulator running on same machine.
   if [[ -z "${ISS_RPC_SERVER_PORT}" ]]; then
     export ISS_RPC_SERVER_PORT=0
   fi
   aiesimulator_options+="$key "
   ;;
   -i|--input-dir)
   shift
   aiesimulator_options+="--input-dir $1 "
   ;;
   -i=*|--input-dir=*)
   aiesimulator_options+="--input-dir=${key#*=} "
   ;;
   -outdir|-o|--output-dir)
   shift
   vcdoptions+="--outdir $1 "
   aiesimulator_options+="--output-dir $1 "
   ;;
   -outdir=*|-o=*|--output-dir=*)
   vcdoptions+="--outdir ${key#*=} "
   aiesimulator_options+="--output-dir ${key#*=} "
   ;;
   -pkg|--pkg-dir)
   shift
   package_dir="${1}"
   set_aiearch "$package_dir"
   ;;
   --pkg-dir=*)
   package_dir="${key#*=}"
   set_aiearch "$package_dir"
   ;;
   -ctf | --ctf)
   echo "[WARNING]: -ctf option is deprecated. Please use -text to generate events.txt file"
   vcdoptions+="--text "
   aiesimulator_options+="--text "
   ;;
   -text | --text)
   vcdoptions+="--text "
   aiesimulator_options+="--text "
   ;;
   -wdb | --wdb)
   vcdoptions+="--wdb "
   aiesimulator_options+="--wdb "
   ;;
   --online)
   ONLINE=1
   uid=`uuidgen`
   vcdfile="/tmp/vcd_fifo_$uid"
   aiesimulator_options+="--vcd-pipe ${vcdfile} "
   vcdoptions+="--vcd ${vcdfile} "
   ;;
   -vcd|-w|--dump-vcd|--vcdfile)
   shift
   aiesimulator_options+="--dump-vcd $1 "
   VCDDUMP=1
   ;;
   --dump-vcd=*|-w=*)
   VCDFILE="${key#*=}"
   aiesimulator_options+="--dump-vcd=${VCDFILE} "
   VCDDUMP=1
   ;;
   --xdp|-xdp)
   aiesimulator_options+="--dump-xdp "
   ;;
   --aiesimulator-debug|-aiesimulator-debug)
   AIETOOLSDEBUG=1
   aiesimulator_options+="$key "
   ;;
   --mt-model=*)
   mt_model_enabled="${key#*=}"
   mt_model_option=true
   ;;
   # Add switch for full functional mode
   --func=*)
   export AIE_FUNC_MODE=${key#*=}
   if [[ "${AIE_FUNC_MODE}" == "core" ]]; then
       $XILINX_VITIS/aietools/data/aiesim/scripts/gen_core_func.py
   fi
   ;;
   # Add switch for vaiml_memdump
   --vaiml-memdump)
   vaiml_memdump=true
   ;;
   --vaiml-hang-detect)
   vaiml_hang_detect=true
   ;;

   --gmio-throughput-global-read=*)
   aiesimulator_options+="--gmio-throughput-global-read=${key#*=} "
   export GMIO_THROUGHPUT_GLOBAL_READ=${key#*=}
   ;;
   --gmio-throughput-global-read)
   shift
   aiesimulator_options+="--gmio-throughput-global-read $1 "
   export GMIO_THROUGHPUT_GLOBAL_READ=$1
   ;;
   --gmio-throughput-global-write=*)
   aiesimulator_options+="--gmio-throughput-global-write=${key#*=} "
   export GMIO_THROUGHPUT_GLOBAL_WRITE=${key#*=}
   ;;
   --gmio-throughput-global-write)
   shift
   aiesimulator_options+="--gmio-throughput-global-write $1 "
   export GMIO_THROUGHPUT_GLOBAL_WRITE=$1
   ;;
   --options-json)
   shift
   export AIE_OPTS_JSON=$1
   ;;
   -f|--options-file)
   shift
   aiesimulator_options+="--options-file $1 "
   if [[ "${mt_model_option}" == "false" ]]; then
      mt_model_enabled=`grep -nr "MTMODEL" "$1" | cut -d = -f2`
      if [ ! -z "$mt_model_enabled" ]; then
          mt_model_option=true
      fi
   fi
   config_mt_model "$1"
   config_func_mode "$1"
   if [[ "${aie_sim_log_info}" == "false" ]]; then
      aie_sim_log_info=`grep -nr "AIE_SIM_LOG_INFO" "$1" | cut -d = -f2`
   fi
   if [[ "${aie_sim_log_warn}" == "false" ]]; then
      aie_sim_log_warn=`grep -nr "AIE_SIM_LOG_WARN" "$1" | cut -d = -f2`
   fi
   if [[ "${aie_sim_log_debug}" == "false" ]]; then
      aie_sim_log_debug=`grep -nr "AIE_SIM_LOG_DEBUG" "$1" | cut -d = -f2`
   fi
   aie_latency_options=`grep -nr "AIE_LATENCY_OPTIONS" "$1" | cut -d = -f2`
   export AIE_LATENCY_OPTIONS=${aie_latency_options:-""}
   aie_gmio_throughput_global_read=`grep -nr "GMIO_THROUGHPUT_GLOBAL_READ" "$1" | cut -d = -f2`
   export GMIO_THROUGHPUT_GLOBAL_READ=${aie_gmio_throughput_global_read:-0}
   aie_gmio_throughput_global_write=`grep -nr "GMIO_THROUGHPUT_GLOBAL_WRITE" "$1" | cut -d = -f2`
   export GMIO_THROUGHPUT_GLOBAL_WRITE=${aie_gmio_throughput_global_write:-0}
   ;;
   --options-json=*)
   export AIE_OPTS_JSON="${key#*=}"
   ;;
   -f=*|--options-file=*)
   aiesimulator_options+="--options-file=${key#*=} "
   if [[ "${mt_model_option}" == "false" ]]; then
      mt_model_enabled=`grep -nr "MTMODEL" "${key#*=}" | cut -d = -f2`
      if [ ! -z "$mt_model_enabled" ]; then
          mt_model_option=true
      fi
   fi
   config_mt_model "${key#*=}"
   config_func_mode "${key#*=}"
   if [[ "${aie_sim_log_info}" == "false" ]]; then
      aie_sim_log_info=`grep -nr "AIE_SIM_LOG_INFO" "${key#*=}" | cut -d = -f2`
   fi
   if [[ "${aie_sim_log_warn}" == "false" ]]; then
      aie_sim_log_warn=`grep -nr "AIE_SIM_LOG_WARN" "${key#*=}" | cut -d = -f2`
   fi
   if [[ "${aie_sim_log_debug}" == "false" ]]; then
      aie_sim_log_debug=`grep -nr "AIE_SIM_LOG_DEBUG" "${key#*=}" | cut -d = -f2`
   fi
   aie_latency_options=`grep -nr "AIE_LATENCY_OPTIONS" "${key#*=}" | cut -d = -f2`
   export AIE_LATENCY_OPTIONS=${aie_latency_options:-""}
   aie_gmio_throughput_global_read=`grep -nr "GMIO_THROUGHPUT_GLOBAL_READ" "${key#*=}" | cut -d = -f2`
   export GMIO_THROUGHPUT_GLOBAL_READ=${aie_gmio_throughput_global_read:-0}
   aie_gmio_throughput_global_write=`grep -nr "GMIO_THROUGHPUT_GLOBAL_WRITE" "${key#*=}" | cut -d = -f2`
   export GMIO_THROUGHPUT_GLOBAL_WRITE=${aie_gmio_throughput_global_write:-0}
   ;;
   *)
   # AIE Simulator options
   aiesimulator_options+="$key "
   ;;
   esac
   # Shift after checking all the cases to get the next option
   shift
done

if [[ "X$VCDDUMP" != "X"  && "X$ONLINE" != "X" ]]; then
    echo "[ERROR]: AIE Simulation --online and --dump-vcd options are mutually exclusive, specifying both options are not supported."
    exit 1
fi

if [[ $aiesimulator_options != *"-help "* && $aiesimulator_options != *"-h "* && $aiesimulator_options != *"-help-list "* && $aiesimulator_options != *"-version "* ]]; then
if [[ $aiesimulator_options != *"--pkg-dir"* ]]; then
    echo "[INFO]: --pkg-dir not specified. Assuming ./Work as the default package directory."
    package_dir="./Work"
    set_aiearch "$package_dir"
fi
fi

if [[ "${aiearch}" == "aie" ]]; then
    if [[ "${mt_model_option}" == "false" || "${mt_model_enabled}" == "true" ]]; then
        progname=aiesimmsm
    else
        progname=aiesim
    fi
    export me_DIR=${RDI_APPROOT}/data/versal_prod/lib
    . ${RDI_APPROOT}/tps/lnx64/target/chess_env_LNa64.sh
elif [[ "${aiearch}" == "aie2" || "${aiearch}" == "aie-ml" ]]; then
    if [[ "${mt_model_option}" == "false" || "${mt_model_enabled}" == "true" ]]; then
        if [[ "${AIE_FUNC_MODE}" == "beta" || "${AIE_FUNC_MODE}" == "full" ]]; then
            progname=aie2simmsm_func
        elif [[ "${AIE_FUNC_MODE}" == "core" ]]; then
            progname=aie2simfunc
        else
            progname=aie2simmsm
        fi
        if [[ "${vaiml_memdump}" == "true" ]]; then
            #Check if AIE_FUNC_MODE is set. Use functional memdump library if AIE_FUNC_MODE is set
            if [[ "${AIE_FUNC_MODE}" == "beta" || "${AIE_FUNC_MODE}" == "full" ]]; then
                if [ -z "$dbgsuffix" ]; then
                    export MSM_DEBUGGER_LIB=${RDI_APPROOT}/lib/lnx64.o/libvaiml_memdump_func.so
                else
                    export MSM_DEBUGGER_LIB=${RDI_APPROOT}/lib/lnx64.o/libvaiml_memdump_dbg_func.so
                fi
            else
                if [ -z "$dbgsuffix" ]; then
                    export MSM_DEBUGGER_LIB=${RDI_APPROOT}/lib/lnx64.o/libvaiml_memdump.so
                else
                    export MSM_DEBUGGER_LIB=${RDI_APPROOT}/lib/lnx64.o/libvaiml_memdump_dbg.so
                fi
            fi
        fi
    else
        progname=aie2sim
    fi
    export me_DIR=${RDI_APPROOT}/data/aie_ml/lib
    . ${RDI_APPROOT}/tps/lnx64/target_aie_ml/chess_env_LNa64.sh
elif [ "${aiearch}" == "aie2p" ]; then
    if [[ "${mt_model_option}" == "false" ||  "${mt_model_enabled}" == "true" ]]; then
        progname=aie2psimmsm
        if [[ "${vaiml_memdump}" == "true" ]]; then
            if [ -z "$dbgsuffix" ]; then
                export MSM_DEBUGGER_LIB=${RDI_APPROOT}/lib/lnx64.o/libvaiml_memdump_aie2p.so
            else
                export MSM_DEBUGGER_LIB=${RDI_APPROOT}/lib/lnx64.o/libvaiml_memdump_aie2p_dbg.so
            fi
        fi
        #if AIE_FUNC_MODE is set, then set libraries as apt
        if [[ "${AIE_FUNC_MODE}" == "beta" || "${AIE_FUNC_MODE}" == "full" ]]; then
            progname=aie2psimmsm_func
            #Check if memdump is enabled
            if [[ "${vaiml_memdump}" == "true" ]]; then
                if [ -z "$dbgsuffix" ]; then
                    export MSM_DEBUGGER_LIB=${RDI_APPROOT}/lib/lnx64.o/libvaiml_memdump_aie2p_func.so
                else
                    export MSM_DEBUGGER_LIB=${RDI_APPROOT}/lib/lnx64.o/libvaiml_memdump_aie2p_dbg_func.so
                fi
            fi
        fi
        if [[ "${vaiml_hang_detect}" == "true" ]]; then
            export MSM_DEBUGGER_LIB=${RDI_APPROOT}/lib/lnx64.o/libvaiml_memdump_aie2p_overlay_4x4.so
        fi
    else
        progname=aie2psim
    fi
    export me_DIR=${RDI_APPROOT}/data/aie2p/lib
    . ${RDI_APPROOT}/tps/lnx64/target_aie2p/chess_env_LNa64.sh
elif [ "${aiearch}" == "aie2ps" ]; then
    if [[ "${mt_model_option}" == "false" ||  "${mt_model_enabled}" == "true" ]]; then
        if [[ "${AIE_FUNC_MODE}" == "beta" || "${AIE_FUNC_MODE}" == "full" ]]; then
            progname=aie2pssimmsm_func
        else
            progname=aie2pssimmsm
        fi
        if [[ "${vaiml_memdump}" == "true" ]]; then
            #Check if AIE_FUNC_MODE is set. Use functional memdump library if AIE_FUNC_MODE is set
            if [[ "${AIE_FUNC_MODE}" == "beta" || "${AIE_FUNC_MODE}" == "full" ]]; then
                if [ -z "$dbgsuffix" ]; then
                    export MSM_DEBUGGER_LIB=${RDI_APPROOT}/lib/lnx64.o/libvaiml_memdump_aie2ps_func.so
                else
                    export MSM_DEBUGGER_LIB=${RDI_APPROOT}/lib/lnx64.o/libvaiml_memdump_aie2ps_dbg_func.so
                fi
            else
                if [ -z "$dbgsuffix" ]; then
                    export MSM_DEBUGGER_LIB=${RDI_APPROOT}/lib/lnx64.o/libvaiml_memdump_aie2ps.so
                else
                    export MSM_DEBUGGER_LIB=${RDI_APPROOT}/lib/lnx64.o/libvaiml_memdump_aie2ps_dbg.so
                fi
            fi
        fi
        if [[ "${vaiml_hang_detect}" == "true" ]]; then
            if [ -z "$dbgsuffix" ]; then
                if [[ "${AIE_FUNC_MODE}" == "beta" || "${AIE_FUNC_MODE}" == "full" ]]; then
                    export MSM_DEBUGGER_LIB=${RDI_APPROOT}/lib/lnx64.o/libvaiml_memdump_aie2ps_func.so
                else
                    export MSM_DEBUGGER_LIB=${RDI_APPROOT}/lib/lnx64.o/libvaiml_memdump_aie2ps.so
                fi
            else
                if [[ "${AIE_FUNC_MODE}" == "beta" || "${AIE_FUNC_MODE}" == "full" ]]; then
                    export MSM_DEBUGGER_LIB=${RDI_APPROOT}/lib/lnx64.o/libvaiml_memdump_aie2ps_func.so
                else
                    export MSM_DEBUGGER_LIB=${RDI_APPROOT}/lib/lnx64.o/libvaiml_memdump_aie2ps_dbg_func.so
                fi
            fi
        fi
    else
        progname=aie2pssim
    fi
    export me_DIR=${RDI_APPROOT}/data/aie2ps/lib
    . ${RDI_APPROOT}/tps/lnx64/target_aie2ps/chess_env_LNa64.sh
fi

VCD_PROG="vcdanalyze"
RDI_PROG=${progname}${dbgsuffix}
aiesimulator_options=${aiesimulator_options//$'\r'}
vcdoptions=${vcdoptions//$'\r'}

# set RDI_VERBOSE=True to get DEBUG Info (also by default)
export RDI_VERBOSE=False

# AIEHLC: Change 2
# aiehlc_ps.so is self-contained (aie-rt SIM backend + ioutils compiled in),
# so no external runtime library injection is needed here.
# The PS .so path is specified in Work/config/scsim_config.json.

# Run the iss in the background... if we receive a signal, then pass it along to the iss so it
# shuts down cleanly.  The ps/grep magic extracts the process group ID and kills the whole
# group so that we don't have to worry about getting this right in every subshell.  setsid runs the
# resulting process with a new group id.
{
  if [[ $RDI_PROG == "aiesim" || $RDI_PROG == "aiesim_dbg" || $RDI_PROG == "aie2sim" || $RDI_PROG == "aie2sim_dbg" || $RDI_PROG == "aie2psim" || $RDI_PROG == "aie2psim_dbg" || $RDI_PROG == "aie2pssim" || $RDI_PROG == "aie2pssim_dbg" ]]; then
       echo "[ERROR]: aiesimulator option --mt-model=false is obsolate and not supported "
  else
       pid=
       setsid "$RDI_BINROOT"/loader -exec $RDI_PROG $aiesimulator_options & pid=$!
       sid=`ps -o sid= $pid | sed -e "s/^[ \t]*//" | grep -o "[0-9]*"`

       trap '[[ "X$pid"!="X" ]] && kill -INT -$sid' INT
       trap '[[ "X$pid"!="X" ]] && kill -TERM -$sid >& /dev/null' TERM ERR

       if [[ "X$ONLINE" != "X" ]]; then
            echo "Running AIE Simulator in Online mode..."
            if [ -z "$dbgsuffix" ]; then
                echo "[INFO]: If you are running trace or profile, AMD recommends to use --xlopt=0. This will give a greater visibility into the design. One can verify --xlopt level in the aiecompiler command line."
            fi
           "$RDI_BINROOT"/loader -exec $VCD_PROG ${vcdoptions} &> vcdanalyze.log &
           pid_loader_vcd=$!
           sleep 1
           pid_vcd=$(pgrep -P $pid_loader_vcd)
           trap '[[ "X$pid_loader_vcd"!="X" ]] && kill -9 $pid_loader_vcd; [[ "X$pid_vcd"!="X" ]] && kill -9 $pid_vcd' INT
           wait "$pid" "$pid_loader_vcd"
       else
           wait "$pid"
       fi
       wait "$sid"
       exit $?
  fi
} 2>&1 | tee AIESimulator.log
export EXIT_CODE=${PIPESTATUS[0]}
export PATH=${TMP_PATH}
export LD_LIBRARY_PATH=${TMP_LD_LIBRARY_PATH}

exit ${EXIT_CODE}