/******************************************************************************
* Copyright (C) 2025 Advanced Micro Devices, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT
******************************************************************************/
#include "dshostmanager.h"
#include <iostream>

#define GET_TYPEDEF_CLASSES
#define GET_ATTRDEF_CLASSES
#define GET_OP_CLASSES
#define GET_OP_DEFS
//#define GET_OP_LIST
#include "dshostdialect.cc.inc"
#include "dshostattr.cc.inc"
#include "dshosttype.cc.inc"
#include "dshostenums.cc.inc"

#include "dshostop.cc.inc"
//#undef GET_OP_LIST
#undef GET_OP_DEFS

#undef GET_OP_CLASSES
#undef GET_ATTRDEF_CLASSES
#undef GET_TYPEDEF_CLASSES

void dshostdialect::initialize()  { 
    addOperations<
    #define GET_OP_LIST
    #include "dshostop.cc.inc"
        >();
    // 如果有 Attr / Type：addAttributes<...>(); addTypes<...>();
     addAttributes<
    #define GET_ATTRDEF_LIST
    #include "dshostattr.cc.inc"
    >();

        // 3. Types
    addTypes<
    #define GET_TYPEDEF_LIST
    #include "dshosttype.cc.inc"
    >();
}

/*
void dshostdialect::printType(Type type, DialectAsmPrinter &printer) const {
    // This is the C++ type generated by TableGen from your TypeDef.
    // Ensure you use the correct name (e.g., DMAPDataType).
    if (isa<dshostdataType>(type)) {
        // All you need to do is print the mnemonic you defined in TableGen.
        printer << "dshostdata";
    }
}
//*/


ModuleOp dshostmanager::ops_test(MLIRContext* ctx, int totalN) {
    const int hwrowused= 4, hwcolused=4;
    OpBuilder builder(ctx);
    mlir::ModuleOp m = ModuleOp::create(builder.getUnknownLoc());
    //auto func = createdshostfuncByDim(ctx, true);
    //m.push_back(func);
    auto functype = builder.getFunctionType({},{});
    
    dshost::FuncOp main = builder.create<dshost::FuncOp>(builder.getUnknownLoc(), "main", functype);
    m.push_back(main);
    //auto block = main.addEntryBlock();
    auto &block = main.getBody().emplaceBlock();
    builder.setInsertionPointToEnd(&block);

    SymbolTable symTable(main);

    createdshostfuncByDim(builder, ctx, symTable);
    auto retop = builder.create<mlir::func::ReturnOp>(builder.getUnknownLoc());
    
  // ------------------------------------------------------------------
  // 4. Look up the symbol anywhere inside the module
  // ------------------------------------------------------------------
    Operation *found = symTable.lookup("receive1");
    if (!found) {
        llvm::errs() << "Symbol @receive1 not found!\n";
   } else {
        llvm::outs() << "receive1 found \n";
        llvm::outs() << "Found: " << found->getName() <<"\n";
   }
    llvm::errs() << m;
    return m;
}

void dshostmanager::loaddialect(MLIRContext* ctx) {
    ctx->getOrLoadDialect<mlir::func::FuncDialect>();
    ctx->getOrLoadDialect<dshost::dshostdialect>();
    ctx->getOrLoadDialect<mlir::scf::SCFDialect>();
    ctx->getOrLoadDialect<mlir::arith::ArithDialect>();
}
/*
      %data = dataflowmap.create_data {type="i32", dim1=10, dim2 20}
      %coreenginegroup = dataflowmap.dshost_create_core_engine_group {1, 4, "row"}
      %ioengine = dataflowmap.dshost_create_io_engine {0, "shim"}
      %send_port = dataflowmap.configure_port %ioengine {peorioidx=0, dataacces=}  
      %portreceive1 = dataflowmap.configure_port on %{peorioidx = 0, dataacces=}  
      %portreceive2 = dataflowmap.configure_port on %{peorioidx = 1, dataacces=}   
      %receive_group = dataflowmap.create_port_group(%portreceive1, %portreceive2)    
      %broadcast_stream = dataflowmap.create_stream %send_port, %receive_group         
      dataflowmap.push %data, %broadcast_stream {cache_policy = "force_memtile" }
*/
void dshostmanager::createdshostfuncByDim(OpBuilder& builder, MLIRContext* ctx,SymbolTable& symTable) {
        auto location = builder.getUnknownLoc();
        // no region creatation
    ///*   
        mlir::SmallVector<mlir::Attribute, 4> shapeElems;
        shapeElems.push_back(builder.getI64IntegerAttr(16));
        shapeElems.push_back(builder.getI64IntegerAttr(16));
        mlir::ArrayAttr shapettr = mlir::ArrayAttr::get(ctx, shapeElems);
        mlir::Type elementType = builder.getF32Type();
        mlir::Type myDataHandleType = dshost::dshostdataType::get(ctx);
        auto data = builder.create<create_data>(builder.getUnknownLoc(),  myDataHandleType, shapettr, elementType); 
        mlir::Type pgeout = dshost::dmacoreenginegroupType::get(ctx);
        auto peg = builder.create<create_core_engine_group>(builder.getUnknownLoc(),  pgeout, 0, 4, "row"); 
        mlir::Type ioout = dshost::dshostioenginetypeType::get(ctx);
        auto io = builder.create<create_io_engine>(builder.getUnknownLoc(),  ioout, 0, "SHIM"); 
        auto memio = builder.create<create_io_engine>(builder.getUnknownLoc(),  ioout, 0, "MEM"); 
        //config port
        auto ioconfigret = dshost::dshostioconfigType::get(ctx);
        auto dataaccesspattern = dshost::dataaccesspatternAttr::get(ctx, builder.getStringAttr("SEND"), 16, 1, 1);
        auto memsndpattern = dshost::dataaccesspatternAttr::get(ctx, builder.getStringAttr("SEND"), 16, 1, 1);
        auto memreceivepattern = dshost::dataaccesspatternAttr::get(ctx, builder.getStringAttr("RECEIVE"), 16, 1, 1);
        auto receivepattern = dshost::dataaccesspatternAttr::get(ctx, builder.getStringAttr("RECEIVE"), 16, 1, 1);
        // create a port configuration
        //port_configure_create
        
        mlir::Type portconfig = dshost::dshostportconfigType::get(ctx);
        std::string symbolName = "receive1";
        auto pf = builder.create<dshost::port_configure_create>(builder.getUnknownLoc(), portconfig, symbolName, receivepattern);
        symTable.insert(pf);
        mlir::SymbolRefAttr symbolRef = mlir::SymbolRefAttr::get(ctx,"receive1");
        //auto useOp = builder.create<dshost::UseSymbolOp>(builder.getUnknownLoc(), symbolRef);
        //config io port 
        auto shimioconfig = builder.create<configure_io_engine>(builder.getUnknownLoc(),  ioconfigret,  io.getResult(),dataaccesspattern);
        //config port group
        dshost::dataconfmapitemAttr item1 = dshost::dataconfmapitemAttr::get(ctx,0, mlir::SymbolRefAttr::get(ctx, "receive1"));
        dshost::dataconfmapitemAttr item2 = dshost::dataconfmapitemAttr::get(ctx,1, mlir::SymbolRefAttr::get(ctx, "receive1"));
        dshost::dataconfmapitemAttr item3 = dshost::dataconfmapitemAttr::get(ctx,2, mlir::SymbolRefAttr::get(ctx, "receive1"));
        dshost::dataconfmapitemAttr item4 = dshost::dataconfmapitemAttr::get(ctx,3, mlir::SymbolRefAttr::get(ctx, "receive1"));
        llvm::SmallVector<dshost::dataconfmapitemAttr> itemsVector;
        itemsVector.push_back(item1);
        itemsVector.push_back(item2);
        itemsVector.push_back(item3);
        itemsVector.push_back(item4);
        dshost::dataconfigmapAttr configMapAttr = dshost::dataconfigmapAttr::get(ctx,itemsVector);
        auto gcret = dshost::dmacoregroupconfigType::get(ctx);
        auto gcmap = builder.create<configure_coregroup>(builder.getUnknownLoc(),  gcret, peg.getResult(), "row", configMapAttr);
        //create strem
        auto streamret = dshost::dshostportstreamType::get(ctx);
        bool opbymemio = false;
        if (opbymemio) {
            auto memiorecvconfig = builder.create<configure_io_engine>(builder.getUnknownLoc(),  ioconfigret,  memio.getResult(),memreceivepattern);
            auto memiosendconfig = builder.create<configure_io_engine>(builder.getUnknownLoc(),  ioconfigret,  memio.getResult(),memsndpattern);
            
            auto shimToMemAttr = dshostioAttr::get(ctx, dshostio::DMAP_SHIMIO);
            auto memToCoreAttr = dshostioAttr::get(ctx, dshostio::DMAP_MEMTILEIO);
            
            auto groupIndexAttr = builder.getI32IntegerAttr(0);
            auto streamIdAttr1 = builder.getI32IntegerAttr(1);
            
            auto streamhandle1 = builder.create<createstream>(builder.getUnknownLoc(),  streamret, shimioconfig.getResult(),memiorecvconfig.getResult(), shimToMemAttr, groupIndexAttr, streamIdAttr1);
            auto streamhandle2 = builder.create<createstream>(builder.getUnknownLoc(),  streamret, memiosendconfig.getResult(),gcmap.getResult(), memToCoreAttr, groupIndexAttr, streamIdAttr1);

            // Create a chained stream from streamhandle1 and streamhandle2, then push once to the chained stream.
            auto chainType = dshost::dshostportchainstreamType::get(ctx);
            // The generated op build expects (TypeRange resultTypes, ValueRange operands, ArrayRef<NamedAttribute> attrs).
            auto chainStreamOp = builder.create<createchainstream>(builder.getUnknownLoc(),
                                                                   chainType,
                                                                   mlir::ValueRange{streamhandle1.getResult(),
                                                                                    streamhandle2.getResult()});
            auto chainStream = chainStreamOp.getResult();

            // Single push that targets the chained stream (replaces pret1 and pret2)
            auto pchain = builder.create<push>(builder.getUnknownLoc(), data.getResult(), chainStream);

        } else {
            auto shimToCoreAttr = dshostioAttr::get(ctx, dshostio::DMAP_SHIMIO);
            
            auto groupIndexAttr = builder.getI32IntegerAttr(0);
            auto streamIdAttr = builder.getI32IntegerAttr(1);
            
            auto streamhandle = builder.create<createstream>(builder.getUnknownLoc(),  streamret, shimioconfig.getResult(),gcmap.getResult(), shimToCoreAttr, groupIndexAttr, streamIdAttr);
            auto pret = builder.create<push>(builder.getUnknownLoc(), data.getResult(),streamhandle.getResult());
        }
        //push stream
        

        //config core port
        //auto dataaccesspattern1 = dshost::dataaccesspatternAttr::get(ctx, builder.getStringAttr("RECEIVE"), 16, 1, 1);
        //auto cport0 = builder.create<configure_io>(builder.getUnknownLoc(),  portret, peg.getResult(),0, dataaccesspattern1);
        //auto cport1 = builder.create<configure_io>(builder.getUnknownLoc(),  portret, peg.getResult(),1, dataaccesspattern1); 
        //auto cport2 = builder.create<configure_io>(builder.getUnknownLoc(),  portret, peg.getResult(),2, dataaccesspattern1); 
        //auto cport3 = builder.create<configure_io>(builder.getUnknownLoc(),  portret, peg.getResult(),3, dataaccesspattern1);  
        //create port group
        //mlir::SmallVector<mlir::Value, 4> portlist;
        //portlist.push_back(cport0.getResult());
        //portlist.push_back(cport1.getResult());
        //portlist.push_back(cport2.getResult());
        //portlist.push_back(cport3.getResult());

        //auto portg = dshost::dshostportgroupType::get(ctx);
        //auto portgroup = builder.create<createport_group>(builder.getUnknownLoc(),  ioout, portlist);  
        return ;//func;
}
