###############################################################################
# Copyright (C) 2026 Advanced Micro Devices, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
###############################################################################
"""Emit the int8 ResNet-18 v2 oracle as plain C + a weight blob.

The generated C is a **transcription** of ``qresnet.QuantResNet18.forward`` —
same layer order, same integer arithmetic, same requantization — so the two can
be diffed numerically layer by layer. Anything the C computes differently from
the numpy oracle is a bug in this file, not a modelling choice.

Weights are emitted as a **binary blob**, not C array literals
----------------------------------------------------------------
ResNet-18 is 11.68 MB of int8 weights. As `int8_t w[] = {...}` that is roughly a
40 MB source file, which is slow to compile and, more importantly, makes the
per-layer offsets invisible. Instead the weights go to ``weights.bin`` and are
linked in with ``ld -r -b binary`` (the same mechanism the AIE flow already uses
to embed kernel ELFs into the host). The C reads them through a generated table
of offsets, so the layout is one place and checkable.

Where the C legitimately differs from the numpy oracle
------------------------------------------------------
The residual add. The oracle sums ``out_f + skip_f`` in float and quantizes the
result once; the C receives two int8 tensors and must rescale-and-round each
branch before summing (``q_add``). That is one extra rounding per branch per
block, compounded over 8 residual blocks, and it is inherent to an all-int8
dataflow rather than a defect — a float intermediate would mean the tensor
crossing that layer boundary is not int8.

Measured cost on the reference image: top-1 unchanged (Samoyed), confidence
89.1% -> 83.9%, top-5 membership shuffled below rank 1. Both remain 4/5 against
the float model. If that margin ever matters, the fix is to widen the residual
accumulator to int16 or int32 rather than to reintroduce float.

Fixed-point requantization
--------------------------
The numpy oracle keeps the requant multiplier as float32. Here it becomes an
int32 multiplier plus a right shift::

    M_real ≈ M_int / 2^shift        (M_int in [2^30, 2^31))
    out    = (acc * M_int + rounding) >> shift

chosen per output channel. ``emit_requant_params`` picks the largest shift that
keeps ``M_int`` inside int32, which maximizes retained precision. The C uses
int64 for the intermediate product — ``acc`` can approach 2^22 and ``M_int``
2^31, so int32 would overflow.

Layer config is int32, not int8
-------------------------------
The existing AIE path packs ``{H,W,Cin,Cout,K,stride}`` as int8 (ceiling 255);
real ResNet-18 has 512 channels and 1000 classes. This emitter therefore uses a
plain C struct with ``int`` fields rather than the packed int8 header.
"""

import os
import struct
from typing import Dict, List, Tuple

import numpy as np

_COPYRIGHT = (
    "/******************************************************************************\n"
    " * Copyright (C) 2026 Advanced Micro Devices, Inc. All Rights Reserved.\n"
    " * SPDX-License-Identifier: Apache-2.0\n"
    " * GENERATED by src/frontend/tvm/quant/emit_c.py -- do not edit by hand.\n"
    " ******************************************************************************/\n")

# int32 multipliers are normalized into [2^30, 2^31) to retain precision.
_M_LO, _M_HI = 1 << 30, 1 << 31


# ═══════════════════════════════════════════════════════════════════════════
#  Fixed-point requantization parameters
# ═══════════════════════════════════════════════════════════════════════════

def to_fixed_point(m: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """Split float multipliers into ``(int32 multiplier, right shift)``.

    For each ``m[c]`` finds ``(M, s)`` with ``m ≈ M / 2^s`` and ``|M|`` in
    ``[2^30, 2^31)``.

    **The multiplier may be negative.** It folds in the BN scale
    ``gamma/sqrt(var+eps)``, and a trained BN can legitimately learn a negative
    gamma — 4 of ResNet-18's 3971 BN channels do. Taking ``|m|`` and dropping
    the sign (or treating ``m <= 0`` as degenerate) silently zeroes those
    channels, which is a real accuracy loss that no shape check would catch. The
    sign is therefore carried on ``M`` itself; C's ``>>`` on a negative int64 is
    an arithmetic shift, which rounds toward negative infinity consistently.

    A genuinely zero multiplier maps to ``(0, 0)`` so that channel contributes
    nothing rather than producing a NaN.
    """
    m = np.asarray(m, dtype=np.float64)
    mult = np.zeros(m.shape, dtype=np.int64)
    shift = np.zeros(m.shape, dtype=np.int32)
    for i, v in enumerate(m.ravel()):
        if not np.isfinite(v) or v == 0.0:
            continue
        sign = -1 if v < 0 else 1
        frac, exp = np.frexp(abs(v))             # frac in [0.5,1), |v|=frac*2^exp
        M = int(round(frac * (1 << 31)))         # frac*2^31 in [2^30, 2^31]
        s = 31 - exp
        if M >= _M_HI:                           # rounding pushed it over
            M //= 2
            s -= 1
        if s < 0:                                # multiplier > 1: rare but legal
            M <<= -s
            s = 0
        mult.ravel()[i] = sign * M
        shift.ravel()[i] = s
    return mult.astype(np.int64), shift


def verify_fixed_point(m: np.ndarray, mult: np.ndarray,
                       shift: np.ndarray) -> float:
    """Return the max relative error of the fixed-point approximation.

    Normalized by ``max|m|`` (not per element) so a near-zero multiplier cannot
    dominate the ratio; negative multipliers are compared by magnitude.
    """
    approx = mult.astype(np.float64) / (2.0 ** shift.astype(np.float64))
    ref = np.asarray(m, dtype=np.float64)
    nz = ref != 0
    if not np.any(nz):
        return 0.0
    return float(np.abs(approx[nz] - ref[nz]).max() / np.abs(ref[nz]).max())


def _bias_in_acc_domain(bias_out_scale: np.ndarray,
                        mult: np.ndarray) -> np.ndarray:
    """Convert a bias expressed in output-scale units into accumulator units.

    The C kernels add the bias BEFORE applying the multiplier — ``(acc + b)*m``
    — because that keeps the bias an int32 and avoids a second rounding. So a
    bias we know in output units (``shift/s_out``) must be pre-divided by ``m``.
    Passing it through unconverted scales it by ``m`` a second time, which is a
    silent accuracy loss: the network still classifies, just less confidently.

    Channels with ``m == 0`` contribute nothing regardless, so their bias is
    forced to 0 rather than dividing by zero.
    """
    m = np.asarray(mult, dtype=np.float64)
    safe = np.where(m == 0, 1.0, m)
    return np.where(m == 0, 0.0, np.asarray(bias_out_scale, np.float64) / safe)


# ═══════════════════════════════════════════════════════════════════════════
#  Weight blob
# ═══════════════════════════════════════════════════════════════════════════

class BlobWriter:
    """Accumulates tensors into one binary blob, recording name -> offset.

    Every tensor is 4-byte aligned so the int32 arrays (multipliers, shifts,
    biases) can be read through aligned pointers on aarch64.
    """

    def __init__(self) -> None:
        self.buf = bytearray()
        self.offsets: Dict[str, Tuple[int, int]] = {}   # name -> (offset, count)

    def add(self, name: str, arr: np.ndarray, dtype: str) -> int:
        if name in self.offsets:
            raise ValueError(f"duplicate blob entry {name!r}")
        while len(self.buf) % 4:
            self.buf.append(0)
        off = len(self.buf)
        self.buf.extend(np.ascontiguousarray(arr, dtype=dtype).tobytes())
        self.offsets[name] = (off, int(np.asarray(arr).size))
        return off

    def write(self, path: str) -> int:
        with open(path, "wb") as f:
            f.write(self.buf)
        return len(self.buf)


# ═══════════════════════════════════════════════════════════════════════════
#  Runtime C: the fixed-point kernels the generated main calls
# ═══════════════════════════════════════════════════════════════════════════
#
# These mirror qresnet.py op for op. Kept as one static string (rather than
# generated per layer) because the arithmetic is layer-independent -- only the
# shapes and parameter offsets vary, and those arrive as arguments.

RUNTIME_C = r"""
#include <stdint.h>
#include <string.h>

/* Requantize one int32 accumulator with a per-channel signed fixed-point
 * multiplier. int64 intermediate is required: acc can reach ~2^22 and |mult|
 * ~2^31, so an int32 product would overflow. The shift is arithmetic, which
 * rounds toward -inf; the +half term restores round-to-nearest. */
static inline int8_t requant(int32_t acc, int64_t mult, int32_t shift,
                             int32_t zp_out) {
    int64_t v = (int64_t)acc * mult;
    if (shift > 0) {
        int64_t half = (int64_t)1 << (shift - 1);
        v = (v + (v >= 0 ? half : -half)) >> shift;
    }
    v += zp_out;
    if (v < -128) v = -128;
    if (v >  127) v =  127;
    return (int8_t)v;
}

/* int8 conv2d, NCHW. Padding uses zp_in so that after the -zp_in shift the
 * padded taps contribute exactly zero (matching float zero-padding). */
void q_conv2d(const int8_t *in, int Cin, int H, int W,
              const int8_t *wt, int Cout, int K, int stride, int pad,
              int32_t zp_in,
              const int64_t *mult, const int32_t *shift,
              const int32_t *bias, int32_t zp_out,
              int do_relu, int8_t *out) {
    int OH = (H + 2 * pad - K) / stride + 1;
    int OW = (W + 2 * pad - K) / stride + 1;
    for (int oc = 0; oc < Cout; ++oc) {
        for (int oh = 0; oh < OH; ++oh) {
            for (int ow = 0; ow < OW; ++ow) {
                int32_t acc = bias ? bias[oc] : 0;
                for (int ic = 0; ic < Cin; ++ic) {
                    for (int kh = 0; kh < K; ++kh) {
                        int ih = oh * stride + kh - pad;
                        if (ih < 0 || ih >= H) continue;
                        for (int kw = 0; kw < K; ++kw) {
                            int iw = ow * stride + kw - pad;
                            if (iw < 0 || iw >= W) continue;
                            int32_t a = (int32_t)in[(ic * H + ih) * W + iw] - zp_in;
                            int32_t b = (int32_t)wt[((oc * Cin + ic) * K + kh) * K + kw];
                            acc += a * b;
                        }
                    }
                }
                int8_t q = requant(acc, mult[oc], shift[oc], zp_out);
                if (do_relu && q < zp_out) q = (int8_t)zp_out;
                out[(oc * OH + oh) * OW + ow] = q;
            }
        }
    }
}

/* Per-channel affine (a folded BatchNorm) applied directly to int8. */
void q_affine(const int8_t *in, int C, int H, int W, int32_t zp_in,
              const int64_t *mult, const int32_t *shift, const int32_t *bias,
              int32_t zp_out, int do_relu, int8_t *out) {
    for (int c = 0; c < C; ++c) {
        for (int i = 0; i < H * W; ++i) {
            int32_t acc = (int32_t)in[c * H * W + i] - zp_in;
            acc += bias ? bias[c] : 0;
            int8_t q = requant(acc, mult[c], shift[c], zp_out);
            if (do_relu && q < zp_out) q = (int8_t)zp_out;
            out[c * H * W + i] = q;
        }
    }
}

/* Max pool on int8. Max commutes with a monotonically increasing affine, so
 * pooling the quantized values equals quantizing the pooled floats. */
void q_maxpool(const int8_t *in, int C, int H, int W, int k, int stride,
               int pad, int8_t *out) {
    int OH = (H + 2 * pad - k) / stride + 1;
    int OW = (W + 2 * pad - k) / stride + 1;
    for (int c = 0; c < C; ++c)
        for (int oh = 0; oh < OH; ++oh)
            for (int ow = 0; ow < OW; ++ow) {
                int32_t best = -128;
                for (int kh = 0; kh < k; ++kh) {
                    int ih = oh * stride + kh - pad;
                    if (ih < 0 || ih >= H) continue;
                    for (int kw = 0; kw < k; ++kw) {
                        int iw = ow * stride + kw - pad;
                        if (iw < 0 || iw >= W) continue;
                        int32_t v = in[(c * H + ih) * W + iw];
                        if (v > best) best = v;
                    }
                }
                out[(c * OH + oh) * OW + ow] = (int8_t)best;
            }
}

/* Residual add of two int8 tensors on DIFFERENT scales.
 * Each side is rescaled into the output scale by its own fixed-point
 * multiplier before summing -- adding the raw int8 values would be wrong
 * whenever the two branches carry different scales, which they generally do. */
void q_add(const int8_t *a, int32_t zp_a, int64_t mult_a, int32_t shift_a,
           const int8_t *b, int32_t zp_b, int64_t mult_b, int32_t shift_b,
           int n, int32_t zp_out, int8_t *out) {
    for (int i = 0; i < n; ++i) {
        int64_t va = (int64_t)((int32_t)a[i] - zp_a) * mult_a;
        int64_t vb = (int64_t)((int32_t)b[i] - zp_b) * mult_b;
        if (shift_a > 0) {
            int64_t h = (int64_t)1 << (shift_a - 1);
            va = (va + (va >= 0 ? h : -h)) >> shift_a;
        }
        if (shift_b > 0) {
            int64_t h = (int64_t)1 << (shift_b - 1);
            vb = (vb + (vb >= 0 ? h : -h)) >> shift_b;
        }
        int64_t v = va + vb + zp_out;
        if (v < -128) v = -128;
        if (v >  127) v =  127;
        out[i] = (int8_t)v;
    }
}

/* Global average pool: exact integer mean over the spatial plane. */
void q_global_avgpool(const int8_t *in, int C, int H, int W, int32_t zp_in,
                      const int64_t *mult, const int32_t *shift,
                      int32_t zp_out, int8_t *out) {
    int n = H * W;
    for (int c = 0; c < C; ++c) {
        int32_t s = 0;
        for (int i = 0; i < n; ++i) s += (int32_t)in[c * n + i] - zp_in;
        /* Divide first (round-to-nearest, sign-aware), then requantize. */
        int32_t avg = (s >= 0) ? (s + n / 2) / n : -((-s + n / 2) / n);
        out[c] = requant(avg, mult[c], shift[c], zp_out);
    }
}

/* Fully-connected producing float32 logits (the final dequantization). */
void q_gemm_f32(const int8_t *in, int Cin, int32_t zp_in,
                const int8_t *wt, int Cout, const float *scale,
                const float *bias, float *out) {
    for (int o = 0; o < Cout; ++o) {
        int32_t acc = 0;
        for (int i = 0; i < Cin; ++i)
            acc += ((int32_t)in[i] - zp_in) * (int32_t)wt[o * Cin + i];
        out[o] = (float)acc * scale[o] + bias[o];
    }
}
"""


# ═══════════════════════════════════════════════════════════════════════════
#  Model walk -> blob + generated main
# ═══════════════════════════════════════════════════════════════════════════
#
# Shapes are computed here (at emit time) rather than at runtime: every tensor
# size is a compile-time constant of the network, so the generated C allocates
# exact buffers and a shape bug surfaces as a build-time mismatch.

def _conv_out(h: int, k: int, stride: int, pad: int) -> int:
    return (h + 2 * pad - k) // stride + 1


class ResNetCEmitter:
    """Walk a ``QuantResNet18`` and emit ``weights.bin`` + ``resnet_int8.c``."""

    def __init__(self, q, in_hw: int = 224):
        self.q = q
        self.in_hw = in_hw
        self.blob = BlobWriter()
        self.calls: List[str] = []      # generated statements for run_resnet()
        self.bufs: Dict[str, int] = {}  # buffer name -> byte size
        self._n = 0

    # ── blob helpers ───────────────────────────────────────────────────────
    def _put_requant(self, tag: str, mult_f: np.ndarray,
                     bias: np.ndarray = None) -> None:
        """Store per-channel fixed-point multiplier/shift (+ optional bias)."""
        mult, shift = to_fixed_point(mult_f)
        err = verify_fixed_point(mult_f, mult, shift)
        if err > 1e-6:
            raise ValueError(f"{tag}: fixed-point error {err:.2e} too large")
        self.blob.add(f"{tag}_mult", mult, "<i8")
        self.blob.add(f"{tag}_shift", shift, "<i4")
        if bias is not None:
            self.blob.add(f"{tag}_bias", np.round(bias).astype(np.int64), "<i4")

    def _buf(self, name: str, nbytes: int) -> str:
        self.bufs[name] = max(self.bufs.get(name, 0), nbytes)
        return name

    # ── emit ───────────────────────────────────────────────────────────────
    def emit(self, out_dir: str) -> Dict[str, object]:
        """Generate into ``out_dir``; returns a manifest dict."""
        os.makedirs(out_dir, exist_ok=True)
        q = self.q
        qp = q.qp
        H = self.in_hw

        # -- input + BN0 (standalone affine; v2 has no conv to fold it into) --
        self.blob.add("input_dummy", np.zeros(1, np.int8), "<i1")
        sc, sh = q.bn["bn0"]
        # in-scale -> out-scale with the BN affine folded in
        m = qp["input"].scale * sc / qp["bn0"].scale
        # Bias is added BEFORE the multiply (see q_affine), so it must live in
        # the accumulator domain: the C computes (acc + b)*m, and we want
        # acc*m + shift/s_out, hence b = shift/s_out/m. Passing shift/s_out
        # directly would scale the bias by m a second time.
        b = _bias_in_acc_domain(sh / qp["bn0"].scale, m)
        self._put_requant("bn0", m, b)

        a = self._buf("bufA", 3 * H * H)
        o = self._buf("bufB", 3 * H * H)
        self.calls.append(
            f"    q_affine({a}, 3, {H}, {H}, {qp['input'].zp}, "
            f"B_I64(bn0_mult), B_I32(bn0_shift), B_I32(bn0_bias), "
            f"{qp['bn0'].zp}, 0, {o});")

        # -- conv0 7x7/s2 + BN1 + ReLU --
        Cout, Cin, K, _ = q.qw["conv0"].shape
        self.blob.add("conv0_w", q.qw["conv0"], "<i1")
        bsc, bsh = q.bn["bn1"]
        m = qp["bn0"].scale * q.sw["conv0"] * bsc / qp["stem_act"].scale
        # BN shift enters the accumulator domain: acc*m + shift/s_out
        b = _bias_in_acc_domain(bsh / qp["stem_act"].scale, m)
        self._put_requant("conv0", m, b)
        OH = _conv_out(H, K, 2, 3)
        src, dst = o, self._buf("bufA", Cout * OH * OH)
        self.calls.append(
            f"    q_conv2d({src}, {Cin}, {H}, {H}, B_I8(conv0_w), {Cout}, {K}, "
            f"2, 3, {qp['bn0'].zp}, B_I64(conv0_mult), B_I32(conv0_shift), "
            f"B_I32(conv0_bias), {qp['stem_act'].zp}, 1, {dst});")

        # -- maxpool 3x3/s2 --
        PH = _conv_out(OH, 3, 2, 1)
        src, dst = dst, self._buf("bufB", Cout * PH * PH)
        self.calls.append(
            f"    q_maxpool({src}, {Cout}, {OH}, {OH}, 3, 2, 1, {dst});")

        cur, curC, curH, cur_tag = dst, Cout, PH, "stem_act"
        ping = 0    # alternate bufA/bufB for the block chain

        for blk in q.struct:
            t = blk["tag"]
            stride = blk["stride"]
            # pre-activation BN -> ReLU
            sc, sh = q.bn[f"{t}_bn1"]
            m = qp[cur_tag].scale * sc / qp[f"{t}_preact"].scale
            b = _bias_in_acc_domain(sh / qp[f"{t}_preact"].scale, m)
            self._put_requant(f"{t}_pre", m, b)
            pre = self._buf("bufPre", curC * curH * curH)
            self.calls.append(
                f"    q_affine({cur}, {curC}, {curH}, {curH}, {qp[cur_tag].zp}, "
                f"B_I64({t}_pre_mult), B_I32({t}_pre_shift), "
                f"B_I32({t}_pre_bias), {qp[f'{t}_preact'].zp}, 1, {pre});")

            # conv1 (+BN2+ReLU)
            C1, _, K1, _ = q.qw[f"{t}_c1"].shape
            self.blob.add(f"{t}_c1_w", q.qw[f"{t}_c1"], "<i1")
            bsc, bsh = q.bn[f"{t}_bn2"]
            m = qp[f"{t}_preact"].scale * q.sw[f"{t}_c1"] * bsc / qp[f"{t}_act2"].scale
            b = _bias_in_acc_domain(bsh / qp[f"{t}_act2"].scale, m)
            self._put_requant(f"{t}_c1", m, b)
            H1 = _conv_out(curH, K1, stride, 1)
            mid = self._buf("bufMid", C1 * H1 * H1)
            self.calls.append(
                f"    q_conv2d({pre}, {curC}, {curH}, {curH}, B_I8({t}_c1_w), "
                f"{C1}, {K1}, {stride}, 1, {qp[f'{t}_preact'].zp}, "
                f"B_I64({t}_c1_mult), B_I32({t}_c1_shift), B_I32({t}_c1_bias), "
                f"{qp[f'{t}_act2'].zp}, 1, {mid});")

            # conv2 -> its own intermediate scale (no BN, no ReLU)
            C2, _, K2, _ = q.qw[f"{t}_c2"].shape
            self.blob.add(f"{t}_c2_w", q.qw[f"{t}_c2"], "<i1")
            s_c2 = qp[f"{t}_act2"].scale * q.sw[f"{t}_c2"]
            # Land conv2 on the block-output scale directly.
            m = s_c2 / qp[f"{t}_out"].scale
            self._put_requant(f"{t}_c2", m)
            H2 = _conv_out(H1, K2, 1, 1)
            main = self._buf("bufMain", C2 * H2 * H2)
            self.calls.append(
                f"    q_conv2d({mid}, {C1}, {H1}, {H1}, B_I8({t}_c2_w), {C2}, "
                f"{K2}, 1, 1, {qp[f'{t}_act2'].zp}, B_I64({t}_c2_mult), "
                f"B_I32({t}_c2_shift), (const int32_t*)0, "
                f"{qp[f'{t}_out'].zp}, 0, {main});")

            # skip: 1x1 projection off the pre-activation, or the block input
            if blk["down"]:
                CD, _, KD, _ = q.qw[f"{t}_down"].shape
                self.blob.add(f"{t}_dw_w", q.qw[f"{t}_down"], "<i1")
                m = (qp[f"{t}_preact"].scale * q.sw[f"{t}_down"]
                     / qp[f"{t}_out"].scale)
                self._put_requant(f"{t}_dw", m)
                skip = self._buf("bufSkip", CD * H2 * H2)
                self.calls.append(
                    f"    q_conv2d({pre}, {curC}, {curH}, {curH}, "
                    f"B_I8({t}_dw_w), {CD}, {KD}, {stride}, 0, "
                    f"{qp[f'{t}_preact'].zp}, B_I64({t}_dw_mult), "
                    f"B_I32({t}_dw_shift), (const int32_t*)0, "
                    f"{qp[f'{t}_out'].zp}, 0, {skip});")
                skip_zp = qp[f"{t}_out"].zp
                skip_m, skip_s = 1 << 30, 30        # already on out scale
            else:
                skip = cur
                skip_zp = qp[cur_tag].zp
                mm, ss = to_fixed_point(
                    np.array([qp[cur_tag].scale / qp[f"{t}_out"].scale]))
                skip_m, skip_s = int(mm[0]), int(ss[0])

            # residual add: both sides rescaled into the output scale
            out_buf = self._buf(f"bufOut{ping}", C2 * H2 * H2)
            self.calls.append(
                f"    q_add({main}, {qp[f'{t}_out'].zp}, {1 << 30}, 30, "
                f"{skip}, {skip_zp}, {skip_m}, {skip_s}, "
                f"{C2 * H2 * H2}, {qp[f'{t}_out'].zp}, {out_buf});")
            cur, curC, curH, cur_tag = out_buf, C2, H2, f"{t}_out"
            ping ^= 1

        # -- tail BN + ReLU --
        sc, sh = q.bn["bn2"]
        m = qp[cur_tag].scale * sc / qp["tail_act"].scale
        b = _bias_in_acc_domain(sh / qp["tail_act"].scale, m)
        self._put_requant("tail", m, b)
        tail = self._buf("bufTail", curC * curH * curH)
        self.calls.append(
            f"    q_affine({cur}, {curC}, {curH}, {curH}, {qp[cur_tag].zp}, "
            f"B_I64(tail_mult), B_I32(tail_shift), B_I32(tail_bias), "
            f"{qp['tail_act'].zp}, 1, {tail});")

        # -- global average pool --
        m = np.full(curC, qp["tail_act"].scale / qp["gap"].scale)
        self._put_requant("gap", m)
        gap = self._buf("bufGap", curC)
        self.calls.append(
            f"    q_global_avgpool({tail}, {curC}, {curH}, {curH}, "
            f"{qp['tail_act'].zp}, B_I64(gap_mult), B_I32(gap_shift), "
            f"{qp['gap'].zp}, {gap});")

        # -- FC -> float logits --
        NC = q.qw["fc"].shape[0]
        self.blob.add("fc_w", q.qw["fc"], "<i1")
        self.blob.add("fc_scale",
                      (qp["gap"].scale * q.sw["fc"]).astype(np.float32), "<f4")
        self.blob.add("fc_bias", q.fc_b.astype(np.float32), "<f4")
        self.calls.append(
            f"    q_gemm_f32({gap}, {curC}, {qp['gap'].zp}, B_I8(fc_w), {NC}, "
            f"B_F32(fc_scale), B_F32(fc_bias), logits);")

        blob_path = os.path.join(out_dir, "weights.bin")
        nbytes = self.blob.write(blob_path)
        src_path = os.path.join(out_dir, "resnet_int8.c")
        with open(src_path, "w") as f:
            f.write(self._source(NC))
        return {"blob": blob_path, "blob_bytes": nbytes, "source": src_path,
                "num_classes": NC, "input_hw": H,
                "input_qp": (qp["input"].scale, qp["input"].zp),
                "entries": len(self.blob.offsets)}

    # ── source assembly ────────────────────────────────────────────────────
    def _source(self, num_classes: int) -> str:
        offs = "\n".join(
            f"#define OFF_{n} {o}u   /* {c} elems */"
            for n, (o, c) in self.blob.offsets.items())
        bufs = "\n".join(f"static int8_t {n}[{sz}];"
                         for n, sz in sorted(self.bufs.items()))
        body = "\n".join(self.calls)
        return f"""{_COPYRIGHT}
{RUNTIME_C}

/* ===== weight blob (linked via `ld -r -b binary weights.bin`) ===== */
extern const unsigned char _binary_weights_bin_start[];
#define BLOB _binary_weights_bin_start
#define B_I8(n)  ((const int8_t  *)(BLOB + OFF_##n))
#define B_I32(n) ((const int32_t *)(BLOB + OFF_##n))
#define B_I64(n) ((const int64_t *)(BLOB + OFF_##n))
#define B_F32(n) ((const float   *)(BLOB + OFF_##n))

{offs}

/* ===== activation buffers (sized at emit time; .bss, not the heap) ===== */
{bufs}

#define NUM_CLASSES {num_classes}

/* Run the network. `input` is the pre-quantized int8 image, CHW,
 * {self.in_hw}x{self.in_hw}x3. `logits` receives NUM_CLASSES float32 scores. */
void run_resnet(const int8_t *input, float *logits) {{
    memcpy(bufA, input, 3 * {self.in_hw} * {self.in_hw});
{body}
}}
"""
