###############################################################################
# Copyright (C) 2025 Advanced Micro Devices, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
###############################################################################
"""CPU fallback for the non-conv2d ops of the TVM frontend launch plan.

The aiegraph *runtime* pipeline (``run_aie_pipeline`` -> real AIE) only supports
the conv2d family (``conv_bn``, ``conv_bn_relu``). The remaining plan ops
(``residual_add_relu``, ``avgpool_fc``) are emitted here as **bit-exact CPU C
generated by TVM** (``target="c"``) instead of being sent to the AIE backend.

Bit-exactness contract
----------------------
Each op is expressed as a TVM TE compute that is a transcription of the numpy
Q7 oracle in ``_compiler.py`` (``_cpu_add_relu`` / ``_cpu_avgpool_fc``):

* int8 inputs are widened with ``.astype("int16")`` and every reduction
  accumulates in int16, so the emitted C ``int16_t`` accumulator wraps exactly
  like the numpy ``int16`` oracle;
* the pool divide uses ``te.truncdiv`` (feature values are post-ReLU, i.e.
  ``>= 0``, so truncation == floor, matching the oracle's ``int(s)//spatial_sz``);
* saturation is ``te.max(te.min(x, hi), lo)``.

Because the same TE drives both ``target="c"`` (emitted artifact) and
``target="llvm"`` (used by the tests to run against the numpy oracle), the two
are numerically identical.

ABI note
--------
The installed TVM's ``target="c"`` codegen emits a *packed* function using the
TVM FFI ABI (entry ``__tvm_ffi_<func_name>``, ``DLTensor``/``TVMFFIAny`` args,
requires the ``tvm/ffi`` headers to link). Setting the PrimFunc
``global_symbol`` to ``func_name`` makes the requested name the public symbol.
Wrapping this into a plain ``void <func_name>(int8_t*, ...)`` host entry and
linking the CPU ops into a single AIE+CPU executable is deliberately out of
scope (no multi-layer host orchestrator exists yet); each launch is emitted as a
standalone C artifact, mirroring the standalone ``host.cc``/``kernel.cc`` the AIE
path emits per launch.

Portability
-----------
``_make_module`` probes the installed TVM so this module works across the
classic ``te.create_schedule`` + ``get_source`` API and the newer
``te.create_prim_func`` + ``inspect_source`` API.
"""

import os

from .model import LayerOp

# Ops the AIE runtime pipeline handles; everything else falls back to CPU C.
AIE_OPS = {"conv_bn", "conv_bn_relu"}
CPU_OPS = {"residual_add_relu", "avgpool_fc"}


def is_aie_op(op_name: str) -> bool:
    """True iff ``op_name`` is emitted to the AIE backend (conv2d family)."""
    return op_name in AIE_OPS


def is_cpu_op(op_name: str) -> bool:
    """True iff ``op_name`` is emitted as TVM CPU C."""
    return op_name in CPU_OPS


def available() -> bool:
    """True iff TVM is importable and its TE API is usable for codegen.

    Independent of ``relay_import.tvm_available`` (which checks ``tvm.relay``):
    the CPU codegen only needs the TE + build path, which exists even in the
    relay-less TVM builds.
    """
    try:
        import tvm  # noqa: F401
        from tvm import te  # noqa: F401
        return hasattr(te, "compute") and hasattr(te, "create_prim_func") \
            or hasattr(te, "create_schedule")
    except Exception:
        return False


# ═══════════════════════════════════════════════════════════════════════════
#  TE builders — one per CPU op (transcriptions of the numpy Q7 oracle)
# ═══════════════════════════════════════════════════════════════════════════

def _clamp(te, x, lo: int, hi: int):
    """Saturate int16 expr ``x`` to ``[lo, hi]`` (== numpy max/min clamp)."""
    return te.max(te.min(x, te.const(hi, "int16")), te.const(lo, "int16"))


def _residual_te(n: int):
    """``out[i] = int8(clamp(int16(main[i]) + int16(skip[i]), 0, 127))``.

    Returns the tensor list ``[main, skip, out]`` (inputs first, output last).
    """
    from tvm import te
    main = te.placeholder((n,), dtype="int8", name="main_in")
    skip = te.placeholder((n,), dtype="int8", name="skip_in")
    out = te.compute(
        (n,),
        lambda i: _clamp(te, main[i].astype("int16") + skip[i].astype("int16"),
                         0, 127).astype("int8"),
        name="out")
    return [main, skip, out]


def _avgpool_fc_te(spatial_h: int, spatial_w: int,
                   channels: int, num_classes: int):
    """Global average pool + FC, headerless weights/bias.

    ``pooled[c] = int8(truncdiv(Σ_spatial int16(feat), spatial_sz))``;
    ``logits[j] = int8(clamp(Σ_c int16(pooled[c])*int16(wts[c*NC+j]) + bias[j],
    -128, 127))``. Returns ``[feat, wts, bias, logits]``.
    """
    from tvm import te
    ssz = spatial_h * spatial_w
    feat = te.placeholder((channels * ssz,), dtype="int8", name="feat")
    wts = te.placeholder((channels * num_classes,), dtype="int8", name="wts")
    bias = te.placeholder((num_classes,), dtype="int8", name="bias")

    r = te.reduce_axis((0, ssz), "r")
    psum = te.compute(
        (channels,),
        lambda c: te.sum(feat[c * ssz + r].astype("int16"), axis=r),
        name="psum")
    pooled = te.compute(
        (channels,),
        lambda c: te.truncdiv(psum[c], te.const(ssz, "int16")).astype("int8"),
        name="pooled")

    k = te.reduce_axis((0, channels), "k")
    acc = te.compute(
        (num_classes,),
        lambda j: te.sum(pooled[k].astype("int16")
                         * wts[k * num_classes + j].astype("int16"), axis=k),
        name="acc")
    logits = te.compute(
        (num_classes,),
        lambda j: _clamp(te, acc[j] + bias[j].astype("int16"),
                         -128, 127).astype("int8"),
        name="logits")
    return [feat, wts, bias, logits]


def op_tensors(op: LayerOp):
    """Return the TE tensor list ``[ins..., out]`` for a CPU ``op``.

    Raises ``ValueError`` for AIE ops and unknown ops (extension point: add a
    new TE builder + CPU_OPS entry to support another op on the CPU path).
    """
    if op.op == "residual_add_relu":
        return _residual_te(op.length)
    if op.op == "avgpool_fc":
        return _avgpool_fc_te(op.spatial_h, op.spatial_w,
                              op.channels, op.num_classes)
    if is_aie_op(op.op):
        raise ValueError(f"{op.op!r} is an AIE op, not a CPU-codegen op")
    raise ValueError(f"unknown op {op.op!r} (no CPU TE builder)")


# ═══════════════════════════════════════════════════════════════════════════
#  Build / emit
# ═══════════════════════════════════════════════════════════════════════════

def _make_module(tensors, func_name: str, target: str):
    """Build ``tensors`` into a TVM module for ``target`` (portable across APIs).

    New TVM: ``te.create_prim_func`` + ``with_attr("global_symbol", ...)``.
    Classic TVM: ``te.create_schedule`` + ``build(..., name=func_name)``.
    """
    import tvm
    from tvm import te
    if hasattr(te, "create_prim_func"):
        pf = te.create_prim_func(list(tensors))
        try:
            pf = pf.with_attr("global_symbol", func_name)
        except Exception:
            pass
        return tvm.build(pf, target=target)
    sched = te.create_schedule(tensors[-1].op)
    return tvm.build(sched, list(tensors), target=target, name=func_name)


def _module_source(mod) -> str:
    """Return the C source of a ``target="c"`` module (portable across APIs)."""
    if hasattr(mod, "inspect_source"):
        return mod.inspect_source()
    return mod.get_source()


def build_llvm(op: LayerOp, func_name: str = "cpu"):
    """Build a runnable ``target="llvm"`` module for ``op`` (used by tests).

    Returns ``(module, tensors)``; call ``module(*ndarrays)`` in tensor order.
    """
    tensors = op_tensors(op)
    return _make_module(tensors, func_name, "llvm"), tensors


def cpu_c_source(op: LayerOp, func_name: str) -> str:
    """Return the TVM ``target="c"`` source for a CPU ``op`` (entry ``func_name``)."""
    tensors = op_tensors(op)
    mod = _make_module(tensors, func_name, "c")
    return _module_source(mod)


def emit_cpu_launch(op: LayerOp, out_dir: str, func_name: str) -> bool:
    """Write ``<func_name>.c`` (TVM CPU C) for ``op`` into ``out_dir``.

    Returns ``True`` on success. Raises ``ValueError`` for a non-CPU op.
    """
    os.makedirs(out_dir, exist_ok=True)
    src = cpu_c_source(op, func_name)
    with open(os.path.join(out_dir, f"{func_name}.c"), "w") as f:
        f.write(src)
    return True


# ═══════════════════════════════════════════════════════════════════════════
#  Plain-C emit — self-contained, TVM-FFI-free, aarch64-portable entries
# ═══════════════════════════════════════════════════════════════════════════
#
# Unlike ``cpu_c_source`` (TVM ``target="c"``, a packed ``__tvm_ffi_*`` function
# needing the TVM FFI ABI + headers to link), these emit a plain
# ``void <func_name>(...)`` with only ``<stdint.h>``, so the CPU ops can be
# linked into an on-board executable with no TVM FFI at runtime. Each function
# below is a line-by-line transcription of the numpy Q7 oracle in
# ``_compiler.py`` (``_cpu_add_relu`` / ``_cpu_avgpool_fc``): every accumulate is
# ``int16_t`` (so C wrap == numpy ``int16`` wrap), clamps use the same bounds,
# and the pool divide is C integer ``/`` (features are post-ReLU ``>= 0`` so
# truncation-toward-zero == the oracle's ``int(s)//spatial_sz`` floor).

def _plain_c_residual(func_name: str) -> str:
    """Plain-C ``residual_add_relu`` (length-parametric).

    Emits ``void <fn>(const int8_t* a, const int8_t* b, int8_t* out, int n)``:
    per element ``s = int16(a[i]) + int16(b[i])``, clamp to ``[0, 127]`` (ReLU +
    saturate), store int8 — byte-identical to ``_cpu_add_relu``.
    """
    return (
        "#include <stdint.h>\n\n"
        f"void {func_name}(const int8_t* a, const int8_t* b, int8_t* out, int n) {{\n"
        "  for (int i = 0; i < n; ++i) {\n"
        "    int16_t s = (int16_t)a[i] + (int16_t)b[i];\n"
        "    if (s < 0) s = 0;\n"
        "    if (s > 127) s = 127;\n"
        "    out[i] = (int8_t)s;\n"
        "  }\n"
        "}\n")


def _plain_c_avgpool_fc(func_name: str, spatial_h: int, spatial_w: int,
                        channels: int, num_classes: int) -> str:
    """Plain-C global-avgpool + FC (fixed geometry, headerless weights|bias).

    Emits ``void <fn>(const int8_t* feat, const int8_t* wts,
    const int8_t* bias, int8_t* out)`` with the geometry baked in. Mirrors
    ``_cpu_avgpool_fc``: ``pooled[c] = int8(int16_sum(feat) / spatial_sz)``
    (integer trunc; feat post-ReLU ``>= 0`` so ``==`` floor), then
    ``acc = int16_sum(pooled*wts) + bias``, clamp ``[-128, 127]``, store int8.
    """
    ssz = spatial_h * spatial_w
    return (
        "#include <stdint.h>\n\n"
        f"void {func_name}(const int8_t* feat, const int8_t* wts,\n"
        "                 const int8_t* bias, int8_t* out) {\n"
        f"  const int spatial_sz = {ssz};\n"
        f"  const int channels = {channels};\n"
        f"  const int num_classes = {num_classes};\n"
        f"  int8_t pooled[{channels}];\n"
        "  for (int c = 0; c < channels; ++c) {\n"
        "    int16_t s = 0;\n"
        "    for (int idx = 0; idx < spatial_sz; ++idx)\n"
        "      s += (int16_t)feat[c * spatial_sz + idx];\n"
        "    pooled[c] = (int8_t)((int)s / spatial_sz);\n"
        "  }\n"
        "  for (int j = 0; j < num_classes; ++j) {\n"
        "    int16_t acc = 0;\n"
        "    for (int i = 0; i < channels; ++i)\n"
        "      acc += (int16_t)pooled[i] * (int16_t)wts[i * num_classes + j];\n"
        "    acc += (int16_t)bias[j];\n"
        "    if (acc < -128) acc = -128;\n"
        "    if (acc > 127) acc = 127;\n"
        "    out[j] = (int8_t)acc;\n"
        "  }\n"
        "}\n")


def plain_c_source(op: LayerOp, func_name: str) -> str:
    """Return self-contained plain-C source for a CPU ``op`` (entry ``func_name``).

    Unlike ``cpu_c_source`` (TVM FFI packed function), the returned C is a plain
    ``void <func_name>(...)`` needing only ``<stdint.h>`` and is bit-exact with
    the numpy Q7 oracle. Raises ``ValueError`` for AIE ops / unknown ops.
    """
    if op.op == "residual_add_relu":
        return _plain_c_residual(func_name)
    if op.op == "avgpool_fc":
        return _plain_c_avgpool_fc(func_name, op.spatial_h, op.spatial_w,
                                   op.channels, op.num_classes)
    if is_aie_op(op.op):
        raise ValueError(f"{op.op!r} is an AIE op, not a CPU-codegen op")
    raise ValueError(f"unknown op {op.op!r} (no plain-C emitter)")


def emit_cpu_launch_plain(op: LayerOp, out_dir: str, func_name: str) -> bool:
    """Write self-contained plain-C ``<func_name>.c`` for ``op`` into ``out_dir``.

    Plain-C sibling of ``emit_cpu_launch`` (no TVM FFI). Returns ``True`` on
    success. Raises ``ValueError`` for a non-CPU op.
    """
    os.makedirs(out_dir, exist_ok=True)
    src = plain_c_source(op, func_name)
    with open(os.path.join(out_dir, f"{func_name}.c"), "w") as f:
        f.write(src)
    return True
