#!/usr/bin/env python3
###############################################################################
# Copyright (C) 2026 Advanced Micro Devices, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
###############################################################################
"""Bootstrap aiedbg for the live debug UI.

On first use (or with --update), clones the aiedbg repo under thirdparty/aiedbg
and installs it with ``pip install --user``. Writes .aiehlc/aiedbg_env.sh so
shell sessions can prepend ~/.local/bin to PATH.

Board JTAG setup (``aiedbg-setup --board …`` / ``AIEDBG_TARGET``) is separate
and is not run automatically — see script/test/envlocal.sh.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(_THIS_DIR)))

DEFAULT_REPO = os.environ.get(
    "AIEHLC_AIEDBG_REPO",
    "https://github.com/AMD-AECG-SSWSIP/aiedbg.git",
)


def _local_bin():
    return os.path.expanduser("~/.local/bin")


def _env_file(repo_root):
    return os.path.join(repo_root, ".aiehlc", "aiedbg_env.sh")


def _src_dir(repo_root):
    override = os.environ.get("AIEHLC_AIEDBG_SRC", "").strip()
    if override:
        return os.path.abspath(override)
    return os.path.join(repo_root, "thirdparty", "aiedbg")


def prepend_local_bin():
    """Prepend ~/.local/bin to PATH for the current process."""
    lb = _local_bin()
    path = os.environ.get("PATH", "")
    parts = path.split(os.pathsep) if path else []
    if lb not in parts:
        os.environ["PATH"] = lb + (os.pathsep + path if path else "")


def write_path_env(repo_root):
    """Write a small shell snippet for future bash sessions."""
    lb = _local_bin()
    dest = _env_file(repo_root)
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    body = (
        "# Auto-generated by ensure_aiedbg.py — prepend pip --user scripts.\n"
        f'case ":$PATH:" in *":{lb}:"*) ;; *) export PATH="{lb}:$PATH" ;; esac\n'
    )
    with open(dest, "w") as f:
        f.write(body)
    return dest


def _run(cmd, cwd=None, check=True):
    return subprocess.run(cmd, cwd=cwd, check=check, text=True,
                          capture_output=True)


def _git_clone(repo_url, dest):
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    r = _run(["git", "clone", "--depth", "1", repo_url, dest], check=False)
    if r.returncode != 0:
        err = (r.stderr or r.stdout or "git clone failed").strip()
        return False, err
    return True, dest


def _git_pull(dest):
    r = _run(["git", "pull", "--ff-only"], cwd=dest, check=False)
    if r.returncode != 0:
        err = (r.stderr or r.stdout or "git pull failed").strip()
        return False, err
    return True, (r.stdout or "").strip() or "ok"


def _pip_install(src_dir, upgrade=False):
    cmd = [sys.executable, "-m", "pip", "install", "--user"]
    if upgrade:
        cmd.append("--upgrade")
    cmd.append(src_dir)
    r = _run(cmd, check=False)
    if r.returncode != 0:
        err = (r.stderr or r.stdout or "pip install failed").strip()
        return False, err
    return True, (r.stdout or "").strip() or "ok"


def _aiedbg_path():
    return shutil.which("aiedbg")


def ensure_aiedbg(repo_root=None, update=False, force=False, quiet=False):
    """Install or refresh aiedbg. Returns a status dict with key ``ok``."""
    repo_root = os.path.abspath(repo_root or _REPO_ROOT)
    src = _src_dir(repo_root)
    prepend_local_bin()

    existing = _aiedbg_path()
    if existing and not update and not force:
        env_path = write_path_env(repo_root)
        return {
            "ok": True,
            "action": "present",
            "path": existing,
            "src": src if os.path.isdir(src) else None,
            "env_file": env_path,
        }

    if not os.path.isdir(os.path.join(src, ".git")):
        if not quiet:
            print(f"ensure_aiedbg: cloning {DEFAULT_REPO} -> {src}", file=sys.stderr)
        ok, detail = _git_clone(DEFAULT_REPO, src)
        if not ok:
            return {"ok": False, "action": "clone_failed", "error": detail, "src": src}
        action = "cloned"
    else:
        action = "existing_src"
        if update:
            if not quiet:
                print(f"ensure_aiedbg: updating {src}", file=sys.stderr)
            ok, detail = _git_pull(src)
            if not ok:
                return {"ok": False, "action": "pull_failed", "error": detail, "src": src}
            action = "updated"

    if not quiet:
        print(f"ensure_aiedbg: pip install --user {src}", file=sys.stderr)
    ok, detail = _pip_install(src, upgrade=update or force)
    if not ok:
        return {"ok": False, "action": "pip_failed", "error": detail, "src": src}

    prepend_local_bin()
    path = _aiedbg_path()
    if not path:
        return {
            "ok": False,
            "action": "not_on_path",
            "error": f"pip succeeded but aiedbg not found; add {_local_bin()} to PATH",
            "src": src,
        }

    env_path = write_path_env(repo_root)
    return {
        "ok": True,
        "action": action,
        "path": path,
        "src": src,
        "env_file": env_path,
        "pip": detail,
    }


def _print_result(result):
    if result.get("ok"):
        print(f"aiedbg: {result.get('action')} -> {result.get('path')}")
        if result.get("env_file"):
            print(f"  PATH env: source {result['env_file']}")
        if result.get("src"):
            print(f"  source:   {result['src']}")
    else:
        print(f"aiedbg bootstrap failed ({result.get('action')}): "
              f"{result.get('error', 'unknown')}", file=sys.stderr)
        return 1
    return 0


def main():
    ap = argparse.ArgumentParser(
        description="Clone/install aiedbg for the live debug UI")
    ap.add_argument("--repo-root", default=_REPO_ROOT,
                    help="aiehlc repo root (default: auto-detect)")
    ap.add_argument("--update", action="store_true",
                    help="git pull + pip install --upgrade")
    ap.add_argument("--force", action="store_true",
                    help="reinstall even when aiedbg is already on PATH")
    ap.add_argument("-q", "--quiet", action="store_true",
                    help="suppress progress messages")
    args = ap.parse_args()
    result = ensure_aiedbg(args.repo_root, update=args.update,
                           force=args.force, quiet=args.quiet)
    return _print_result(result)


if __name__ == "__main__":
    sys.exit(main())
