#!/usr/bin/env python3
# Copyright (C) 2025 Advanced Micro Devices, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""Convert routingresourcemap.json into a self-contained C header.

The generated header (aie_resource_map.h) declares a flat table of routing
resource entries -- for each connection, which tile / stream port / pkt id /
pkt mask it uses -- plus a dependency-free __Runtime_print_resource_map()
that prints every entry via plain printf.

Usage:
    resource_json_to_header.py <routingresourcemap.json> --out <aie_resource_map.h>
"""

import argparse
import json
import sys


def _port(obj, key):
    """Return (dir, idx) for a nested port object, or ("NONE", -1)."""
    p = obj.get(key) if obj else None
    if not isinstance(p, dict):
        return ("NONE", -1)
    return (str(p.get("dir", "NONE")), int(p.get("idx", -1)))


def _slot(obj, key):
    """Return (dir, idx, pktid, mask) for a recv_slave / local_dma object."""
    p = obj.get(key) if obj else None
    if not isinstance(p, dict):
        return ("NONE", -1, -1, 0)
    return (
        str(p.get("dir", "NONE")),
        int(p.get("idx", -1)),
        int(p.get("pktid", -1)),
        int(p.get("mask", 0)),
    )


def build_entries(model):
    """Flatten the JSON connections into a stable list of table rows (dicts)."""
    rows = []
    for conn in model.get("connections", []):
        kind = str(conn.get("kind", "unknown"))
        tile = conn.get("tile") or {}
        col = int(tile.get("col", -1))
        row = int(tile.get("row", -1))
        tkind = str(tile.get("kind", "unknown"))

        recv_dir, recv_idx, recv_pktid, recv_mask = _slot(conn, "recv_slave")
        dma_dir, dma_idx, dma_pktid, dma_mask = _slot(conn, "local_dma")
        fwd_dir, fwd_idx = _port(conn, "forward_master")
        preserve = 1 if conn.get("preserve_header") else 0

        rows.append(
            {
                "kind": kind,
                "col": col,
                "row": row,
                "tkind": tkind,
                "recv_dir": recv_dir,
                "recv_idx": recv_idx,
                "recv_pktid": recv_pktid,
                "recv_mask": recv_mask,
                "dma_dir": dma_dir,
                "dma_idx": dma_idx,
                "dma_pktid": dma_pktid,
                "dma_mask": dma_mask,
                "fwd_dir": fwd_dir,
                "fwd_idx": fwd_idx,
                "preserve": preserve,
            }
        )

    # Deterministic ordering so rebuilds are diff-clean.
    rows.sort(
        key=lambda e: (
            e["col"],
            e["row"],
            e["kind"],
            e["recv_dir"],
            e["recv_idx"],
            e["recv_pktid"],
            e["dma_dir"],
            e["dma_idx"],
            e["dma_pktid"],
            e["fwd_dir"],
            e["fwd_idx"],
        )
    )
    return rows


def _cstr(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_header(model, rows):
    start_col = model.get("partition_start_col", model.get("startcol", -1))
    aie_gen = model.get("aie_gen", "")

    out = []
    w = out.append

    w("/* Auto-generated by resource_json_to_header.py -- do not edit. */")
    w("#ifndef AIE_RESOURCE_MAP_H")
    w("#define AIE_RESOURCE_MAP_H")
    w("")
    w("#include <stdio.h>")
    w("")
    w("struct AieResourceEntry {")
    w("    const char *kind;   /* connection kind (packet_connect, circuit_connect, ...) */")
    w("    int col;")
    w("    int row;")
    w("    const char *tile_kind;")
    w("    /* receive slave slot */")
    w("    const char *recv_dir;")
    w("    int recv_idx;")
    w("    int recv_pktid;")
    w("    int recv_mask;")
    w("    /* local DMA slave slot */")
    w("    const char *dma_dir;")
    w("    int dma_idx;")
    w("    int dma_pktid;")
    w("    int dma_mask;")
    w("    /* forward master port */")
    w("    const char *fwd_dir;")
    w("    int fwd_idx;")
    w("    int preserve_header;")
    w("};")
    w("")
    w("static const struct AieResourceEntry __aie_resource_map[] = {")
    for e in rows:
        w(
            "    { %s, %d, %d, %s, %s, %d, %d, %d, %s, %d, %d, %d, %s, %d, %d },"
            % (
                _cstr(e["kind"]),
                e["col"],
                e["row"],
                _cstr(e["tkind"]),
                _cstr(e["recv_dir"]),
                e["recv_idx"],
                e["recv_pktid"],
                e["recv_mask"],
                _cstr(e["dma_dir"]),
                e["dma_idx"],
                e["dma_pktid"],
                e["dma_mask"],
                _cstr(e["fwd_dir"]),
                e["fwd_idx"],
                e["preserve"],
            )
        )
    w("};")
    w("")
    w("static const int __aie_resource_map_count =")
    w("    (int)(sizeof(__aie_resource_map) / sizeof(__aie_resource_map[0]));")
    w("")
    w("static inline void __Runtime_print_resource_map(void) {")
    w('    printf("[aie_resource_map] partition_start_col=%d aie_gen=%s entries=%d\\n",')
    w("           %d, %s, __aie_resource_map_count);" % (int(start_col), _cstr(str(aie_gen))))
    w("    for (int i = 0; i < __aie_resource_map_count; ++i) {")
    w("        const struct AieResourceEntry *e = &__aie_resource_map[i];")
    w('        printf("[aie_resource_map] #%d %s tile(%d,%d,%s)"')
    w('               " recv[%s:%d pktid=%d mask=0x%x]"')
    w('               " dma[%s:%d pktid=%d mask=0x%x]"')
    w('               " fwd[%s:%d] preserve=%d\\n",')
    w("               i, e->kind, e->col, e->row, e->tile_kind,")
    w("               e->recv_dir, e->recv_idx, e->recv_pktid, e->recv_mask,")
    w("               e->dma_dir, e->dma_idx, e->dma_pktid, e->dma_mask,")
    w("               e->fwd_dir, e->fwd_idx, e->preserve_header);")
    w("    }")
    w("}")
    w("")
    w("#endif /* AIE_RESOURCE_MAP_H */")
    w("")
    return "\n".join(out)


def main(argv=None):
    ap = argparse.ArgumentParser(description="Convert routingresourcemap.json to a C header.")
    ap.add_argument("json", help="path to routingresourcemap.json")
    ap.add_argument("--out", required=True, help="output header path (aie_resource_map.h)")
    args = ap.parse_args(argv)

    try:
        with open(args.json, "r") as f:
            model = json.load(f)
    except (OSError, ValueError) as exc:
        sys.stderr.write("resource_json_to_header: cannot read %s: %s\n" % (args.json, exc))
        return 1

    rows = build_entries(model)
    text = render_header(model, rows)

    try:
        with open(args.out, "w") as f:
            f.write(text)
    except OSError as exc:
        sys.stderr.write("resource_json_to_header: cannot write %s: %s\n" % (args.out, exc))
        return 1

    sys.stderr.write(
        "resource_json_to_header: wrote %s (%d entries)\n" % (args.out, len(rows))
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
