###############################################################################
# Copyright (C) 2026 Advanced Micro Devices, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
###############################################################################
"""Step 4 of the BYOC flow: what a partitioned-out AIE subgraph compiles into.

After ``PartitionGraph``, TVM calls ``relay.ext.aie`` for every function with
``Compiler="aie"``; this module is that callback. It returns a C source module
(``CSourceModuleCreate``), so the wrapper lands in ``resnet18.c`` next to TVM's
own kernels and is compiled and linked by ``arm_build.py`` like everything else.

Dispatch is on the COMPOSITE NAME
---------------------------------
``_EMITTERS`` maps ``Composite`` attribute -> emitter. A second AIE kernel is
then a ``aie_patterns.pattern_table`` entry plus an entry in that dict: nothing
else in the flow branches on which op this is. The composite also carries
``aie.layer_id`` from step 2, so an error here can name the ``--aie-layers``
argument that produced it instead of an anonymous ``tvmgen_default_aie_main_0``.

What the wrapper does
---------------------
The subgraph is the FUSED stem op (``aie_patterns``): uint8 NCHW
``[1,3,230,230]`` (already padded by TVM with the input zero-point) ->
uint8 NCHW ``[1,64,112,112]``. The AIE kernel behind
``conv2d_stem_prepadded()`` (``libconv2dstem.a``) computes the same op as
int8 x int8 on HWC data with a per-channel ``{bias, zp, mult, shift}``
epilogue. The wrapper bridges the two, exactly:

* **uint8 -> int8.** ``x_s8 = x_u8 - 128``; since
  ``sum(x_u8 * w) = sum(x_s8 * w) + 128 * sum(w)``, ``128 * sum(w[f])`` is folded
  into the bias at codegen time. The border pixels (value = zero-point) go
  through the same shift, so the padding stays exact too.
* **Epilogue constants.** ``bias = C2 + C3 - C4 + 128*sum(w)``, ``zp = 0``,
  ``mult = C5``, ``shift = C7`` -- the canonicalized
  ``add/bias_add/subtract/fixed_point_multiply_per_axis`` chain, which is
  ``(acc*mult + 2^(rs+30)) >> (rs+31)`` in TVM (``QMultiplyShift``) and on the
  core alike. ``aie_patterns.check_fused_qconv`` already rejected anything that
  form cannot express (weight zero-point, left shift, other clip).
* **Layouts.** NCHW -> HWC on the way in, HWC -> NCHW on the way out.

Weights and qparams are emitted as function-scope ``static const`` arrays
inside the wrapper: they are Constants of the composite, so nothing has to
"publish" them at run time, and ``split_layers`` (which carries functions, not
file-scope data) still gets a self-contained layer file.
"""

from __future__ import annotations

import numpy as np
import tvm
from tvm import relay

from frontend.tvmrelay.byoc.aie_patterns import (AIE_PATTERN_NAME, ATTR_LAYER_ID,
                                                 STEM_GEOMETRY, composite_name,
                                                 extract_fused)
# The symbol arm_build keys the libconv2dstem.a link off -- one definition.
from frontend.tvmrelay.arm_build import AIE_ENTRY

__all__ = ["aie_compiler", "register", "emit_c_for_function", "emit_stem",
           "fold_qparams", "AIE_ENTRY"]

#: Keep in sync with aie_annotate.AIE_COMPILER_NAME.
_COMPILER = "aie"


_C_PRELUDE = """\
/* Generated by src/frontend/tvmrelay/byoc/aie_codegen.py -- do not edit. */
#ifndef AIE_BYOC_PRELUDE
#define AIE_BYOC_PRELUDE
#include <stdint.h>

#ifndef TVM_DLL
#define TVM_DLL
#endif

#ifdef __cplusplus
extern "C" {
#endif
/* libconv2dstem.a (src/aietensorop/conv2dstem/conv2dstem.h). Declared rather
 * than #included so resnet18.c needs no -I. `qp` is the header's
 * conv2dstem_qparam[OC] -- four int32 {bias, zero_point, multiplier, shift}
 * per channel -- passed as a flat int32 array of the same layout: a typedef
 * here would land mid-file in resnet18.c, where split_layers cannot carry it. */
int conv2d_stem_prepadded(const int8_t *ifm_pad, const int8_t *wts,
                          const void *qp, uint8_t *ofm);
#ifdef __cplusplus
}
#endif
#endif /* AIE_BYOC_PRELUDE */
"""

_FUNC_TMPL = """
/* Subgraph {name}: fused stem qconv on the AIE mesh (libconv2dstem.a)
 *   input  : {in_desc}
 *   output : {out_desc}
 */
#ifdef __cplusplus
extern "C"
#endif
TVM_DLL int {name}_wrapper_(uint8_t* in0, uint8_t* out0) {{
    /* Function-scope, so split_layers' per-layer file stays self-contained. */
    static const int8_t wts[{n_w}] = {{  /* [OC][KH][KW][IC] */
{wts}
    }};
    static const int32_t qp[{oc} * 4] = {{  /* per channel: bias, zp, mult, shift */
{qp}
    }};
    static int8_t ifm[{hp} * {wp} * {ic}];
    static uint8_t ofm[{oh} * {ow} * {oc}];
    /* uint8 NCHW, zero-point padded by TVM  ->  int8 HWC, x - 128 */
    for (int c = 0; c < {ic}; ++c)
        for (int h = 0; h < {hp}; ++h)
            for (int w = 0; w < {wp}; ++w)
                ifm[(h * {wp} + w) * {ic} + c] =
                    (int8_t)((int)in0[(c * {hp} + h) * {wp} + w] - 128);

    int rc = {entry}(ifm, wts, qp, ofm);
    if (rc != 0) return rc;

    /* HWC -> NCHW */
    for (int f = 0; f < {oc}; ++f)
        for (int h = 0; h < {oh}; ++h)
            for (int w = 0; w < {ow}; ++w)
                out0[(f * {oh} + h) * {ow} + w] = ofm[(h * {ow} + w) * {oc} + f];
    return 0;
}}

#ifdef __cplusplus
extern "C"
#endif
TVM_DLL int {name}(void* args, int* type_codes, int num_args,
                   void* out_value, int* out_type_code) {{
    /* TVM C packed ABI: args is a TVMValue[] of DLTensor*; shapes are baked in. */
    void** handles = (void**)args;
    (void)type_codes; (void)num_args; (void)out_value; (void)out_type_code;
    uint8_t* in0 = (uint8_t*)(((void**)handles[0])[0]);
    uint8_t* out0 = (uint8_t*)(((void**)handles[1])[0]);
    return {name}_wrapper_(in0, out0);
}}
"""


def _find_composite(func):
    """The AIE composite inside a partitioned function, as ``(composite, name)``.

    Matches by MEMBERSHIP in ``_EMITTERS`` rather than against one constant, so a
    second kernel is a ``pattern_table`` entry plus an emitter and nothing here.
    """
    found = []

    def visit(e):
        name = composite_name(e)
        if name in _EMITTERS:
            found.append((e, name))

    relay.analysis.post_order_visit(func.body, visit)
    if len(found) != 1:
        known = ", ".join(sorted(_EMITTERS)) or "(none registered)"
        raise ValueError(f"expected exactly one AIE composite ({known}), "
                         f"found {len(found)}")
    return found[0]


def _layer_label(comp, comp_name: str) -> str:
    """``aie.qconv_fused (layer 06)`` -- with the number if step 2 attached one.

    An error here is otherwise impossible to tie back to a ``--aie-layers``
    argument, which is the only handle the user has.
    """
    if comp.attrs and ATTR_LAYER_ID in comp.attrs:
        return f"{comp_name} (layer {int(comp.attrs[ATTR_LAYER_ID]):02d})"
    return comp_name


def fold_qparams(f) -> np.ndarray:
    """Per-channel ``[bias, zero_point, multiplier, shift]`` (int64 [OC,4]) for the kernel.

    ``bias`` absorbs C2 + C3 - C4 and the ``+128*sum(w)`` that undoes the
    uint8 -> int8 input shift. Range-checked into int32 -- an overflow here
    would silently wrap on the core.
    """
    wsum = f.weight.astype(np.int64).reshape(f.weight.shape[0], -1).sum(axis=1)
    bias = f.add_c + f.bias - f.sub_c + 128 * wsum
    qp = np.stack([bias, np.zeros_like(bias), f.mult, f.rshift], axis=1)
    if (qp < -(1 << 31)).any() or (qp >= (1 << 31)).any():
        raise ValueError("folded qparams overflow int32")
    return qp


def _c_rows(values, per_line: int, indent: str = "    ") -> str:
    vals = [str(int(v)) for v in values]
    return ",\n".join(indent + ", ".join(vals[i:i + per_line])
                      for i in range(0, len(vals), per_line))


def emit_c_for_function(func, name: str) -> str:
    """C source for one partitioned function, dispatched on the composite name."""
    comp, comp_name = _find_composite(func)
    return _EMITTERS[comp_name](func, comp, name, _layer_label(comp, comp_name))


def emit_stem(func, comp, name: str, label: str) -> str:
    """``aie.qconv_fused`` -> the ``conv2d_stem_prepadded`` wrapper.

    Fail-closed on the signature: ``kernel_can_run`` already vetted this during
    selection, but it may have run before ``InferType`` reached the composite's
    params, so the authoritative dtype/shape check is here, on the partitioned
    function, where types always exist.
    """
    f = extract_fused(comp.body)
    in_t, out_t = func.params[0].checked_type, func.ret_type
    in_shape = [int(d) for d in in_t.shape]
    out_shape = [int(d) for d in out_t.shape]
    oc, ic, kh, kw = (int(d) for d in f.weight.shape)
    if (str(in_t.dtype), str(out_t.dtype)) != ("uint8", "uint8") \
            or in_shape[1:] != [ic, *STEM_GEOMETRY["in_hw"]] or out_shape[1] != oc:
        raise ValueError(f"{name}: {label}: {in_shape} {in_t.dtype} -> {out_shape} "
                         f"{out_t.dtype} is not the fused stem signature")

    qp = fold_qparams(f)
    wts_ohwi = f.weight.transpose(0, 2, 3, 1).reshape(-1)
    return _FUNC_TMPL.format(
        name=name, entry=AIE_ENTRY,
        in_desc=f"{in_shape} {in_t.dtype}", out_desc=f"{out_shape} {out_t.dtype}",
        n_w=wts_ohwi.size, wts=_c_rows(wts_ohwi, 24, indent="        "),
        qp=",\n".join(f"        {b}, {z}, {m}, {s}" for b, z, m, s in qp),
        ic=ic, hp=in_shape[2], wp=in_shape[3],
        oc=oc, oh=out_shape[2], ow=out_shape[3])


#: Composite name -> emitter ``(func, composite, symbol, label) -> C source``.
#: The one dispatch point in step 4: ``_find_composite`` looks up by membership
#: here, so adding a kernel means a ``pattern_table`` entry and an entry here.
#: Defined after the emitters so the functions exist.
_EMITTERS = {AIE_PATTERN_NAME: emit_stem}


@tvm._ffi.register_func("relay.ext.aie")
def aie_compiler(ref):
    """TVM calls this for every function with ``Compiler="aie"``. Returns a runtime.Module.

    ``ref`` carries a ``global_symbol`` attribute -- the name the host-side call
    site links against, so it is used verbatim as the C function name.
    """
    if not isinstance(ref, relay.Function):
        raise ValueError(f"relay.ext.aie expected a Function, got {type(ref)}")
    name = str(ref.attrs["global_symbol"])
    code = _C_PRELUDE + emit_c_for_function(ref, name)
    csource = tvm.get_global_func("runtime.CSourceModuleCreate")
    return csource(code, "c", [name], [])


def register() -> bool:
    """Confirm ``relay.ext.aie`` is registered (importing this module registers it)."""
    return bool(tvm.get_global_func("relay.ext.aie", allow_missing=True))
