###############################################################################
# Copyright (C) 2026 Advanced Micro Devices, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
###############################################################################
"""Codegen + runtime: what the partitioned-out AIE subgraph compiles into.

The third and fourth of the four BYOC files. After ``PartitionGraph``, TVM calls
``relay.ext.aie`` for every function with ``Compiler="aie"``; this module is that
callback.

Use CSourceModule, not a custom runtime.Module
----------------------------------------------
BYOC allows returning any ``runtime.Module``. Here we return the C source module
produced by ``CSourceModuleCreate``, because the whole pipeline is already on
``target="c"``: the generated C ends up in ``resnet18.c`` together with the
kernels TVM emits itself, compiled by the same ``arm_build.py`` Makefile and
linked into the same ``main.elf``. Switching to a custom runtime would mean
handling serialization, symbol export, and cross-compilation ourselves, and
``arm_build.py`` already does all of that.

What is emitted is a **wrapper**, not the kernel itself
-------------------------------------------------------
The function signature produced by ``_emit_c`` conforms to TVM's C packed ABI,
and the function body is currently a **placeholder**: it copies the input to the
output as int8 with a clamp, it is not a real convolution. That is deliberate --
it lets the whole chain "partition -> codegen -> compile -> link -> run" close
first, so the boundaries, the ABI, and the buffer sizes can all be verified; the
real AIE kernel is generated by ``run_aie_pipeline``, and plugging it in only
requires replacing the function body, with the signature and the call sites
unchanged.

**The placeholder body will not compute correct results.** It compiles, links,
and runs to completion, but the classification result is wrong. That is why the
default in ``aie_byoc.py`` is ``n=0`` (offload nothing); offloading must be
requested explicitly, and ``partition_for_aie`` prints this fact so it cannot
happen silently.
"""

from __future__ import annotations

import tvm
from tvm import relay

__all__ = ["aie_compiler", "register", "emit_c_for_function"]

#: Keep in sync with aie_annotate.AIE_COMPILER_NAME.
_COMPILER = "aie"

_C_PRELUDE = """\
/* Generated by src/frontend/tvmrelay/byoc/aie_codegen.py -- do not edit.
 *
 * C wrapper for the AIE BYOC subgraph. It conforms to TVM's C packed ABI, so it
 * can be compiled by the same Makefile and linked into the same main.elf as the
 * kernels TVM emits itself.
 *
 * Note: the function body is a placeholder implementation, not a convolution.
 * It is used to validate the whole BYOC chain (partition/codegen/compile/link);
 * the real compute comes from the AIE kernel generated by run_aie_pipeline --
 * plugging that in only requires replacing the function body, with the signature
 * and the call sites unchanged.
 */
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifndef TVM_DLL
#define TVM_DLL
#endif

/* libconv2dstem.a. Declared rather than #included so this file stays
 * self-contained and needs no -I at codegen time; the archive exports these
 * with C linkage (conv2dstem.h wraps its API in extern "C"). */
#ifdef __cplusplus
extern "C" {
#endif
int conv2d_stem_raw(const int8_t *ifm, const int8_t *wts, int32_t *ofm);

/* Weight channel.
 *
 * MergeComposite folds the convolution weights into the partitioned function
 * as a Constant, so they are NOT a subgraph parameter and never arrive through
 * the packed args. The host publishes them once, before the graph runs, and
 * the wrapper reads them back here. Returns NULL if nothing was published --
 * the wrapper then fails loudly instead of convolving against garbage. */
const int8_t *conv2dstem_byoc_weights(void);
void conv2dstem_byoc_set_weights(const int8_t *wts);
#ifdef __cplusplus
}
#endif

/* Definition of the weight channel, emitted once per compilation unit. */
static const int8_t *g_conv2dstem_byoc_wts = NULL;
const int8_t *conv2dstem_byoc_weights(void) { return g_conv2dstem_byoc_wts; }
void conv2dstem_byoc_set_weights(const int8_t *wts) { g_conv2dstem_byoc_wts = wts; }
"""

_FUNC_TMPL = """
/* Subgraph {name}
 *   inputs  : {in_desc}
 *   output  : {out_desc}
 */
#ifdef __cplusplus
extern "C"
#endif
TVM_DLL int {name}_wrapper_({args_decl}) {{
{body}
    return 0;
}}

#ifdef __cplusplus
extern "C"
#endif
TVM_DLL int {name}(void* args, int* type_codes, int num_args,
                   void* out_value, int* out_type_code) {{
    /* TVM's packed calling convention: args is a TVMValue[], and each v_handle
     * points at a DLTensor. Here we only take the data pointer and forward it to
     * _wrapper_; the shapes were already baked in at generation time. */
    void** handles = (void**)args;
    (void)type_codes; (void)num_args; (void)out_value; (void)out_type_code;
{unpack}
    return {name}_wrapper_({call_args});
}}
"""


def _dltensor_elems(ttype) -> int:
    """Number of tensor elements; the shape is known at compile time, so just
    multiply it out."""
    n = 1
    for d in ttype.shape:
        n *= int(d)
    return n


def _c_dtype(ttype) -> str:
    """Relay dtype -> C type. Only covers the few that actually occur in the
    quantized graph; anything else raises instead of being guessed -- a wrong
    guess generates code that compiles but computes the wrong answer."""
    mapping = {"int8": "int8_t", "uint8": "uint8_t", "int16": "int16_t",
               "int32": "int32_t", "float32": "float"}
    dt = str(ttype.dtype)
    if dt not in mapping:
        raise ValueError(f"AIE BYOC codegen does not support dtype {dt!r}")
    return mapping[dt]


#: Subgraph signature `conv2d_stem_raw` can actually serve, as the partitioned
#: Relay function presents it: the spatially pre-padded uint8 input and the raw
#: int32 accumulator, both NCHW. Anything else falls back to the placeholder
#: rather than calling the library with a shape it was not built for.
_STEM_IN_SHAPE = [1, 3, 230, 230]
_STEM_OUT_SHAPE = [1, 64, 112, 112]


def _is_stem_signature(in_types, out_type) -> bool:
    """True iff this subgraph is the ResNet-18 stem conv `libconv2dstem.a` implements."""
    if len(in_types) != 1:
        return False
    t = in_types[0]
    return ([int(d) for d in t.shape] == _STEM_IN_SHAPE
            and str(t.dtype) == "uint8"
            and [int(d) for d in out_type.shape] == _STEM_OUT_SHAPE
            and str(out_type.dtype) == "int32")


def _stem_body(in_types, out_type, n_out: int, n_in0: int) -> str:
    """C body for the subgraph: a real AIE call when we recognise the stem.

    The AIE library wants the UNPADDED [224,224,3] int8 HWC input, while Relay
    hands us a pre-padded [1,3,230,230] uint8 NCHW tensor (TVM hoists the
    spatial padding into its own `nn.pad`, and conv2d_stem_raw re-pads
    internally). So the wrapper de-pads and transposes on the way in.

    The uint8 -> int8 step is a plain reinterpretation: this model's input
    zero-point is folded into the surrounding ops, which stay outside the
    subgraph, so the bytes carry straight through.

    Weights are NOT a subgraph parameter -- MergeComposite folded them into the
    partitioned function as a Constant -- so they are published by the host via
    conv2dstem_byoc_set_weights() before the graph runs.
    """
    if not _is_stem_signature(in_types, out_type):
        # Not the stem. Keep the old placeholder (copy + clamp, deliberately
        # input-dependent so an all-zero output cannot masquerade as success)
        # rather than calling into a library built for a different geometry.
        return f"""    /* Placeholder: subgraph is not the stem conv this library implements. */
    const int n_out = {n_out};
    const int n_in  = {n_in0};
    for (int i = 0; i < n_out; ++i) {{
        int v = (n_in > 0) ? (int)in0[i % n_in] : 0;
        if (v > 127) v = 127;
        if (v < -128) v = -128;
        out0[i] = ({_c_dtype(out_type)})v;
    }}"""

    return """    /* ResNet-18 stem conv on the AIE mesh (libconv2dstem.a). */
    const int8_t* wts = conv2dstem_byoc_weights();
    if (wts == NULL) { return -1; }   /* weights never published */

    /* [1,3,230,230] uint8 NCHW, pre-padded  ->  [224,224,3] int8 HWC, unpadded */
    static int8_t ifm[224 * 224 * 3];
    for (int h = 0; h < 224; ++h)
        for (int w = 0; w < 224; ++w)
            for (int c = 0; c < 3; ++c)
                ifm[(h * 224 + w) * 3 + c] =
                    (int8_t)in0[(c * 230 + (h + 3)) * 230 + (w + 3)];

    return conv2d_stem_raw(ifm, wts, out0);"""


def emit_c_for_function(func, name: str) -> str:
    """Turn one partitioned Relay function into C source. Returns the source string.

    Only the function's **signature** is inspected (the shapes and dtypes of the
    inputs/output); the body is not traversed -- the body is the qconv that
    MergeComposite already fused, and the real implementation will be supplied
    later by the AIE kernel.
    """
    params = list(func.params)
    in_types = [p.checked_type for p in params]
    out_type = func.ret_type

    args_decl = ", ".join(
        f"{_c_dtype(t)}* in{i}" for i, t in enumerate(in_types)
    ) + f", {_c_dtype(out_type)}* out0"

    unpack_lines, call_args = [], []
    for i, t in enumerate(in_types):
        unpack_lines.append(
            f"    {_c_dtype(t)}* in{i} = ({_c_dtype(t)}*)(((void**)handles[{i}])[0]);")
        call_args.append(f"in{i}")
    out_idx = len(in_types)
    unpack_lines.append(
        f"    {_c_dtype(out_type)}* out0 = "
        f"({_c_dtype(out_type)}*)(((void**)handles[{out_idx}])[0]);")
    call_args.append("out0")

    n_out = _dltensor_elems(out_type)
    n_in0 = _dltensor_elems(in_types[0]) if in_types else 0
    body = _stem_body(in_types, out_type, n_out, n_in0)

    in_desc = ", ".join(f"{list(t.shape)} {t.dtype}" for t in in_types) or "(none)"
    out_desc = f"{list(out_type.shape)} {out_type.dtype}"
    return _FUNC_TMPL.format(
        name=name, args_decl=args_decl, body=body,
        unpack="\n".join(unpack_lines), call_args=", ".join(call_args),
        in_desc=in_desc, out_desc=out_desc)


@tvm._ffi.register_func("relay.ext.aie")
def aie_compiler(ref):
    """TVM calls this for every function with ``Compiler="aie"``. Returns a runtime.Module.

    ``ref`` is a ``relay.Function`` carrying a ``global_symbol`` attribute -- that
    symbol name is what the host-side generated call site will link against, so it
    must be used verbatim as the C function name.
    """
    if not isinstance(ref, relay.Function):
        raise ValueError(f"relay.ext.aie expected a Function, got {type(ref)}")

    name = str(ref.attrs["global_symbol"])
    code = _C_PRELUDE + emit_c_for_function(ref, name)

    # fmt="c" tells TVM to treat it as a C source module, to be compiled along
    # with everything else by the target="c" toolchain.
    csource = tvm.get_global_func("runtime.CSourceModuleCreate")
    return csource(code, "c", [name], [])


def register() -> bool:
    """Confirm that ``relay.ext.aie`` is registered. Importing this module is what
    performs the registration; this is only an explicit confirmation point for the
    caller (and a reason for the import not to be flagged as unused by a linter)."""
    return bool(tvm.get_global_func("relay.ext.aie", allow_missing=True))
