/******************************************************************************
 * Copyright (C) 2026 Advanced Micro Devices, Inc. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

#include "ctrlpkt_dbg.h"

#include <ctype.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

static int mkdir_p(const char *dir) {
    char p[1024];
    snprintf(p, sizeof(p), "%s", dir);
    for (char *s = p + 1; *s; s++) {
        if (*s != '/')
            continue;
        *s = '\0';
        if (mkdir(p, 0755) != 0 && errno != EEXIST)
            return -1;
        *s = '/';
    }
    return (mkdir(p, 0755) == 0 || errno == EEXIST) ? 0 : -1;
}

static FILE *open_in(const char *dir, const char *file, const char *mode) {
    if (mkdir_p(dir) != 0)
        return NULL;
    char path[1024];
    snprintf(path, sizeof(path), "%s/%s", dir, file);
    return fopen(path, mode);
}

FILE *cpd_open_raw(const char *dir, const char *file, const char *mode) {
    char raw[1024];
    snprintf(raw, sizeof(raw), "%s/raw", dir);
    return open_in(raw, file, mode);
}

static void ident(const char *name, int upper, char *out, size_t n) {
    size_t i = 0U;
    for (; name[i] && i + 1U < n; i++) {
        char c = isalnum((unsigned char)name[i]) ? name[i] : '_';
        out[i] = upper ? (char)toupper((unsigned char)c) : c;
    }
    out[i] = '\0';
}

static void put_comment_lines(FILE *f, const char *indent, const char *text) {
    for (const char *s = text; *s;) {
        const char *e = strchr(s, '\n');
        size_t len = e ? (size_t)(e - s) : strlen(s);
        fprintf(f, "%s * %.*s\n", indent, (int)len, s);
        s += len + (e ? 1 : 0);
    }
}

FILE *cpd_open_h(const char *dir, const char *name, const char *title) {
    char file[300], guard[300];
    snprintf(file, sizeof(file), "%s.h", name);
    FILE *f = open_in(dir, file, "w");
    if (!f)
        return NULL;
    ident(name, 1, guard, sizeof(guard));
    fprintf(f, "/* Auto-generated by aiehlc_ctrlpkt --debug-dir (AOT control packets, debug dump) -- do not edit.\n");
    if (title) {
        fprintf(f, " *\n");
        put_comment_lines(f, "", title);
    }
    fprintf(f, " *\n"
               " * Access = stream header (packet id [4:0], odd parity bit 31), control header\n"
               " * ([19:0] tile address, [21:20] words-1, [23:22] op: write, read, write+ret =\n"
               " * write-with-return), data words. @N = word offset in this array.\n"
               " */\n#ifndef CTRLPKT_DBG_%s_H\n#define CTRLPKT_DBG_%s_H\n\n#include <stdint.h>\n\n",
            guard, guard);
    return f;
}

int cpd_close_h(FILE *f) {
    fprintf(f, "\n#endif\n");
    return fclose(f) == 0 ? 0 : -1;
}

static const char *op_name(uint32_t op) {
    static const char *names[4] = {"write", "read", "write+ret", "op3"};
    return names[op & 3U];
}

static void ann_mark(FILE *ann, uint32_t at, const char *text) {
    if (!ann)
        return;
    fprintf(ann, "M\t%u\t", (unsigned)at);
    for (const char *s = text; *s; s++)
        *s == '\n' ? fputs("\\n", ann) : fputc(*s, ann);
    fputc('\n', ann);
}

static void put_banner(FILE *f, FILE *ann, const cpd_mark *m) {
    fprintf(f, "\n\n    /* ");
    for (const char *s = m->text; *s; s++)
        *s == '\n' ? fputs("\n     * ", f) : fputc(*s, f);
    fprintf(f, " */");
    ann_mark(ann, m->at, m->text);
}

void cpd_array(FILE *f, FILE *ann, const char *name, const uint32_t *w, uint32_t n, const cpd_mark *marks, int nmarks,
               cpd_note_fn note, void *ctx) {
    char id[300], mac[300];
    ident(name, 0, id, sizeof(id));
    ident(name, 1, mac, sizeof(mac));
    fprintf(f, "static const uint32_t ctrlpkt_%s[] = {", id);
    if (n == 0U)
        fprintf(f, "\n    0u /* no words */");
    int m = 0;
    uint32_t acc = 0U;
    for (uint32_t i = 0U; i + 2U <= n; acc++) {
        uint32_t hdr = w[i], ctrl = w[i + 1U];
        uint32_t addr = ctrl & 0xFFFFFU, beats = ((ctrl >> 20U) & 0x3U) + 1U, op = (ctrl >> 22U) & 0x3U;
        uint32_t len = 2U + (op == 1U ? 0U : beats);
        if (i + len > n)
            len = n - i;
        for (; m < nmarks && marks[m].at < i + len; m++)
            put_banner(f, ann, &marks[m]);
        char words[96] = "", *p = words;
        for (uint32_t k = 0U; k < len; k++)
            p += snprintf(p, sizeof(words) - (size_t)(p - words), "0x%08xu, ", (unsigned)w[i + k]);
        char cmt[512] = "";
        if (note)
            note(ctx, acc, i, w + i, len, cmt, sizeof(cmt));
        int bad = !__builtin_parity(hdr) || !__builtin_parity(ctrl);
        fprintf(f, "\n    %-78s/* @%u id 0x%02x %s %uw 0x%05x%s%s%s */", words, (unsigned)i, (unsigned)(hdr & 0x1FU),
                op_name(op), (unsigned)beats, (unsigned)addr, cmt[0] ? ": " : "", cmt, bad ? " !PARITY" : "");
        if (ann)
            fprintf(ann, "A\t%u\t%s\n", (unsigned)i, cmt);
        i += len;
    }
    for (; m < nmarks; m++)
        put_banner(f, ann, &marks[m]);
    fprintf(f, "\n};\n#define CTRLPKT_%s_WORDS %uu /* %u access%s */\n", mac, (unsigned)n, (unsigned)acc,
            acc == 1U ? "" : "es");
}

int cpd_bin(const char *dir, const char *name, const uint32_t *w, uint32_t n) {
    char file[300];
    snprintf(file, sizeof(file), "%s.bin", name);
    FILE *f = cpd_open_raw(dir, file, "wb");
    if (!f)
        return -1;
    size_t put = fwrite(w, sizeof(uint32_t), n, f);
    return (fclose(f) == 0 && put == n) ? 0 : -1;
}

int cpd_dump(const char *dir, const char *name, const char *title, const uint32_t *w, uint32_t n,
             const cpd_mark *marks, int nmarks, cpd_note_fn note, void *ctx) {
    FILE *f = cpd_open_h(dir, name, title);
    if (!f)
        return -1;
    char file[300];
    snprintf(file, sizeof(file), "%s.ann", name);
    FILE *ann = cpd_open_raw(dir, file, "w");
    cpd_array(f, ann, name, w, n, marks, nmarks, note, ctx);
    if (ann)
        fclose(ann);
    int rc = cpd_close_h(f);
    if (cpd_bin(dir, name, w, n) != 0)
        rc = -1;
    const char *t = title ? title : "";
    size_t nlen = strlen(name);
    if (!strncmp(t, name, nlen) && !strncmp(t + nlen, ": ", 2))
        t += nlen + 2;
    const char *nl = strchr(t, '\n');
    char what[256];
    snprintf(what, sizeof(what), "%.*s", nl ? (int)(nl - t) : (int)sizeof(what) - 1, t);
    cpd_index(dir, name, n, what);
    return rc;
}

int cpd_ann_load(const char *dir, const char *name, uint32_t shift, cpd_ann *a) {
    memset(a, 0, sizeof(*a));
    char file[256];
    snprintf(file, sizeof(file), "%s.ann", name);
    FILE *f = cpd_open_raw(dir, file, "r");
    if (!f)
        return -1;
    char line[1024];
    int cap_m = 0;
    uint32_t cap_n = 0U;
    while (fgets(line, sizeof(line), f)) {
        char *t1 = strchr(line, '\t'), *t2 = t1 ? strchr(t1 + 1, '\t') : NULL;
        if (!t2 || (line[0] != 'M' && line[0] != 'A'))
            continue;
        char *text = t2 + 1, *nl = strchr(text, '\n');
        if (nl)
            *nl = '\0';
        uint32_t at = (uint32_t)strtoul(t1 + 1, NULL, 10) + shift;
        if (line[0] == 'A') {
            if (a->nnotes == cap_n) {
                cap_n = cap_n ? 2U * cap_n : 256U;
                a->notes = (char **)realloc(a->notes, cap_n * sizeof(char *));
            }
            a->notes[a->nnotes++] = strdup(text);
            continue;
        }
        char *u = strdup(text), *o = u;
        for (const char *p = u; *p; p++, o++) {
            if (p[0] == '\\' && p[1] == 'n') {
                *o = '\n';
                p++;
            } else {
                *o = *p;
            }
        }
        *o = '\0';
        if (a->nmarks == cap_m) {
            cap_m = cap_m ? 2 * cap_m : 64;
            a->marks = (cpd_mark *)realloc(a->marks, (size_t)cap_m * sizeof(cpd_mark));
        }
        a->marks[a->nmarks].at = at;
        a->marks[a->nmarks++].text = u;
    }
    fclose(f);
    return 0;
}

void cpd_ann_free(cpd_ann *a) {
    for (int i = 0; i < a->nmarks; i++)
        free((char *)a->marks[i].text);
    for (uint32_t i = 0U; i < a->nnotes; i++)
        free(a->notes[i]);
    free(a->marks);
    free(a->notes);
    memset(a, 0, sizeof(*a));
}

static void put_cstr(FILE *f, const char *s) {
    fputc('"', f);
    for (; *s; s++) {
        if (*s == '"' || *s == '\\')
            fputc('\\', f);
        fputc(*s, f);
    }
    fputc('"', f);
}

static void write_index(const char *dir) {
    FILE *t = cpd_open_raw(dir, "index.tsv", "r");
    if (!t)
        return;
    char names[64][128], whats[64][256];
    unsigned words[64];
    int n = 0;
    char line[512];
    while (n < 64 && fgets(line, sizeof(line), t)) {
        char *a = strchr(line, '\t'), *b = a ? strchr(a + 1, '\t') : NULL, *e = strchr(line, '\n');
        if (!b)
            continue;
        if (e)
            *e = '\0';
        snprintf(names[n], sizeof(names[0]), "%.*s", (int)(a - line), line);
        words[n] = (unsigned)strtoul(a + 1, NULL, 10);
        snprintf(whats[n], sizeof(whats[0]), "%s", b + 1);
        n++;
    }
    fclose(t);
    FILE *f = cpd_open_h(dir, "index",
                         "index.h: every AOT control-packet site of this build (#pragma control_packet_mode(aot)).\n"
                         "Same words as kernel_<fn>_ctrlpkt.h / host_ctrlpkt.h, one header per site, written by\n"
                         "kc.sh on every AOT build. Each banner inside a site header names the runtime API call\n"
                         "and its host.cc line; each array line names the register and the MMIO API it replaces.\n"
                         "\n"
                         "  kernel_<fn>.h        kernel-ELF load body (resets, PT_LOAD writes, completion barrier)\n"
                         "  plan_ret.h           ctrl_plan_init return-route prefix, plus the writes that stay MMIO\n"
                         "  kernel_<fn>_wire.h   the ELF-load BD as sent: plan_ret, then the kernel body\n"
                         "  write<N>_<what>.h    one broadcast / row-multicast write (core enable, lock init)\n"
                         "  shim_bd_seg<K>_col<C>.h  one shim-BD window segment (relaunch-only prefix and the\n"
                         "                       run-time patched DDR address words are marked)\n"
                         "  shim_bd_calls.h      the window's match table and batched replay arguments\n"
                         "  raw/<name>.bin       the words, little-endian (diff against a board capture)\n"
                         "  raw/<name>.ann       banners (M) and per-access comments (A) by word offset, for tools");
    if (!f)
        return;
    for (int i = 0; i < n; i++)
        if (names[i][0] != '-')
            fprintf(f, "#include \"%s.h\"\n", names[i]);
    fprintf(f, "\ntypedef struct {\n    const char *name;\n    const uint32_t *words; /* NULL: table-only header */\n"
               "    uint32_t nwords;\n    const char *site;\n} ctrlpkt_dbg_site;\n\n"
               "static const ctrlpkt_dbg_site ctrlpkt_dbg_sites[] = {\n");
    for (int i = 0; i < n; i++) {
        char id[200], mac[200];
        if (names[i][0] == '-') {
            fprintf(f, "    /* not precomputed: %s */\n", whats[i]);
            continue;
        }
        ident(names[i], 0, id, sizeof(id));
        ident(names[i], 1, mac, sizeof(mac));
        fprintf(f, "    {");
        put_cstr(f, names[i]);
        if (words[i])
            fprintf(f, ", ctrlpkt_%s, CTRLPKT_%s_WORDS, ", id, mac);
        else
            fprintf(f, ", 0, 0u, ");
        put_cstr(f, whats[i]);
        fprintf(f, "},\n");
    }
    fprintf(f, "};\n");
    cpd_close_h(f);
}

void cpd_index(const char *dir, const char *name, uint32_t words, const char *what) {
    FILE *f = cpd_open_raw(dir, "index.tsv", "a");
    if (!f)
        return;
    fprintf(f, "%s\t%u\t%s\n", name, (unsigned)words, what);
    fclose(f);
    write_index(dir);
}
