module attributes {codegen.headers = ["stdint.h", "stdio.h", "custom_lib.h"], routing.effective_k = 64 : i64, routing.full_k = 512 : i64, routing.k_rounds = 8 : i64, routing.m_rounds = 8 : i64, routing.n_rounds = 8 : i64, routing.pp_depth_map = {tensor_0 = 2 : i32, tensor_1 = 2 : i32, tensor_2 = 2 : i32}, routing.tile_cols = 128 : i64, routing.tile_m = 16 : i64, routing.tile_n = 16 : i64, routing.tile_rows = 128 : i64} {
  func.func @routing(%arg0: !emitc.ptr<!emitc.opaque<"XAie_DevInst">>) {
    %0 = "emitc.constant"() <{value = true}> : () -> i1
    emitc.verbatim "\0A//round is 0 hw split in : col -----------"
    emitc.if %0 {
      %1 = emitc.call_opaque "XAie_EnableShimDmaToAieStrmPort"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,0)">, 3 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %2 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,0)">, #emitc.opaque<"SOUTH">, 3 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %3 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,1)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %4 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,2)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %5 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,3)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %6 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,3)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"DMA">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %7 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,4)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %8 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,4)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"DMA">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %9 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,5)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %10 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,5)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"DMA">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %11 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,6)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"DMA">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
    }
    emitc.verbatim "\0A//round is 1 hw split in : col -----------"
    emitc.if %0 {
      %1 = emitc.call_opaque "XAie_EnableShimDmaToAieStrmPort"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,0)">, 3 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %2 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,0)">, #emitc.opaque<"SOUTH">, 3 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %3 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,1)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %4 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,2)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %5 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,3)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %6 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,3)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"DMA">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %7 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,4)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %8 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,4)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"DMA">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %9 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,5)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %10 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,5)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"DMA">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %11 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,6)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"DMA">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
    }
    emitc.verbatim "\0A//round is 2 hw split in : col -----------"
    emitc.if %0 {
      %1 = emitc.call_opaque "XAie_EnableShimDmaToAieStrmPort"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,0)">, 3 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %2 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,0)">, #emitc.opaque<"SOUTH">, 3 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %3 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,1)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %4 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,2)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %5 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,3)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %6 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,3)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"DMA">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %7 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,4)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %8 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,4)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"DMA">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %9 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,5)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %10 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,5)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"DMA">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %11 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,6)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"DMA">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
    }
    emitc.verbatim "\0A//round is 3 hw split in : col -----------"
    emitc.if %0 {
      %1 = emitc.call_opaque "XAie_EnableShimDmaToAieStrmPort"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,0)">, 3 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %2 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,0)">, #emitc.opaque<"SOUTH">, 3 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %3 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,1)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %4 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,2)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %5 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,3)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %6 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,3)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"DMA">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %7 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,4)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %8 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,4)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"DMA">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %9 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,5)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"NORTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %10 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,5)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"DMA">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %11 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,6)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"DMA">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
    }
    emitc.verbatim "\0A//round is 0 hw split in : row -----------"
    emitc.if %0 {
      %1 = emitc.call_opaque "XAie_EnableShimDmaToAieStrmPort"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,0)">, 7 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %2 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,0)">, #emitc.opaque<"SOUTH">, 7 : i32, #emitc.opaque<"NORTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %3 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,1)">, #emitc.opaque<"SOUTH">, 1 : i32, #emitc.opaque<"NORTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %4 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,2)">, #emitc.opaque<"SOUTH">, 1 : i32, #emitc.opaque<"NORTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %5 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,3)">, #emitc.opaque<"SOUTH">, 1 : i32, #emitc.opaque<"EAST">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %6 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,3)">, #emitc.opaque<"SOUTH">, 1 : i32, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %7 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,3)">, #emitc.opaque<"WEST">, 0 : i32, #emitc.opaque<"EAST">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %8 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,3)">, #emitc.opaque<"WEST">, 0 : i32, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %9 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,3)">, #emitc.opaque<"WEST">, 0 : i32, #emitc.opaque<"EAST">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %10 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,3)">, #emitc.opaque<"WEST">, 0 : i32, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %11 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,3)">, #emitc.opaque<"WEST">, 0 : i32, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %12 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,3)">, #emitc.opaque<"DMA">, 0 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(1, 0)">, 31 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %13 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,3)">, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %14 = emitc.call_opaque "XAie_StrmPktSwMstrPortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,3)">, #emitc.opaque<"EAST">, 1 : i32, #emitc.opaque<"XAIE_SS_PKT_DONOT_DROP_HEADER">, 0 : i32, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %15 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,3)">, #emitc.opaque<"WEST">, 1 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(0, 0)">, 0 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %16 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,3)">, #emitc.opaque<"WEST">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %17 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,3)">, #emitc.opaque<"DMA">, 0 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(2, 0)">, 31 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %18 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,3)">, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %19 = emitc.call_opaque "XAie_StrmPktSwMstrPortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,3)">, #emitc.opaque<"EAST">, 1 : i32, #emitc.opaque<"XAIE_SS_PKT_DONOT_DROP_HEADER">, 0 : i32, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %20 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,3)">, #emitc.opaque<"WEST">, 1 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(0, 0)">, 0 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %21 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,3)">, #emitc.opaque<"WEST">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %22 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,3)">, #emitc.opaque<"DMA">, 0 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(3, 0)">, 31 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %23 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,3)">, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %24 = emitc.call_opaque "XAie_StrmPktSwMstrPortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,3)">, #emitc.opaque<"EAST">, 1 : i32, #emitc.opaque<"XAIE_SS_PKT_DONOT_DROP_HEADER">, 0 : i32, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %25 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,3)">, #emitc.opaque<"WEST">, 1 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(0, 0)">, 0 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %26 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,3)">, #emitc.opaque<"WEST">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %27 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,3)">, #emitc.opaque<"DMA">, 0 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(4, 0)">, 31 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %28 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,3)">, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %29 = emitc.call_opaque "XAie_EnableAieToShimDmaStrmPort"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,0)">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %30 = emitc.call_opaque "XAie_StrmPktSwMstrPortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,3)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"XAIE_SS_PKT_DONOT_DROP_HEADER">, 0 : i32, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %31 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,2)">, #emitc.opaque<"NORTH">, 0 : i32, #emitc.opaque<"SOUTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %32 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,1)">, #emitc.opaque<"NORTH">, 0 : i32, #emitc.opaque<"SOUTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %33 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,0)">, #emitc.opaque<"NORTH">, 0 : i32, #emitc.opaque<"SOUTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
    }
    emitc.verbatim "\0A//round is 1 hw split in : row -----------"
    emitc.if %0 {
      %1 = emitc.call_opaque "XAie_EnableShimDmaToAieStrmPort"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,0)">, 7 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %2 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,0)">, #emitc.opaque<"SOUTH">, 7 : i32, #emitc.opaque<"NORTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %3 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,1)">, #emitc.opaque<"SOUTH">, 1 : i32, #emitc.opaque<"NORTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %4 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,2)">, #emitc.opaque<"SOUTH">, 1 : i32, #emitc.opaque<"NORTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %5 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,3)">, #emitc.opaque<"SOUTH">, 1 : i32, #emitc.opaque<"WEST">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %6 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,3)">, #emitc.opaque<"SOUTH">, 1 : i32, #emitc.opaque<"NORTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %7 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,3)">, #emitc.opaque<"EAST">, 0 : i32, #emitc.opaque<"NORTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %8 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,4)">, #emitc.opaque<"SOUTH">, 1 : i32, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %9 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,4)">, #emitc.opaque<"SOUTH">, 1 : i32, #emitc.opaque<"EAST">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %10 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,4)">, #emitc.opaque<"SOUTH">, 1 : i32, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %11 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,4)">, #emitc.opaque<"WEST">, 0 : i32, #emitc.opaque<"EAST">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %12 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,4)">, #emitc.opaque<"WEST">, 0 : i32, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %13 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,4)">, #emitc.opaque<"WEST">, 0 : i32, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %14 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,4)">, #emitc.opaque<"DMA">, 0 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(5, 0)">, 31 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %15 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,4)">, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %16 = emitc.call_opaque "XAie_StrmPktSwMstrPortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,4)">, #emitc.opaque<"EAST">, 0 : i32, #emitc.opaque<"XAIE_SS_PKT_DONOT_DROP_HEADER">, 0 : i32, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %17 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,4)">, #emitc.opaque<"WEST">, 0 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(0, 0)">, 0 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %18 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,4)">, #emitc.opaque<"WEST">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %19 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,4)">, #emitc.opaque<"DMA">, 0 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(6, 0)">, 31 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %20 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,4)">, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %21 = emitc.call_opaque "XAie_StrmPktSwMstrPortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,4)">, #emitc.opaque<"EAST">, 1 : i32, #emitc.opaque<"XAIE_SS_PKT_DONOT_DROP_HEADER">, 0 : i32, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %22 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,4)">, #emitc.opaque<"WEST">, 1 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(0, 0)">, 0 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %23 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,4)">, #emitc.opaque<"WEST">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %24 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,4)">, #emitc.opaque<"DMA">, 0 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(7, 0)">, 31 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %25 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,4)">, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %26 = emitc.call_opaque "XAie_StrmPktSwMstrPortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,4)">, #emitc.opaque<"EAST">, 1 : i32, #emitc.opaque<"XAIE_SS_PKT_DONOT_DROP_HEADER">, 0 : i32, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %27 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,4)">, #emitc.opaque<"WEST">, 1 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(0, 0)">, 0 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %28 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,4)">, #emitc.opaque<"WEST">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %29 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,4)">, #emitc.opaque<"DMA">, 0 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(8, 0)">, 31 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %30 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,4)">, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %31 = emitc.call_opaque "XAie_EnableAieToShimDmaStrmPort"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,0)">, 3 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %32 = emitc.call_opaque "XAie_StrmPktSwMstrPortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,4)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"XAIE_SS_PKT_DONOT_DROP_HEADER">, 0 : i32, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %33 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,3)">, #emitc.opaque<"NORTH">, 0 : i32, #emitc.opaque<"SOUTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %34 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,2)">, #emitc.opaque<"NORTH">, 1 : i32, #emitc.opaque<"SOUTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %35 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,1)">, #emitc.opaque<"NORTH">, 1 : i32, #emitc.opaque<"SOUTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %36 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,0)">, #emitc.opaque<"NORTH">, 1 : i32, #emitc.opaque<"SOUTH">, 3 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
    }
    emitc.verbatim "\0A//round is 2 hw split in : row -----------"
    emitc.if %0 {
      %1 = emitc.call_opaque "XAie_EnableShimDmaToAieStrmPort"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,0)">, 7 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %2 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,0)">, #emitc.opaque<"SOUTH">, 7 : i32, #emitc.opaque<"NORTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %3 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,1)">, #emitc.opaque<"SOUTH">, 1 : i32, #emitc.opaque<"NORTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %4 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,2)">, #emitc.opaque<"SOUTH">, 1 : i32, #emitc.opaque<"NORTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %5 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,3)">, #emitc.opaque<"SOUTH">, 1 : i32, #emitc.opaque<"WEST">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %6 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,3)">, #emitc.opaque<"EAST">, 0 : i32, #emitc.opaque<"WEST">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %7 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,3)">, #emitc.opaque<"EAST">, 1 : i32, #emitc.opaque<"NORTH">, 2 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %8 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,4)">, #emitc.opaque<"SOUTH">, 2 : i32, #emitc.opaque<"NORTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %9 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,5)">, #emitc.opaque<"SOUTH">, 1 : i32, #emitc.opaque<"EAST">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %10 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,5)">, #emitc.opaque<"SOUTH">, 1 : i32, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %11 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,5)">, #emitc.opaque<"WEST">, 0 : i32, #emitc.opaque<"EAST">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %12 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,5)">, #emitc.opaque<"WEST">, 0 : i32, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %13 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,5)">, #emitc.opaque<"WEST">, 0 : i32, #emitc.opaque<"EAST">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %14 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,5)">, #emitc.opaque<"WEST">, 0 : i32, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %15 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,5)">, #emitc.opaque<"WEST">, 0 : i32, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %16 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,5)">, #emitc.opaque<"DMA">, 0 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(9, 0)">, 31 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %17 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,5)">, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %18 = emitc.call_opaque "XAie_StrmPktSwMstrPortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,5)">, #emitc.opaque<"EAST">, 1 : i32, #emitc.opaque<"XAIE_SS_PKT_DONOT_DROP_HEADER">, 0 : i32, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %19 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,5)">, #emitc.opaque<"WEST">, 1 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(0, 0)">, 0 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %20 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,5)">, #emitc.opaque<"WEST">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %21 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,5)">, #emitc.opaque<"DMA">, 0 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(10, 0)">, 31 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %22 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,5)">, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %23 = emitc.call_opaque "XAie_StrmPktSwMstrPortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,5)">, #emitc.opaque<"EAST">, 1 : i32, #emitc.opaque<"XAIE_SS_PKT_DONOT_DROP_HEADER">, 0 : i32, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %24 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,5)">, #emitc.opaque<"WEST">, 1 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(0, 0)">, 0 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %25 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,5)">, #emitc.opaque<"WEST">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %26 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,5)">, #emitc.opaque<"DMA">, 0 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(11, 0)">, 31 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %27 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,5)">, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %28 = emitc.call_opaque "XAie_StrmPktSwMstrPortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,5)">, #emitc.opaque<"EAST">, 1 : i32, #emitc.opaque<"XAIE_SS_PKT_DONOT_DROP_HEADER">, 0 : i32, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %29 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,5)">, #emitc.opaque<"WEST">, 1 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(0, 0)">, 0 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %30 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,5)">, #emitc.opaque<"WEST">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %31 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,5)">, #emitc.opaque<"DMA">, 0 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(12, 0)">, 31 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %32 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,5)">, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %33 = emitc.call_opaque "XAie_EnableAieToShimDmaStrmPort"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,0)">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %34 = emitc.call_opaque "XAie_StrmPktSwMstrPortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,5)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"XAIE_SS_PKT_DONOT_DROP_HEADER">, 0 : i32, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %35 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,4)">, #emitc.opaque<"NORTH">, 0 : i32, #emitc.opaque<"SOUTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %36 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,3)">, #emitc.opaque<"NORTH">, 1 : i32, #emitc.opaque<"WEST">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %37 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,3)">, #emitc.opaque<"EAST">, 0 : i32, #emitc.opaque<"SOUTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %38 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,2)">, #emitc.opaque<"NORTH">, 0 : i32, #emitc.opaque<"SOUTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %39 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,1)">, #emitc.opaque<"NORTH">, 0 : i32, #emitc.opaque<"SOUTH">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %40 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,0)">, #emitc.opaque<"NORTH">, 0 : i32, #emitc.opaque<"SOUTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
    }
    emitc.verbatim "\0A//round is 3 hw split in : row -----------"
    emitc.if %0 {
      %1 = emitc.call_opaque "XAie_EnableShimDmaToAieStrmPort"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,0)">, 7 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %2 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,0)">, #emitc.opaque<"SOUTH">, 7 : i32, #emitc.opaque<"NORTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %3 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,1)">, #emitc.opaque<"SOUTH">, 1 : i32, #emitc.opaque<"NORTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %4 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,2)">, #emitc.opaque<"SOUTH">, 1 : i32, #emitc.opaque<"NORTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %5 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,3)">, #emitc.opaque<"SOUTH">, 1 : i32, #emitc.opaque<"WEST">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %6 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,3)">, #emitc.opaque<"EAST">, 1 : i32, #emitc.opaque<"WEST">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %7 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,3)">, #emitc.opaque<"EAST">, 1 : i32, #emitc.opaque<"WEST">, 2 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %8 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,3)">, #emitc.opaque<"EAST">, 2 : i32, #emitc.opaque<"NORTH">, 3 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %9 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,4)">, #emitc.opaque<"SOUTH">, 3 : i32, #emitc.opaque<"NORTH">, 2 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %10 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,5)">, #emitc.opaque<"SOUTH">, 2 : i32, #emitc.opaque<"NORTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %11 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,6)">, #emitc.opaque<"SOUTH">, 1 : i32, #emitc.opaque<"EAST">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %12 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,6)">, #emitc.opaque<"SOUTH">, 1 : i32, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %13 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,6)">, #emitc.opaque<"WEST">, 0 : i32, #emitc.opaque<"EAST">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %14 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,6)">, #emitc.opaque<"WEST">, 0 : i32, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %15 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,6)">, #emitc.opaque<"WEST">, 0 : i32, #emitc.opaque<"EAST">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %16 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,6)">, #emitc.opaque<"WEST">, 0 : i32, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %17 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,6)">, #emitc.opaque<"WEST">, 0 : i32, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %18 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,6)">, #emitc.opaque<"DMA">, 0 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(13, 0)">, 31 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %19 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,6)">, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %20 = emitc.call_opaque "XAie_StrmPktSwMstrPortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(0,6)">, #emitc.opaque<"EAST">, 1 : i32, #emitc.opaque<"XAIE_SS_PKT_DONOT_DROP_HEADER">, 0 : i32, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %21 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,6)">, #emitc.opaque<"WEST">, 1 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(0, 0)">, 0 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %22 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,6)">, #emitc.opaque<"WEST">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %23 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,6)">, #emitc.opaque<"DMA">, 0 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(14, 0)">, 31 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %24 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,6)">, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %25 = emitc.call_opaque "XAie_StrmPktSwMstrPortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(1,6)">, #emitc.opaque<"EAST">, 1 : i32, #emitc.opaque<"XAIE_SS_PKT_DONOT_DROP_HEADER">, 0 : i32, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %26 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,6)">, #emitc.opaque<"WEST">, 1 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(0, 0)">, 0 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %27 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,6)">, #emitc.opaque<"WEST">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %28 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,6)">, #emitc.opaque<"DMA">, 0 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(15, 0)">, 31 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %29 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,6)">, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %30 = emitc.call_opaque "XAie_StrmPktSwMstrPortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,6)">, #emitc.opaque<"EAST">, 1 : i32, #emitc.opaque<"XAIE_SS_PKT_DONOT_DROP_HEADER">, 0 : i32, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %31 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,6)">, #emitc.opaque<"WEST">, 1 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(0, 0)">, 0 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %32 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,6)">, #emitc.opaque<"WEST">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %33 = emitc.call_opaque "XAie_StrmPktSwSlaveSlotEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,6)">, #emitc.opaque<"DMA">, 0 : i32, 0 : i32, #emitc.opaque<"XAie_PacketInit(16, 0)">, 31 : i32, 0 : i32, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %34 = emitc.call_opaque "XAie_StrmPktSwSlavePortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,6)">, #emitc.opaque<"DMA">, 0 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %35 = emitc.call_opaque "XAie_EnableAieToShimDmaStrmPort"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,0)">, 3 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %36 = emitc.call_opaque "XAie_StrmPktSwMstrPortEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,6)">, #emitc.opaque<"SOUTH">, 0 : i32, #emitc.opaque<"XAIE_SS_PKT_DONOT_DROP_HEADER">, 0 : i32, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %37 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,5)">, #emitc.opaque<"NORTH">, 0 : i32, #emitc.opaque<"SOUTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %38 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,4)">, #emitc.opaque<"NORTH">, 1 : i32, #emitc.opaque<"SOUTH">, 2 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %39 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(3,3)">, #emitc.opaque<"NORTH">, 2 : i32, #emitc.opaque<"WEST">, 2 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %40 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,3)">, #emitc.opaque<"EAST">, 2 : i32, #emitc.opaque<"SOUTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %41 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,2)">, #emitc.opaque<"NORTH">, 1 : i32, #emitc.opaque<"SOUTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %42 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,1)">, #emitc.opaque<"NORTH">, 1 : i32, #emitc.opaque<"SOUTH">, 1 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
      %43 = emitc.call_opaque "XAie_StrmConnCctEnable"(%arg0) {args = [0 : index, #emitc.opaque<"XAie_TileLoc(2,0)">, #emitc.opaque<"NORTH">, 1 : i32, #emitc.opaque<"SOUTH">, 3 : i32]} : (!emitc.ptr<!emitc.opaque<"XAie_DevInst">>) -> i32
    }
    return
  }
  emitc.include <"xaiengine.h">
}
