/******************************************************************************
* Copyright (C) 2025 Advanced Micro Devices, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT
******************************************************************************/
#include "dshostmanager.h"
#include <iostream>

#define GET_TYPEDEF_CLASSES
#define GET_ATTRDEF_CLASSES
#define GET_OP_CLASSES
#define GET_OP_DEFS
//#define GET_OP_LIST
#include "dshostdialect.cc.inc"
#include "dshostattr.cc.inc"
#include "dshosttype.cc.inc"
#include "dshostenums.cc.inc"

#include "dshostop.cc.inc"
//#undef GET_OP_LIST
#undef GET_OP_DEFS

#undef GET_OP_CLASSES
#undef GET_ATTRDEF_CLASSES
#undef GET_TYPEDEF_CLASSES

void dshostdialect::initialize()  { 
    addOperations<
    #define GET_OP_LIST
    #include "dshostop.cc.inc"
        >();
    // 如果有 Attr / Type：addAttributes<...>(); addTypes<...>();
     addAttributes<
    #define GET_ATTRDEF_LIST
    #include "dshostattr.cc.inc"
    >();

        // 3. Types
    addTypes<
    #define GET_TYPEDEF_LIST
    #include "dshosttype.cc.inc"
    >();
}

/*
void dshostdialect::printType(Type type, DialectAsmPrinter &printer) const {
    // This is the C++ type generated by TableGen from your TypeDef.
    // Ensure you use the correct name (e.g., DMAPDataType).
    if (isa<dshostdataType>(type)) {
        // All you need to do is print the mnemonic you defined in TableGen.
        printer << "dshostdata";
    }
}
//*/


ModuleOp dshostmanager::ops_test(MLIRContext* ctx, int totalN) {
    const int hwrowused= 4, hwcolused=4;
    OpBuilder builder(ctx);
    mlir::ModuleOp m = ModuleOp::create(builder.getUnknownLoc());
    //auto func = createdshostfuncByDim(ctx, true);
    //m.push_back(func);
    auto functype = builder.getFunctionType({},{});
    
    dshost::FuncOp main = builder.create<dshost::FuncOp>(builder.getUnknownLoc(), "main", functype);
    m.push_back(main);
    ///*
    //auto block = main.addEntryBlock();
    auto &block = main.getBody().emplaceBlock();
    builder.setInsertionPointToEnd(&block);

    SymbolTable symTable(main);

    createdshostfuncByDim(builder, ctx, symTable);
    auto retop = builder.create<mlir::func::ReturnOp>(builder.getUnknownLoc());
    
  // ------------------------------------------------------------------
  // 4. Look up the symbol anywhere inside the module
  // ------------------------------------------------------------------
    Operation *found = symTable.lookup("receive1");
    if (!found) {
        llvm::errs() << "Symbol @receive1 not found!\n";
   } else {
        llvm::outs() << "receive1 found \n";
        llvm::outs() << "Found: " << found->getName() <<"\n";
   }
    llvm::errs() << m;
   // */
    return m;
}

void dshostmanager::loaddialect(MLIRContext* ctx) {
    ctx->getOrLoadDialect<mlir::func::FuncDialect>();
    ctx->getOrLoadDialect<dshost::dshostdialect>();
    ctx->getOrLoadDialect<mlir::scf::SCFDialect>();
    ctx->getOrLoadDialect<mlir::arith::ArithDialect>();
}
/*
      %data = dataflowmap.create_data {type="i32", dim1=10, dim2 20}
      %coreenginegroup = dataflowmap.dshost_create_core_engine_group {1, 4, "row"}
      %ioengine = dataflowmap.dshost_create_io_engine {0, "shim"}
      %send_port = dataflowmap.configure_port %ioengine {peorioidx=0, dataacces=}  
      %portreceive1 = dataflowmap.configure_port on %{peorioidx = 0, dataacces=}  
      %portreceive2 = dataflowmap.configure_port on %{peorioidx = 1, dataacces=}   
      %receive_group = dataflowmap.create_port_group(%portreceive1, %portreceive2)    
      %broadcast_stream = dataflowmap.create_stream %send_port, %receive_group         
      dataflowmap.push %data, %broadcast_stream {cache_policy = "force_memtile" }
*/
void dshostmanager::createdshostfuncByDim(OpBuilder& builder, MLIRContext* ctx,SymbolTable& symTable) {
        auto location = builder.getUnknownLoc();
        // no region creatation

        // memref<1024xf32>
        auto memrefType = mlir::MemRefType::get({1024}, builder.getF32Type());

        // 1) allocate device memory on host: %gmem = "ds.host.alloc_device_mem"() : memref<1024xf32, 1>
        auto gmemOp = builder.create<dshost::AllocDeviceMemOp>(location, memrefType);
        Value gmem = gmemOp.getResult();

        // 2) get tile handles
        auto shim_handle = builder.create<dshost::GetTileHandleOp>(location,
            /*col=*/builder.getI64IntegerAttr(2),
            /*row=*/builder.getI64IntegerAttr(0)
        ).getResult();

        auto core_A_handle = builder.create<dshost::GetTileHandleOp>(location,
            /*col=*/builder.getI64IntegerAttr(0),
            /*row=*/builder.getI64IntegerAttr(3)
        ).getResult();

        auto core_B_handle = builder.create<dshost::GetTileHandleOp>(location,
            /*col=*/builder.getI64IntegerAttr(1),
            /*row=*/builder.getI64IntegerAttr(3)
        ).getResult();

        // 3) look up stream handles from routing symbols: %stream_A = "ds.host.get_stream_handle"(@my_routes::@route_A)
        auto routeARef = mlir::SymbolRefAttr::get(ctx, "my_routes::route_A");
        auto routeBRef = mlir::SymbolRefAttr::get(ctx, "my_routes::route_B");

        auto streamA = builder.create<dshost::GetStreamHandleOp>(location, routeARef).getResult();
        auto streamB = builder.create<dshost::GetStreamHandleOp>(location, routeBRef).getResult();

        ///*
        // 4) launch DMA: %evt_dma = "dshost::LaunchKernelAsyncOp" on %shim_handle ( %gmem, %stream_A, %stream_B )
        // get the event result type produced by the op
        auto eventType = dshost::EventType::get(ctx);
        auto evt_dma = builder.create<dshost::LaunchKernelAsyncOp>(location,
            eventType,
            ValueRange{shim_handle, gmem, streamA, streamB}
        ).getResult();

        // 5) get packet ids from routinghw dialect
        auto pidA = builder.create<dshost::GetPacketIdOp>(location, routeARef).getResult();
        auto pidB = builder.create<dshost::GetPacketIdOp>(location, routeBRef).getResult();

        // 6) launch kernels asynchronously on core handles
        //    pass kernel symbol and packet id as operands
        auto kernelARef = mlir::SymbolRefAttr::get(ctx, "dskernel_A");
        auto kernelBRef = mlir::SymbolRefAttr::get(ctx, "dskernel_B");

        // callee is an attribute on the op (see extraClassDeclaration)
        auto calleeAttrA = builder.getNamedAttr(dshost::LaunchKernelAsyncOp::getCalleeAttrName(), kernelARef);
        auto evt_A = builder.create<dshost::LaunchKernelAsyncOp>(location,
            eventType,
            ValueRange{core_A_handle, pidA},
            llvm::ArrayRef<mlir::NamedAttribute>{calleeAttrA}
        ).getResult();

        auto calleeAttrB = builder.getNamedAttr(dshost::LaunchKernelAsyncOp::getCalleeAttrName(), kernelBRef);
        auto evt_B = builder.create<dshost::LaunchKernelAsyncOp>(location,
            eventType,
            ValueRange{core_B_handle, pidB},
            llvm::ArrayRef<mlir::NamedAttribute>{calleeAttrB}
        ).getResult();

        // 7) wait on events
        builder.create<dshost::WaitOp>(location, ValueRange{evt_dma, evt_A, evt_B});

        // return from function
        builder.create<mlir::func::ReturnOp>(location);

        return ;
}
