/******************************************************************************
* Copyright (C) 2025 Advanced Micro Devices, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT
******************************************************************************/
#include "dskernelmanager.h"
#include <iostream>

#define GET_TYPEDEF_CLASSES
#define GET_ATTRDEF_CLASSES
#define GET_OP_CLASSES
#define GET_OP_DEFS
//#define GET_OP_LIST
#include "dskerneldialect.cc.inc"
#include "dskernelattr.cc.inc"
#include "dskerneltype.cc.inc"

#include "dskernelop.cc.inc"
//#undef GET_OP_LIST
#undef GET_OP_DEFS

#undef GET_OP_CLASSES
#undef GET_ATTRDEF_CLASSES
#undef GET_TYPEDEF_CLASSES

void dskerneldialect::initialize()  { 
    addOperations<
    #define GET_OP_LIST
    #include "dskernelop.cc.inc"
        >();
    // 如果有 Attr / Type：addAttributes<...>(); addTypes<...>();
     addAttributes<
    #define GET_ATTRDEF_LIST
    #include "dskernelattr.cc.inc"
    >();

        // 3. Types
    addTypes<
    #define GET_TYPEDEF_LIST
    #include "dskerneltype.cc.inc"
    >();
}

// Add implementations for the attribute and type parsers/printers.
// These are required by the vtable for the dialect
#include "mlir/IR/DialectImplementation.h"

void dskerneldialect::printAttribute(Attribute attr, DialectAsmPrinter &p) const {
  // No custom attributes, use default
  llvm_unreachable("unexpected custom attribute");
}

Attribute dskerneldialect::parseAttribute(DialectAsmParser &parser, Type type) const {
  // No custom attributes, use default
  parser.emitError(parser.getCurrentLocation(), "unexpected custom attribute");
  return nullptr;
}

// void dskerneldialect::printType(Type type, DialectAsmPrinter &p) const {
//   if (failed(generatedTypePrinter(type, p))) {
//     llvm_unreachable("unexpected dskernel type");
//   }
// }
//
// Type dskerneldialect::parseType(DialectAsmParser &parser) const {
//   Type result = generatedTypeParser(parser);
//   if (!result) {
//     parser.emitError(parser.getCurrentLocation(), "failed to parse dskernel type");
//   }
//   return result;
// }

/*
void dskerneldialect::printType(Type type, DialectAsmPrinter &printer) const {
    // This is the C++ type generated by TableGen from your TypeDef.
    // Ensure you use the correct name (e.g., DMAPDataType).
    if (isa<dskerneldataType>(type)) {
        // All you need to do is print the mnemonic you defined in TableGen.
        printer << "dskerneldata";
    }
}
//*/


ModuleOp dskernelmanager::ops_test(MLIRContext* ctx, int totalN) {
    const int hwrowused= 4, hwcolused=4;
    OpBuilder builder(ctx);
    mlir::ModuleOp m = ModuleOp::create(builder.getUnknownLoc());
    
    // Set the insertion point at the top level of the module.
    builder.setInsertionPointToStart(m.getBody());

    // Call the helper function to create the FuncOp.
    // The builder will automatically insert it into the module.
    mlir::func::FuncOp kernelFunc = createdskernelfuncByDim(builder, ctx);
    
    // Print the generated module
    llvm::errs() << m;
    return m;
}

void dskernelmanager::loaddialect(MLIRContext* ctx) {
    ctx->getOrLoadDialect<mlir::func::FuncDialect>();
    ctx->getOrLoadDialect<dskernel::dskerneldialect>();
    ctx->getOrLoadDialect<mlir::scf::SCFDialect>();
    ctx->getOrLoadDialect<mlir::arith::ArithDialect>();
    ctx->getOrLoadDialect<mlir::memref::MemRefDialect>();
}
/*
      %data = dataflowmap.create_data {type="i32", dim1=10, dim2 20}
      %coreenginegroup = dataflowmap.create_core_engine_group {1, 4, "row"}
      %ioengine = dataflowmap.create_io_engine {0, "shim"}
      %send_port = dataflowmap.configure_port %ioengine {peorioidx=0, dataacces=}  
      %portreceive1 = dataflowmap.configure_port on %{peorioidx = 0, dataacces=}  
      %portreceive2 = dataflowmap.configure_port on %{peorioidx = 1, dataacces=}   
      %receive_group = dataflowmap.create_port_group(%portreceive1, %portreceive2)    
      %broadcast_stream = dataflowmap.create_stream %send_port, %receive_group         
      dataflowmap.push %data, %broadcast_stream {cache_policy = "force_memtile" }
*/


mlir::func::FuncOp dskernelmanager::createdskernelfuncByDim(OpBuilder &builder, MLIRContext *ctx) {
  auto location = builder.getUnknownLoc();
 
  // 1. Define the function type: (i32) -> ()
  auto funcType = builder.getFunctionType({builder.getI32Type()}, {});

  // 2. Create the func.func operation.
  auto funcOp = builder.create<mlir::func::FuncOp>(location, "dskernel_coretile_compute", funcType);

  // 3. Create the function's entry block and set the insertion point inside it.
  //    This is the correct way to create the entry block for a function.
  Block *entryBlock = funcOp.addEntryBlock();
  builder.setInsertionPointToStart(entryBlock);

  // 4. Get the packet id from the function's argument.
  Value my_packet_id = entryBlock->getArgument(0);

  // --- Function Body ---
  // (The rest of your logic is commented out, so I will leave it that way)
  /*
  auto memrefType = mlir::MemRefType::get({256}, builder.getF32Type());
  auto ping = builder.create<mlir::memref::AllocaOp>(location, memrefType);
  // ... etc ...
  */
  // --- End of Function Body ---
  
  // 5. Add a return op at the end of the function.
  builder.create<mlir::func::ReturnOp>(location);

  // 6. Return the created function.
  return funcOp;
}

// Add these includes at the top if not already present
#include "mlir/Interfaces/FunctionImplementation.h"

// Add after the initialize() function:

::mlir::ParseResult dskernel::FuncOp::parse(::mlir::OpAsmParser &parser, ::mlir::OperationState &result) {
  auto buildFuncType = [](Builder &builder, ArrayRef<Type> argTypes, ArrayRef<Type> results,
                          function_interface_impl::VariadicFlag,
                          std::string &) {
    return builder.getFunctionType(argTypes, results);
  };

  StringAttr functionTypeAttr = parser.getBuilder().getStringAttr("function_type");
  StringAttr argAttrsAttr = parser.getBuilder().getStringAttr("arg_attrs");
  StringAttr resAttrsAttr = parser.getBuilder().getStringAttr("res_attrs");

  return function_interface_impl::parseFunctionOp(
      parser, result, /*allowVariadic=*/false,
      functionTypeAttr, buildFuncType,
      argAttrsAttr, resAttrsAttr);
}

void dskernel::FuncOp::print(::mlir::OpAsmPrinter &p) {
  StringAttr functionTypeAttr = StringAttr::get(getContext(), "function_type");
  StringAttr argAttrsAttr = StringAttr::get(getContext(), "arg_attrs");
  StringAttr resAttrsAttr = StringAttr::get(getContext(), "res_attrs");
  printf("--- dskernel::FuncOp::print----\n");
  function_interface_impl::printFunctionOp(
      p, *this, /*isVariadic=*/false,
      functionTypeAttr, argAttrsAttr, resAttrsAttr);
}
