/******************************************************************************
* Copyright (C) 2025 Advanced Micro Devices, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT
******************************************************************************/
#include "dskernelmanager.h"
#include <iostream>

#define GET_TYPEDEF_CLASSES
#define GET_ATTRDEF_CLASSES
#define GET_OP_CLASSES
#define GET_OP_DEFS
//#define GET_OP_LIST
#include "dskerneldialect.cc.inc"
#include "dskernelattr.cc.inc"
#include "dskerneltype.cc.inc"

#include "dskernelop.cc.inc"
//#undef GET_OP_LIST
#undef GET_OP_DEFS

#undef GET_OP_CLASSES
#undef GET_ATTRDEF_CLASSES
#undef GET_TYPEDEF_CLASSES

void dskerneldialect::initialize()  { 
    addOperations<
    #define GET_OP_LIST
    #include "dskernelop.cc.inc"
        >();
    // 如果有 Attr / Type：addAttributes<...>(); addTypes<...>();
     addAttributes<
    #define GET_ATTRDEF_LIST
    #include "dskernelattr.cc.inc"
    >();

        // 3. Types
    addTypes<
    #define GET_TYPEDEF_LIST
    #include "dskerneltype.cc.inc"
    >();
}

// Add implementations for the attribute and type parsers/printers.
// These are required by the vtable for the dialect
#include "mlir/IR/DialectImplementation.h"

void dskerneldialect::printAttribute(Attribute attr, DialectAsmPrinter &p) const {
  // No custom attributes, use default
  llvm_unreachable("unexpected custom attribute");
}

Attribute dskerneldialect::parseAttribute(DialectAsmParser &parser, Type type) const {
  // No custom attributes, use default
  parser.emitError(parser.getCurrentLocation(), "unexpected custom attribute");
  return nullptr;
}

// void dskerneldialect::printType(Type type, DialectAsmPrinter &p) const {
//   if (failed(generatedTypePrinter(type, p))) {
//     llvm_unreachable("unexpected dskernel type");
//   }
// }
//
// Type dskerneldialect::parseType(DialectAsmParser &parser) const {
//   Type result = generatedTypeParser(parser);
//   if (!result) {
//     parser.emitError(parser.getCurrentLocation(), "failed to parse dskernel type");
//   }
//   return result;
// }

/*
void dskerneldialect::printType(Type type, DialectAsmPrinter &printer) const {
    // This is the C++ type generated by TableGen from your TypeDef.
    // Ensure you use the correct name (e.g., DMAPDataType).
    if (isa<dskerneldataType>(type)) {
        // All you need to do is print the mnemonic you defined in TableGen.
        printer << "dskerneldata";
    }
}
//*/


ModuleOp dskernelmanager::ops_test(MLIRContext* ctx, int totalN) {
    const int hwrowused= 4, hwcolused=4;
    OpBuilder builder(ctx);
    mlir::ModuleOp m = ModuleOp::create(builder.getUnknownLoc());
    
    // Create function type with one i32 argument (packet id) and no return type
    auto functype = builder.getFunctionType({builder.getI32Type()}, {});
    
    dskernel::FuncOp main = builder.create<dskernel::FuncOp>(builder.getUnknownLoc(), "main", functype);
    m.push_back(main);
    
    // Create entry block with the i32 argument
    auto &block = main.getBody().emplaceBlock();
    block.addArgument(builder.getI32Type(), builder.getUnknownLoc());
    builder.setInsertionPointToEnd(&block);

    SymbolTable symTable(main);

    createdskernelfuncByDim(builder, ctx, symTable);
    auto retop = builder.create<mlir::func::ReturnOp>(builder.getUnknownLoc());
    
    // Print the generated module
    llvm::errs() << m;
    return m;
}

void dskernelmanager::loaddialect(MLIRContext* ctx) {
    ctx->getOrLoadDialect<mlir::func::FuncDialect>();
    ctx->getOrLoadDialect<dskernel::dskerneldialect>();
    ctx->getOrLoadDialect<mlir::scf::SCFDialect>();
    ctx->getOrLoadDialect<mlir::arith::ArithDialect>();
    ctx->getOrLoadDialect<mlir::memref::MemRefDialect>();
}
/*
      %data = dataflowmap.create_data {type="i32", dim1=10, dim2 20}
      %coreenginegroup = dataflowmap.create_core_engine_group {1, 4, "row"}
      %ioengine = dataflowmap.create_io_engine {0, "shim"}
      %send_port = dataflowmap.configure_port %ioengine {peorioidx=0, dataacces=}  
      %portreceive1 = dataflowmap.configure_port on %{peorioidx = 0, dataacces=}  
      %portreceive2 = dataflowmap.configure_port on %{peorioidx = 1, dataacces=}   
      %receive_group = dataflowmap.create_port_group(%portreceive1, %portreceive2)    
      %broadcast_stream = dataflowmap.create_stream %send_port, %receive_group         
      dataflowmap.push %data, %broadcast_stream {cache_policy = "force_memtile" }
*/


void dskernelmanager::createdskernelfuncByDim(OpBuilder &builder, MLIRContext *ctx, SymbolTable &symTable) {
  auto location = builder.getUnknownLoc();
 
  // Get the current block - this should be the function's entry block
  Block *currentBlock = builder.getBlock();
  if (!currentBlock || currentBlock->getNumArguments() == 0) {
    llvm::errs() << "Error: Entry block has no arguments!\n";
    return;
  }
  //return;
  // Get the packet id argument from the function's entry block
  Value my_packet_id = currentBlock->getArgument(0);

  // %ping = memref.alloca() : memref<256xf32, "SHARED">
  auto memrefType = mlir::MemRefType::get({256}, builder.getF32Type());
  auto ping = builder.create<mlir::memref::AllocaOp>(location, memrefType);
  auto pong = builder.create<mlir::memref::AllocaOp>(location, memrefType);

  // %lock_dma = "dskernel.lock_init"(1)
  auto lock_dma = builder.create<dskernel::LockInitOp>(location, dskernel::lockType::get(ctx), builder.getI64IntegerAttr(1));
  // %lock_compute = "dskernel.lock_init"(0)
  auto lock_compute = builder.create<dskernel::LockInitOp>(location, dskernel::lockType::get(ctx), builder.getI64IntegerAttr(0));

  // "dskernel.launch_dma_s2m_loop"(%ping, %pong) { ... }
  auto dmaLoop = builder.create<dskernel::LaunchDmaS2MLoopOp>(
      location, ping.getResult(), pong.getResult(), my_packet_id, lock_dma.getResult(), lock_compute.getResult());
  

  // scf.for %i = 0 to 4 { ... }
  auto lowerBound = builder.create<mlir::arith::ConstantIndexOp>(location, 0);
  auto upperBound = builder.create<mlir::arith::ConstantIndexOp>(location, 4);
  auto step = builder.create<mlir::arith::ConstantIndexOp>(location, 1);

  auto forLoop = builder.create<mlir::scf::ForOp>(location, lowerBound.getResult(), upperBound.getResult(), step.getResult());
  builder.setInsertionPointToStart(forLoop.getBody());

  Value iv = forLoop.getInductionVar();

  // "dskernel.acquire_lock"(%lock_compute, %i+1)
  auto one_i32 = builder.create<mlir::arith::ConstantOp>(location, builder.getI32IntegerAttr(1));
  // The induction variable is index type, cast to i32 if needed for the lock op.
  Value iv_i32 = builder.create<mlir::arith::IndexCastOp>(location, builder.getI32Type(), iv).getResult();
  Value token_compute = builder.create<mlir::arith::AddIOp>(location, iv_i32, one_i32.getResult()).getResult();
  builder.create<dskernel::AcquireLockOp>(location, lock_compute.getResult(), token_compute);

  // "core.compute"(...) - Placeholder for a compute operation
  // builder.create<core::ComputeOp>(location, ...);

  // "dskernel.release_lock"(%lock_dma, %i+1)
  builder.create<dskernel::ReleaseLockOp>(location, lock_dma.getResult(), token_compute);

  // Set insertion point back to after the loop
  builder.setInsertionPointAfter(forLoop);
}

// Add these includes at the top if not already present
#include "mlir/Interfaces/FunctionImplementation.h"

// Add after the initialize() function:

::mlir::ParseResult dskernel::FuncOp::parse(::mlir::OpAsmParser &parser, ::mlir::OperationState &result) {
  auto buildFuncType = [](Builder &builder, ArrayRef<Type> argTypes, ArrayRef<Type> results,
                          function_interface_impl::VariadicFlag,
                          std::string &) {
    return builder.getFunctionType(argTypes, results);
  };

  StringAttr functionTypeAttr = parser.getBuilder().getStringAttr("function_type");
  StringAttr argAttrsAttr = parser.getBuilder().getStringAttr("arg_attrs");
  StringAttr resAttrsAttr = parser.getBuilder().getStringAttr("res_attrs");

  return function_interface_impl::parseFunctionOp(
      parser, result, /*allowVariadic=*/false,
      functionTypeAttr, buildFuncType,
      argAttrsAttr, resAttrsAttr);
}

void dskernel::FuncOp::print(::mlir::OpAsmPrinter &p) {
  StringAttr functionTypeAttr = StringAttr::get(getContext(), "function_type");
  StringAttr argAttrsAttr = StringAttr::get(getContext(), "arg_attrs");
  StringAttr resAttrsAttr = StringAttr::get(getContext(), "res_attrs");
  printf("--- dskernel::FuncOp::print----\n");
  function_interface_impl::printFunctionOp(
      p, *this, /*isVariadic=*/false,
      functionTypeAttr, argAttrsAttr, resAttrsAttr);
}
