/******************************************************************************
* Copyright (C) 2025 Advanced Micro Devices, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT
******************************************************************************/
#include "dmapmanager.h"
#include <iostream>

#define GET_TYPEDEF_CLASSES
#define GET_ATTRDEF_CLASSES
#define GET_OP_CLASSES
#define GET_OP_DEFS
//#define GET_OP_LIST
#include "dmapdialect.cc.inc"
#include "dmapattr.cc.inc"
#include "dmaptype.cc.inc"

#include "dmapop.cc.inc"
//#undef GET_OP_LIST
#undef GET_OP_DEFS

#undef GET_OP_CLASSES
#undef GET_ATTRDEF_CLASSES
#undef GET_TYPEDEF_CLASSES

void dmapdialect::initialize()  { 
    addOperations<
    #define GET_OP_LIST
    #include "dmapop.cc.inc"
        >();
    // 如果有 Attr / Type：addAttributes<...>(); addTypes<...>();
     addAttributes<
    #define GET_ATTRDEF_LIST
    #include "dmapattr.cc.inc"
    >();

        // 3. Types
    addTypes<
    #define GET_TYPEDEF_LIST
    #include "dmaptype.cc.inc"
    >();
}

/*
void dmapdialect::printType(Type type, DialectAsmPrinter &printer) const {
    // This is the C++ type generated by TableGen from your TypeDef.
    // Ensure you use the correct name (e.g., DMAPDataType).
    if (isa<dmapdataType>(type)) {
        // All you need to do is print the mnemonic you defined in TableGen.
        printer << "dmapdata";
    }
}
//*/


ModuleOp dmapmanager::ops_test(MLIRContext* ctx, int totalN) {
    const int hwrowused= 4, hwcolused=4;
    OpBuilder builder(ctx);
    mlir::ModuleOp m = ModuleOp::create(builder.getUnknownLoc());
    //auto func = createdmapfuncByDim(ctx, true);
    //m.push_back(func);
    auto functype = builder.getFunctionType({},{});
    
    mlir::func::FuncOp main = builder.create<func::FuncOp>(builder.getUnknownLoc(), "main", functype);
    
    auto block = main.addEntryBlock();
    builder.setInsertionPointToEnd(block);
    createdmapfuncByDim(builder, ctx);
    auto retop = builder.create<mlir::func::ReturnOp>(builder.getUnknownLoc());
    m.push_back(main);
    llvm::errs() << m;
    return m;
}

void dmapmanager::loaddialect(MLIRContext* ctx) {
    ctx->getOrLoadDialect<mlir::func::FuncDialect>();
    ctx->getOrLoadDialect<dmap::dmapdialect>();
    ctx->getOrLoadDialect<mlir::scf::SCFDialect>();
    ctx->getOrLoadDialect<mlir::arith::ArithDialect>();
}
/*
      %data = dataflowmap.create_data {type="i32", dim1=10, dim2 20}
      %coreenginegroup = dataflowmap.dmap_create_core_engine_group {1, 4, "row"}
      %ioengine = dataflowmap.dmap_create_io_engine {0, "shim"}
      %send_port = dataflowmap.configure_port %ioengine {peorioidx=0, dataacces=}  
      %portreceive1 = dataflowmap.configure_port on %{peorioidx = 0, dataacces=}  
      %portreceive2 = dataflowmap.configure_port on %{peorioidx = 1, dataacces=}   
      %receive_group = dataflowmap.create_port_group(%portreceive1, %portreceive2)    
      %broadcast_stream = dataflowmap.create_stream %send_port, %receive_group         
      dataflowmap.push %data, %broadcast_stream {cache_policy = "force_memtile" }
*/
void dmapmanager::createdmapfuncByDim(OpBuilder& builder, MLIRContext* ctx) {
        auto location = builder.getUnknownLoc();
        // no region creatation
    ///*   
        mlir::SmallVector<mlir::Attribute, 4> shapeElems;
        shapeElems.push_back(builder.getI64IntegerAttr(16));
        shapeElems.push_back(builder.getI64IntegerAttr(16));
        mlir::ArrayAttr shapettr = mlir::ArrayAttr::get(ctx, shapeElems);
        mlir::Type elementType = builder.getF32Type();
        mlir::Type myDataHandleType = dmap::dmapdataType::get(ctx);
        auto data = builder.create<create_data>(builder.getUnknownLoc(),  myDataHandleType, shapettr, elementType); 
        mlir::Type pgeout = dmap::dmacoreenginegroupType::get(ctx);
        auto peg = builder.create<create_core_engine_group>(builder.getUnknownLoc(),  pgeout, 0, 4,"row"); 
        mlir::Type ioout = dmap::dmapioenginetypeType::get(ctx);
        auto io = builder.create<create_io_engine>(builder.getUnknownLoc(),  ioout, 0,"shim"); 
        //config port
        auto portret = dmap::dmapportType::get(ctx);
        auto dataaccesspattern = dmap::dataaccesspatternAttr::get(ctx, builder.getStringAttr("SEND"), 16, 1, 1);
        // create a port configuration
        //port_configure_create
        
        mlir::Type portconfig = dmap::dmapportconfigType::get(ctx);
        std::string symbolName = "forwarding_config";
        auto pf = builder.create<dmap::port_configure_create>(builder.getUnknownLoc(), portconfig, symbolName, dataaccesspattern);
        mlir::SymbolRefAttr symbolRef = mlir::SymbolRefAttr::get(ctx,symbolName);
        auto useOp = builder.create<dmap::UseSymbolOp>(builder.getUnknownLoc(), symbolRef);
        //config io port
        auto cport = builder.create<configure_port>(builder.getUnknownLoc(),  portret, io.getResult(),0, dataaccesspattern);
        //config core port
        auto dataaccesspattern1 = dmap::dataaccesspatternAttr::get(ctx, builder.getStringAttr("RECEIVE"), 16, 1, 1);
        auto cport0 = builder.create<configure_port>(builder.getUnknownLoc(),  portret, peg.getResult(),0, dataaccesspattern1);
        auto cport1 = builder.create<configure_port>(builder.getUnknownLoc(),  portret, peg.getResult(),1, dataaccesspattern1); 
        auto cport2 = builder.create<configure_port>(builder.getUnknownLoc(),  portret, peg.getResult(),2, dataaccesspattern1); 
        auto cport3 = builder.create<configure_port>(builder.getUnknownLoc(),  portret, peg.getResult(),3, dataaccesspattern1);  
        //create port group
        mlir::SmallVector<mlir::Value, 4> portlist;
        portlist.push_back(cport0.getResult());
        portlist.push_back(cport1.getResult());
        portlist.push_back(cport2.getResult());
        portlist.push_back(cport3.getResult());

        auto portg = dmap::dmapportgroupType::get(ctx);
        auto portgroup = builder.create<createport_group>(builder.getUnknownLoc(),  ioout, portlist);  
        return ;//func;
}
