/******************************************************************************
* Copyright (C) 2025 Advanced Micro Devices, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT
******************************************************************************/
#include "dmapmanager.h"
#include <iostream>

#define GET_TYPEDEF_CLASSES
#define GET_ATTRDEF_CLASSES
#define GET_OP_CLASSES
#define GET_OP_DEFS
//#define GET_OP_LIST
#include "dmapdialect.cc.inc"
#include "dmapattr.cc.inc"
#include "dmaptype.cc.inc"

#include "dmapop.cc.inc"
//#undef GET_OP_LIST
#undef GET_OP_DEFS

#undef GET_OP_CLASSES
#undef GET_ATTRDEF_CLASSES
#undef GET_TYPEDEF_CLASSES

void dmapdialect::initialize()  { 
    addOperations<
    #define GET_OP_LIST
    #include "dmapop.cc.inc"
        >();
    // 如果有 Attr / Type：addAttributes<...>(); addTypes<...>();
     addAttributes<
    #define GET_ATTRDEF_LIST
    #include "dmapattr.cc.inc"
    >();

        // 3. Types
    addTypes<
    #define GET_TYPEDEF_LIST
    #include "dmaptype.cc.inc"
    >();
}

/*
void dmapdialect::printType(Type type, DialectAsmPrinter &printer) const {
    // This is the C++ type generated by TableGen from your TypeDef.
    // Ensure you use the correct name (e.g., DMAPDataType).
    if (isa<dmapdataType>(type)) {
        // All you need to do is print the mnemonic you defined in TableGen.
        printer << "dmapdata";
    }
}
//*/


ModuleOp dmapmanager::ops_test(MLIRContext* ctx, int totalN) {
    const int hwrowused= 4, hwcolused=4;
    OpBuilder builder(ctx);
    mlir::ModuleOp m = ModuleOp::create(builder.getUnknownLoc());
    //auto func = createdmapfuncByDim(ctx, true);
    //m.push_back(func);
    auto functype = builder.getFunctionType({},{});
    
    mlir::func::FuncOp main = builder.create<func::FuncOp>(builder.getUnknownLoc(), "main", functype);
    
    auto block = main.addEntryBlock();
    builder.setInsertionPointToEnd(block);
    createdmapfuncByDim(builder, ctx);
    auto retop = builder.create<mlir::func::ReturnOp>(builder.getUnknownLoc());
    m.push_back(main);
    llvm::errs() << m;
    return m;
}

void dmapmanager::loaddialect(MLIRContext* ctx) {
    ctx->getOrLoadDialect<mlir::func::FuncDialect>();
    ctx->getOrLoadDialect<dmap::dmapdialect>();
    ctx->getOrLoadDialect<mlir::scf::SCFDialect>();
    ctx->getOrLoadDialect<mlir::arith::ArithDialect>();
}

void dmapmanager::createdmapfuncByDim(OpBuilder& builder, MLIRContext* ctx) {
        auto location = builder.getUnknownLoc();
        // no region creatation
    ///*   
        mlir::SmallVector<mlir::Attribute, 4> shapeElems;

        shapeElems.push_back(builder.getI64IntegerAttr(16));
        shapeElems.push_back(builder.getI64IntegerAttr(16));
        mlir::ArrayAttr shapettr = mlir::ArrayAttr::get(ctx, shapeElems);
        mlir::Type elementType = builder.getF32Type();
        mlir::Type myDataHandleType = dmap::dmapdataType::get(ctx);
        auto data = builder.create<create_data>(builder.getUnknownLoc(),  myDataHandleType, shapettr, elementType); 
        
       
        return ;//func;
}
