/********************************************* Disclaimer *********************************************/
/* This file is generated by aiecompiler 2025.2. */
/* Changes to this file may cause incorrect behavior and will be lost if aiecompiler is invoked again.*/

/************************** Constants/Macros *****************************/
#define HW_GEN                   XAIE_DEV_GEN_AIEML
#define XAIE_NUM_ROWS            11
#define XAIE_NUM_COLS            38
#define XAIE_BASE_ADDR           0x20000000000
#define XAIE_COL_SHIFT           25
#define XAIE_ROW_SHIFT           20
#define XAIE_SHIM_ROW            0
#define XAIE_MEM_TILE_ROW_START  1
#define XAIE_MEM_TILE_NUM_ROWS   2
#define XAIE_AIE_TILE_ROW_START  3
#define XAIE_AIE_TILE_NUM_ROWS   8
#define FOR_WRITE                0
#define FOR_READ                 1

/***************************** Includes *********************************/
#include <fstream>
#include <adf.h>
extern "C"
{
  #include <xaiengine.h>
}

#if defined(__CDO__) || defined(__AIECONTROLCODE__)
#include "adf/adf_api/common_layer/fal_util.h"
#endif

#include "adf/adf_api/AIEControlConfig.h"

XAie_InstDeclare(DevInst, &ConfigPtr);   // Declare global device instance


/************************** Functions/APIs *****************************/
  adf::return_code broadcastConfigForCoreEnable()
  {
	if(!adf::reserveBroadcastchannelForEnablingCores())
	{
		std::cerr << "ERROR: Failed to reserve Broadcast channels for enabling core.\n";
		return adf::return_code::aie_driver_error;
	}

	int driverStatus = AieRC::XAIE_OK;
	driverStatus |= XAie_EventBroadcast(&DevInst, XAie_TileLoc(0, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(0, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(0, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(0, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(0, 1), XAIE_MEM_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(0, 2), XAIE_MEM_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	driverStatus |= XAie_EventBroadcast(&DevInst, XAie_TileLoc(1, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(1, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(1, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(1, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(1, 1), XAIE_MEM_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(1, 2), XAIE_MEM_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	driverStatus |= XAie_EventBroadcast(&DevInst, XAie_TileLoc(2, 0), XAIE_PL_MOD, 7, XAIE_EVENT_BROADCAST_A_8_PL);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(2, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(2, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_A, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(2, 0), XAIE_PL_MOD, XAIE_EVENT_SWITCH_B, 8, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_NORTH);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(2, 1), XAIE_MEM_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(2, 2), XAIE_MEM_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(0, 3), XAIE_CORE_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(0, 3), XAIE_MEM_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_ALL);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(0, 4), XAIE_CORE_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(0, 4), XAIE_MEM_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_ALL);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(0, 5), XAIE_CORE_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(0, 5), XAIE_MEM_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_ALL);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(0, 6), XAIE_CORE_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(0, 6), XAIE_MEM_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_ALL);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(0, 7), XAIE_CORE_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(0, 7), XAIE_MEM_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_ALL);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(1, 3), XAIE_CORE_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(1, 3), XAIE_MEM_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_ALL);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(2, 3), XAIE_CORE_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_SOUTH | XAIE_EVENT_BROADCAST_WEST | XAIE_EVENT_BROADCAST_EAST);
	driverStatus |= XAie_EventBroadcastBlockDir(&DevInst, XAie_TileLoc(2, 3), XAIE_MEM_MOD, XAIE_EVENT_SWITCH_A, 7, XAIE_EVENT_BROADCAST_ALL);
	driverStatus |= XAie_EventBroadcast(&DevInst, XAie_TileLoc(0, 0), XAIE_PL_MOD, 8, XAIE_EVENT_BROADCAST_A_8_PL);
	return (driverStatus == AieRC::XAIE_OK) ? adf::return_code::ok : adf::aie_driver_error;
  }

  bool EG_load_elf(const std::string& work_path, std::vector<std::string>& elfInfoPath)
  {
	#ifdef __PS_INIT_AIE__

	std::string work_dir = (work_path.empty() ?  "/scratch/staff/huaj/aiebr/external/aiebaremetal2/test/test_external_buffer2/Work" : work_path);
	std::cout<<"Loading elfs of graph EG..."<<std::endl;
	if(XAie_LoadElf(&DevInst, XAie_TileLoc(0, 3), (work_dir + "/aie/0_0/Release/0_0").c_str(), XAIE_ENABLE)!=XAIE_OK)
	{
		std::cerr << "ERROR: Failed to load elf for core(0,0)" << std::endl;
		return false;
	}
	if(XAie_LoadElf(&DevInst, XAie_TileLoc(0, 4), (work_dir + "/aie/0_1/Release/0_1").c_str(), XAIE_ENABLE)!=XAIE_OK)
	{
		std::cerr << "ERROR: Failed to load elf for core(0,1)" << std::endl;
		return false;
	}
	if(XAie_LoadElf(&DevInst, XAie_TileLoc(0, 5), (work_dir + "/aie/0_2/Release/0_2").c_str(), XAIE_ENABLE)!=XAIE_OK)
	{
		std::cerr << "ERROR: Failed to load elf for core(0,2)" << std::endl;
		return false;
	}
	if(XAie_LoadElf(&DevInst, XAie_TileLoc(0, 6), (work_dir + "/aie/0_3/Release/0_3").c_str(), XAIE_ENABLE)!=XAIE_OK)
	{
		std::cerr << "ERROR: Failed to load elf for core(0,3)" << std::endl;
		return false;
	}
	#endif

	return true;
  }

  adf::return_code EG_init(const std::string& work_path)
  {

	std::cout<<"Initializing graph EG..."<<std::endl;

	int driverStatus = AieRC::XAIE_OK;

    #ifdef __PS_INIT_AIE__

	std::string work_dir = (work_path.empty() ?  "/scratch/staff/huaj/aiebr/external/aiebaremetal2/test/test_external_buffer2/Work" : work_path);
	// S_EAST_ch2_C0_R0 M_NORTH_ch4_C0_R0 net2

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(0, 3), EAST, 2, NORTH, 4);

	// S_EAST_ch2_C1_R0 M_WEST_ch2_C1_R0 net2

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(1, 3), EAST, 2, WEST, 2);

	// S_EAST_ch3_C0_R0 M_NORTH_ch5_C0_R0 net6

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(0, 3), EAST, 3, NORTH, 5);

	// S_EAST_ch3_C1_R0 M_WEST_ch3_C1_R0 net6

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(1, 3), EAST, 3, WEST, 3);

	// S_MEMTILE_MM2S_DMA_ch0_C2_R1 M_MEMTILE_NORTH_ch4_C2_R1 net2

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(2, 2), DMA, 0, NORTH, 4);

	// S_MEMTILE_MM2S_DMA_ch1_C2_R1 M_MEMTILE_NORTH_ch5_C2_R1 net6

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(2, 2), DMA, 1, NORTH, 5);

	// S_MEMTILE_NORTH_ch3_C0_R0 M_MEMTILE_SOUTH_ch3_C0_R0 net13

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(0, 1), NORTH, 3, SOUTH, 3);

	// S_MEMTILE_NORTH_ch3_C0_R1 M_MEMTILE_SOUTH_ch3_C0_R1 net13

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(0, 2), NORTH, 3, SOUTH, 3);

	// S_MEMTILE_SOUTH_ch4_C2_R0 M_MEMTILE_NORTH_ch4_C2_R0 net0

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(2, 1), SOUTH, 4, NORTH, 4);

	// S_MEMTILE_SOUTH_ch4_C2_R1 M_MEMTILE_S2MM_DMA_ch0_C2_R1 net0

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(2, 2), SOUTH, 4, DMA, 0);

	// S_MEMTILE_SOUTH_ch5_C2_R0 M_MEMTILE_NORTH_ch5_C2_R0 net1

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(2, 1), SOUTH, 5, NORTH, 5);

	// S_MEMTILE_SOUTH_ch5_C2_R1 M_MEMTILE_S2MM_DMA_ch1_C2_R1 net1

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(2, 2), SOUTH, 5, DMA, 1);

	//SLAVE CONFIGURATION FOR SW(0,4)

	// S_MM2S_DMA_ch0_C0_R1->M_SOUTH_ch3_C0_R1 nets: net10 
	driverStatus |= XAie_StrmPktSwSlaveSlotEnable(&DevInst, XAie_TileLoc(0, 4), DMA, 0, 0, {.PktId=0, .PktType=0}, 0x1f, 0, 0);

	//MASTER CONFIGURATION FOR SW(0,4)
	//configure master M_SOUTH_ch3_C0_R1 nets: net10 net11 net12 net13 

	driverStatus |= XAie_StrmPktSwMstrPortEnable(&DevInst, XAie_TileLoc(0, 4), SOUTH, 3, XAIE_SS_PKT_DROP_HEADER, 0, 0x1);


	//SLAVE CONFIGURATION FOR SW(0,5)

	// S_MM2S_DMA_ch0_C0_R2->M_SOUTH_ch3_C0_R2 nets: net11 
	driverStatus |= XAie_StrmPktSwSlaveSlotEnable(&DevInst, XAie_TileLoc(0, 5), DMA, 0, 0, {.PktId=1, .PktType=0}, 0x1f, 0, 0);

	//MASTER CONFIGURATION FOR SW(0,5)
	//configure master M_SOUTH_ch3_C0_R2 nets: net11 net12 net13 

	driverStatus |= XAie_StrmPktSwMstrPortEnable(&DevInst, XAie_TileLoc(0, 5), SOUTH, 3, XAIE_SS_PKT_DONOT_DROP_HEADER, 0, 0x1);


	//SLAVE CONFIGURATION FOR SW(0,6)

	// S_MM2S_DMA_ch0_C0_R3->M_SOUTH_ch3_C0_R3 nets: net12 
	driverStatus |= XAie_StrmPktSwSlaveSlotEnable(&DevInst, XAie_TileLoc(0, 6), DMA, 0, 0, {.PktId=2, .PktType=0}, 0x1f, 0, 0);

	//MASTER CONFIGURATION FOR SW(0,6)
	//configure master M_SOUTH_ch3_C0_R3 nets: net12 net13 

	driverStatus |= XAie_StrmPktSwMstrPortEnable(&DevInst, XAie_TileLoc(0, 6), SOUTH, 3, XAIE_SS_PKT_DONOT_DROP_HEADER, 0, 0x1);


	// S_MM2S_DMA_ch0_C0_R4 M_SOUTH_ch3_C0_R4 net13

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(0, 7), DMA, 0, SOUTH, 3);

	// S_NORTH_ch3_C0_R0 M_SOUTH_ch3_C0_R0 net13

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(0, 3), NORTH, 3, SOUTH, 3);

	//SLAVE CONFIGURATION FOR SW(0,4)

	// S_NORTH_ch3_C0_R1->M_SOUTH_ch3_C0_R1 nets: net11 net12 net13 
	driverStatus |= XAie_StrmPktSwSlaveSlotEnable(&DevInst, XAie_TileLoc(0, 4), NORTH, 3, 0, {.PktId=0, .PktType=0}, 0x0, 0, 0);
	//SLAVE CONFIGURATION FOR SW(0,5)

	// S_NORTH_ch3_C0_R2->M_SOUTH_ch3_C0_R2 nets: net12 net13 
	driverStatus |= XAie_StrmPktSwSlaveSlotEnable(&DevInst, XAie_TileLoc(0, 5), NORTH, 3, 0, {.PktId=0, .PktType=0}, 0x0, 0, 0);
	//SLAVE CONFIGURATION FOR SW(0,6)

	// S_NORTH_ch3_C0_R3->M_SOUTH_ch3_C0_R3 nets: net13 
	driverStatus |= XAie_StrmPktSwSlaveSlotEnable(&DevInst, XAie_TileLoc(0, 6), NORTH, 3, 0, {.PktId=3, .PktType=0}, 0x1f, 0, 0);
	// S_SHIM_NORTH_ch3_C0 M_SHIM_EAST_ch3_C0 net13

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(0, 0), NORTH, 3, EAST, 3);

	// S_SHIM_SOUTH_ch3_C2 M_SHIM_NORTH_ch4_C2 net0

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(2, 0), SOUTH, 3, NORTH, 4);

	// S_SHIM_SOUTH_ch7_C2 M_SHIM_NORTH_ch5_C2 net1

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(2, 0), SOUTH, 7, NORTH, 5);

	// S_SHIM_WEST_ch3_C1 M_SHIM_EAST_ch3_C1 net13

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(1, 0), WEST, 3, EAST, 3);

	// S_SHIM_WEST_ch3_C2 M_SHIM_SOUTH_ch2_C2 net13

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(2, 0), WEST, 3, SOUTH, 2);

	// S_SOUTH_ch4_C0_R1 M_NORTH_ch4_C0_R1 net2

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(0, 4), SOUTH, 4, NORTH, 4);

	// S_SOUTH_ch4_C0_R1 M_S2MM_DMA_ch0_C0_R1 net2

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(0, 4), SOUTH, 4, DMA, 0);

	// S_SOUTH_ch4_C0_R2 M_NORTH_ch4_C0_R2 net2

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(0, 5), SOUTH, 4, NORTH, 4);

	// S_SOUTH_ch4_C0_R2 M_S2MM_DMA_ch0_C0_R2 net2

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(0, 5), SOUTH, 4, DMA, 0);

	// S_SOUTH_ch4_C0_R3 M_NORTH_ch4_C0_R3 net2

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(0, 6), SOUTH, 4, NORTH, 4);

	// S_SOUTH_ch4_C0_R3 M_S2MM_DMA_ch0_C0_R3 net2

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(0, 6), SOUTH, 4, DMA, 0);

	// S_SOUTH_ch4_C0_R4 M_S2MM_DMA_ch0_C0_R4 net2

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(0, 7), SOUTH, 4, DMA, 0);

	// S_SOUTH_ch4_C2_R0 M_WEST_ch2_C2_R0 net2

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(2, 3), SOUTH, 4, WEST, 2);

	// S_SOUTH_ch5_C0_R1 M_NORTH_ch5_C0_R1 net6

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(0, 4), SOUTH, 5, NORTH, 5);

	// S_SOUTH_ch5_C0_R1 M_S2MM_DMA_ch1_C0_R1 net6

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(0, 4), SOUTH, 5, DMA, 1);

	// S_SOUTH_ch5_C0_R2 M_NORTH_ch5_C0_R2 net6

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(0, 5), SOUTH, 5, NORTH, 5);

	// S_SOUTH_ch5_C0_R2 M_S2MM_DMA_ch1_C0_R2 net6

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(0, 5), SOUTH, 5, DMA, 1);

	// S_SOUTH_ch5_C0_R3 M_NORTH_ch5_C0_R3 net6

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(0, 6), SOUTH, 5, NORTH, 5);

	// S_SOUTH_ch5_C0_R3 M_S2MM_DMA_ch1_C0_R3 net6

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(0, 6), SOUTH, 5, DMA, 1);

	// S_SOUTH_ch5_C0_R4 M_S2MM_DMA_ch1_C0_R4 net6

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(0, 7), SOUTH, 5, DMA, 1);

	// S_SOUTH_ch5_C2_R0 M_WEST_ch3_C2_R0 net6

	driverStatus |= XAie_StrmConnCctEnable(&DevInst, XAie_TileLoc(2, 3), SOUTH, 5, WEST, 3);

	driverStatus |= XAie_StrmPktSwSlavePortEnable(&DevInst, XAie_TileLoc(0, 4), DMA, 0);

	driverStatus |= XAie_StrmPktSwSlavePortEnable(&DevInst, XAie_TileLoc(0, 5), DMA, 0);

	driverStatus |= XAie_StrmPktSwSlavePortEnable(&DevInst, XAie_TileLoc(0, 6), DMA, 0);

	driverStatus |= XAie_StrmPktSwSlavePortEnable(&DevInst, XAie_TileLoc(0, 4), NORTH, 3);

	driverStatus |= XAie_StrmPktSwSlavePortEnable(&DevInst, XAie_TileLoc(0, 5), NORTH, 3);

	driverStatus |= XAie_StrmPktSwSlavePortEnable(&DevInst, XAie_TileLoc(0, 6), NORTH, 3);


	std::cout<<"Resetting cores of graph EG..."<<std::endl;
	driverStatus |= XAie_CoreReset(&DevInst, XAie_TileLoc(0, 3));
	driverStatus |= XAie_CoreUnreset(&DevInst, XAie_TileLoc(0, 3));
	driverStatus |= XAie_CoreReset(&DevInst, XAie_TileLoc(0, 4));
	driverStatus |= XAie_CoreUnreset(&DevInst, XAie_TileLoc(0, 4));
	driverStatus |= XAie_CoreReset(&DevInst, XAie_TileLoc(0, 5));
	driverStatus |= XAie_CoreUnreset(&DevInst, XAie_TileLoc(0, 5));
	driverStatus |= XAie_CoreReset(&DevInst, XAie_TileLoc(0, 6));
	driverStatus |= XAie_CoreUnreset(&DevInst, XAie_TileLoc(0, 6));
	//Connect mux stream id 3 to shim DMA. 
	driverStatus |= XAie_EnableShimDmaToAieStrmPort(&DevInst, XAie_TileLoc(2, 0), 3);
	//Connect demux stream id 2 to shim DMA. 
	driverStatus |= XAie_EnableAieToShimDmaStrmPort(&DevInst, XAie_TileLoc(2, 0), 2);
	//Connect mux stream id 7 to shim DMA. 
	driverStatus |= XAie_EnableShimDmaToAieStrmPort(&DevInst, XAie_TileLoc(2, 0), 7);

	std::cout<<"Configuring DMAs of graph EG..."<<std::endl;

	//Setting lock initial value for EG.conv[0].in[0]
	driverStatus |= XAie_LockSetValue(&DevInst, XAie_TileLoc(0, 4), XAie_LockInit(0, 2));

	//Setting buffer buf0 of EG.conv[0].in[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 4));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0xfb40, 588);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(0, -1), XAie_LockInit(1, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 1, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 4), 0);
	}

	//Setting buffer buf0d of EG.conv[0].in[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 4));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0x4000, 588);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(0, -1), XAie_LockInit(1, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 0, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 4), 1);
	}
	{
		driverStatus |= XAie_DmaChannelSetStartQueue(&DevInst, XAie_TileLoc(0, 4), 0, DMA_S2MM, 0, 1, XAIE_DISABLE);
	}

	//Setting lock initial value for EG.conv[0].in[1]
	driverStatus |= XAie_LockSetValue(&DevInst, XAie_TileLoc(0, 4), XAie_LockInit(2, 2));

	//Setting buffer buf4 of EG.conv[0].in[1]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 4));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0x9b40, 588);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(2, -1), XAie_LockInit(3, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 3, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 4), 2);
	}

	//Setting buffer buf4d of EG.conv[0].in[1]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 4));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0xfda0, 588);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(2, -1), XAie_LockInit(3, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 2, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 4), 3);
	}
	{
		driverStatus |= XAie_DmaChannelSetStartQueue(&DevInst, XAie_TileLoc(0, 4), 1, DMA_S2MM, 2, 1, XAIE_DISABLE);
	}

	//Setting lock initial value for EG.conv[1].in[0]
	driverStatus |= XAie_LockSetValue(&DevInst, XAie_TileLoc(0, 5), XAie_LockInit(0, 2));

	//Setting buffer buf1 of EG.conv[1].in[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 5));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0xbd80, 588);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(0, -1), XAie_LockInit(1, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 1, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 5), 0);
	}

	//Setting buffer buf1d of EG.conv[1].in[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 5));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0xc020, 588);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(0, -1), XAie_LockInit(1, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 0, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 5), 1);
	}
	{
		driverStatus |= XAie_DmaChannelSetStartQueue(&DevInst, XAie_TileLoc(0, 5), 0, DMA_S2MM, 0, 1, XAIE_DISABLE);
	}

	//Setting lock initial value for EG.conv[1].in[1]
	driverStatus |= XAie_LockSetValue(&DevInst, XAie_TileLoc(0, 5), XAie_LockInit(2, 2));

	//Setting buffer buf5 of EG.conv[1].in[1]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 5));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0x7d80, 588);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(2, -1), XAie_LockInit(3, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 3, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 5), 2);
	}

	//Setting buffer buf5d of EG.conv[1].in[1]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 5));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0x3da0, 588);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(2, -1), XAie_LockInit(3, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 2, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 5), 3);
	}
	{
		driverStatus |= XAie_DmaChannelSetStartQueue(&DevInst, XAie_TileLoc(0, 5), 1, DMA_S2MM, 2, 1, XAIE_DISABLE);
	}

	//Setting lock initial value for EG.conv[2].in[0]
	driverStatus |= XAie_LockSetValue(&DevInst, XAie_TileLoc(0, 6), XAie_LockInit(0, 2));

	//Setting buffer buf2 of EG.conv[2].in[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 6));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0x8020, 588);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(0, -1), XAie_LockInit(1, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 1, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 6), 0);
	}

	//Setting buffer buf2d of EG.conv[2].in[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 6));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0x3da0, 588);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(0, -1), XAie_LockInit(1, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 0, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 6), 1);
	}
	{
		driverStatus |= XAie_DmaChannelSetStartQueue(&DevInst, XAie_TileLoc(0, 6), 0, DMA_S2MM, 0, 1, XAIE_DISABLE);
	}

	//Setting lock initial value for EG.conv[2].in[1]
	driverStatus |= XAie_LockSetValue(&DevInst, XAie_TileLoc(0, 6), XAie_LockInit(2, 2));

	//Setting buffer buf6 of EG.conv[2].in[1]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 6));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0x7da0, 588);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(2, -1), XAie_LockInit(3, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 3, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 6), 2);
	}

	//Setting buffer buf6d of EG.conv[2].in[1]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 6));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0xfda0, 588);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(2, -1), XAie_LockInit(3, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 2, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 6), 3);
	}
	{
		driverStatus |= XAie_DmaChannelSetStartQueue(&DevInst, XAie_TileLoc(0, 6), 1, DMA_S2MM, 2, 1, XAIE_DISABLE);
	}

	//Setting lock initial value for EG.conv[3].in[0]
	driverStatus |= XAie_LockSetValue(&DevInst, XAie_TileLoc(0, 7), XAie_LockInit(0, 2));

	//Setting buffer buf3 of EG.conv[3].in[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 7));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0x7da0, 588);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(0, -1), XAie_LockInit(1, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 1, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 7), 0);
	}

	//Setting buffer buf3d of EG.conv[3].in[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 7));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0x3da0, 588);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(0, -1), XAie_LockInit(1, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 0, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 7), 1);
	}
	{
		driverStatus |= XAie_DmaChannelSetStartQueue(&DevInst, XAie_TileLoc(0, 7), 0, DMA_S2MM, 0, 1, XAIE_DISABLE);
	}

	//Setting lock initial value for EG.conv[3].in[1]
	driverStatus |= XAie_LockSetValue(&DevInst, XAie_TileLoc(0, 7), XAie_LockInit(2, 2));

	//Setting buffer buf7 of EG.conv[3].in[1]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 7));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0xbda0, 588);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(2, -1), XAie_LockInit(3, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 3, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 7), 2);
	}

	//Setting buffer buf7d of EG.conv[3].in[1]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 7));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0xc020, 588);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(2, -1), XAie_LockInit(3, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 2, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 7), 3);
	}
	{
		driverStatus |= XAie_DmaChannelSetStartQueue(&DevInst, XAie_TileLoc(0, 7), 1, DMA_S2MM, 2, 1, XAIE_DISABLE);
	}

	//Setting lock initial value for EG.conv[0].out[0]
	driverStatus |= XAie_LockSetValue(&DevInst, XAie_TileLoc(0, 4), XAie_LockInit(6, 2));

	//Setting buffer buf8 of EG.conv[0].out[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 4));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0x0, 32);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(7, -1), XAie_LockInit(6, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 5, XAIE_ENABLE);
		driverStatus |= XAie_DmaSetPkt(&DmaInst, {.PktId=0, .PktType=0});
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 4), 4);
	}

	//Setting buffer buf8d of EG.conv[0].out[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 4));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0x8000, 32);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(7, -1), XAie_LockInit(6, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 4, XAIE_ENABLE);
		driverStatus |= XAie_DmaSetPkt(&DmaInst, {.PktId=0, .PktType=0});
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 4), 5);
	}
	{
		driverStatus |= XAie_DmaChannelSetStartQueue(&DevInst, XAie_TileLoc(0, 4), 0, DMA_MM2S, 4, 1, XAIE_DISABLE);
	}

	//Setting lock initial value for EG.conv[1].out[0]
	driverStatus |= XAie_LockSetValue(&DevInst, XAie_TileLoc(0, 5), XAie_LockInit(5, 2));

	//Setting buffer buf9 of EG.conv[1].out[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 5));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0xc000, 32);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(6, -1), XAie_LockInit(5, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 5, XAIE_ENABLE);
		driverStatus |= XAie_DmaSetPkt(&DmaInst, {.PktId=1, .PktType=0});
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 5), 4);
	}

	//Setting buffer buf9d of EG.conv[1].out[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 5));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0xbd60, 32);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(6, -1), XAie_LockInit(5, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 4, XAIE_ENABLE);
		driverStatus |= XAie_DmaSetPkt(&DmaInst, {.PktId=1, .PktType=0});
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 5), 5);
	}
	{
		driverStatus |= XAie_DmaChannelSetStartQueue(&DevInst, XAie_TileLoc(0, 5), 0, DMA_MM2S, 4, 1, XAIE_DISABLE);
	}

	//Setting lock initial value for EG.conv[2].out[0]
	driverStatus |= XAie_LockSetValue(&DevInst, XAie_TileLoc(0, 6), XAie_LockInit(7, 2));

	//Setting buffer buf10 of EG.conv[2].out[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 6));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0xc000, 32);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(8, -1), XAie_LockInit(7, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 5, XAIE_ENABLE);
		driverStatus |= XAie_DmaSetPkt(&DmaInst, {.PktId=2, .PktType=0});
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 6), 4);
	}

	//Setting buffer buf10d of EG.conv[2].out[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 6));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0x8000, 32);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(8, -1), XAie_LockInit(7, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 4, XAIE_ENABLE);
		driverStatus |= XAie_DmaSetPkt(&DmaInst, {.PktId=2, .PktType=0});
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 6), 5);
	}
	{
		driverStatus |= XAie_DmaChannelSetStartQueue(&DevInst, XAie_TileLoc(0, 6), 0, DMA_MM2S, 4, 1, XAIE_DISABLE);
	}

	//Setting lock initial value for EG.conv[3].out[0]
	driverStatus |= XAie_LockSetValue(&DevInst, XAie_TileLoc(0, 7), XAie_LockInit(7, 2));

	//Setting buffer buf11 of EG.conv[3].out[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 7));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0x8000, 32);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(8, -1), XAie_LockInit(7, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 5, XAIE_ENABLE);
		driverStatus |= XAie_DmaSetPkt(&DmaInst, {.PktId=3, .PktType=0});
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 7), 4);
	}

	//Setting buffer buf11d of EG.conv[3].out[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(0, 7));
		driverStatus |= XAie_DmaSetAddrLen(&DmaInst, 0x4000, 32);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(8, -1), XAie_LockInit(7, 1));
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 4, XAIE_ENABLE);
		driverStatus |= XAie_DmaSetPkt(&DmaInst, {.PktId=3, .PktType=0});
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(0, 7), 5);
	}
	{
		driverStatus |= XAie_DmaChannelSetStartQueue(&DevInst, XAie_TileLoc(0, 7), 0, DMA_MM2S, 4, 1, XAIE_DISABLE);
	}

	//Setting memory tile DMA for EG.input.in[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(2, 2));
		XAie_DmaDimDesc aie2DmaDimDesc[1] = {{.AieMlDimDesc = {1, 0}}, };
		XAie_DmaTensor aie2DmaTensor = {1, aie2DmaDimDesc};
		driverStatus |= XAie_DmaSetMultiDimAddr(&DmaInst, &aie2DmaTensor, 524288, 30360); //adjust address with 524288 offset to refer to memory space in local memory tile
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(65, 0), XAie_LockInit(64, 1)); //adjust lock id with 64 offset to refer to local memory tile lock
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 1, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(2, 2), 0);
	}
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(2, 2));
		XAie_DmaDimDesc aie2DmaDimDesc[1] = {{.AieMlDimDesc = {1, 0}}, };
		XAie_DmaTensor aie2DmaTensor = {1, aie2DmaDimDesc};
		driverStatus |= XAie_DmaSetMultiDimAddr(&DmaInst, &aie2DmaTensor, 524288, 30360); //adjust address with 524288 offset to refer to memory space in local memory tile
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(65, 3), XAie_LockInit(64, -1)); //adjust lock id with 64 offset to refer to local memory tile lock
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 0, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(2, 2), 1);
	}
	{
		XAie_DmaDeclareQueueConfig(startQueueDesc, 0, 1, XAIE_DISABLE, XAIE_DISABLE);
		driverStatus |= XAie_DmaChannelSetStartQueueGeneric(&DevInst, XAie_TileLoc(2, 2), 0, DMA_S2MM, &startQueueDesc);
	}

	//Setting memory tile DMA for EG.input.out[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(2, 2));
		XAie_DmaDimDesc aie2DmaDimDesc[4] = {{.AieMlDimDesc = {1, 7}}, {.AieMlDimDesc = {230, 7}}, {.AieMlDimDesc = {2530, 3}}, {.AieMlDimDesc = {2, 0}}, };
		XAie_DmaTensor aie2DmaTensor = {4, aie2DmaDimDesc};
		driverStatus |= XAie_DmaSetMultiDimAddr(&DmaInst, &aie2DmaTensor, 524288, 65856); //adjust address with 524288 offset to refer to memory space in local memory tile
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(64, 1), XAie_LockInit(65, 1)); //adjust lock id with 64 offset to refer to local memory tile lock
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 3, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(2, 2), 2);
	}
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(2, 2));
		XAie_DmaDimDesc aie2DmaDimDesc[4] = {{.AieMlDimDesc = {1, 7}}, {.AieMlDimDesc = {230, 7}}, {.AieMlDimDesc = {2530, 3}}, {.AieMlDimDesc = {2, 0}}, };
		XAie_DmaTensor aie2DmaTensor = {4, aie2DmaDimDesc};
		driverStatus |= XAie_DmaSetMultiDimAddr(&DmaInst, &aie2DmaTensor, 526128, 65856); //adjust address with 524288 offset to refer to memory space in local memory tile
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(64, 1), XAie_LockInit(65, 1)); //adjust lock id with 64 offset to refer to local memory tile lock
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 4, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(2, 2), 3);
	}
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(2, 2));
		XAie_DmaDimDesc aie2DmaDimDesc[4] = {{.AieMlDimDesc = {1, 7}}, {.AieMlDimDesc = {230, 7}}, {.AieMlDimDesc = {2530, 3}}, {.AieMlDimDesc = {2, 0}}, };
		XAie_DmaTensor aie2DmaTensor = {4, aie2DmaDimDesc};
		driverStatus |= XAie_DmaSetMultiDimAddr(&DmaInst, &aie2DmaTensor, 527968, 65856); //adjust address with 524288 offset to refer to memory space in local memory tile
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(64, 1), XAie_LockInit(65, 1)); //adjust lock id with 64 offset to refer to local memory tile lock
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 5, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(2, 2), 4);
	}
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(2, 2));
		XAie_DmaDimDesc aie2DmaDimDesc[4] = {{.AieMlDimDesc = {1, 7}}, {.AieMlDimDesc = {230, 7}}, {.AieMlDimDesc = {2530, 3}}, {.AieMlDimDesc = {2, 0}}, };
		XAie_DmaTensor aie2DmaTensor = {4, aie2DmaDimDesc};
		driverStatus |= XAie_DmaSetMultiDimAddr(&DmaInst, &aie2DmaTensor, 524288, 65856); //adjust address with 524288 offset to refer to memory space in local memory tile
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(64, 0), XAie_LockInit(65, -1)); //adjust lock id with 64 offset to refer to local memory tile lock
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 6, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(2, 2), 5);
	}
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(2, 2));
		XAie_DmaDimDesc aie2DmaDimDesc[4] = {{.AieMlDimDesc = {1, 7}}, {.AieMlDimDesc = {230, 7}}, {.AieMlDimDesc = {2530, 3}}, {.AieMlDimDesc = {2, 0}}, };
		XAie_DmaTensor aie2DmaTensor = {4, aie2DmaDimDesc};
		driverStatus |= XAie_DmaSetMultiDimAddr(&DmaInst, &aie2DmaTensor, 526128, 65856); //adjust address with 524288 offset to refer to memory space in local memory tile
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(64, 0), XAie_LockInit(65, -1)); //adjust lock id with 64 offset to refer to local memory tile lock
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 7, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(2, 2), 6);
	}
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(2, 2));
		XAie_DmaDimDesc aie2DmaDimDesc[4] = {{.AieMlDimDesc = {1, 7}}, {.AieMlDimDesc = {230, 7}}, {.AieMlDimDesc = {2530, 3}}, {.AieMlDimDesc = {2, 0}}, };
		XAie_DmaTensor aie2DmaTensor = {4, aie2DmaDimDesc};
		driverStatus |= XAie_DmaSetMultiDimAddr(&DmaInst, &aie2DmaTensor, 527968, 65856); //adjust address with 524288 offset to refer to memory space in local memory tile
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(64, 0), XAie_LockInit(65, -1)); //adjust lock id with 64 offset to refer to local memory tile lock
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 2, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(2, 2), 7);
	}
	{
		driverStatus |= XAie_DmaChannelSetStartQueue(&DevInst, XAie_TileLoc(2, 2), 0, DMA_MM2S, 2, 1, XAIE_DISABLE);
	}

	//Setting memory tile DMA for EG.input_weight.in[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(2, 2));
		XAie_DmaDimDesc aie2DmaDimDesc[1] = {{.AieMlDimDesc = {1, 0}}, };
		XAie_DmaTensor aie2DmaTensor = {1, aie2DmaDimDesc};
		driverStatus |= XAie_DmaSetMultiDimAddr(&DmaInst, &aie2DmaTensor, 617888, 4704); //adjust address with 524288 offset to refer to memory space in local memory tile
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(67, 0), XAie_LockInit(66, 1)); //adjust lock id with 64 offset to refer to local memory tile lock
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 25, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(2, 2), 24);
	}
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(2, 2));
		XAie_DmaDimDesc aie2DmaDimDesc[1] = {{.AieMlDimDesc = {1, 0}}, };
		XAie_DmaTensor aie2DmaTensor = {1, aie2DmaDimDesc};
		driverStatus |= XAie_DmaSetMultiDimAddr(&DmaInst, &aie2DmaTensor, 617888, 4704); //adjust address with 524288 offset to refer to memory space in local memory tile
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(67, 1), XAie_LockInit(66, -1)); //adjust lock id with 64 offset to refer to local memory tile lock
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 24, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(2, 2), 25);
	}
	{
		XAie_DmaDeclareQueueConfig(startQueueDesc, 24, 1, XAIE_DISABLE, XAIE_DISABLE);
		driverStatus |= XAie_DmaChannelSetStartQueueGeneric(&DevInst, XAie_TileLoc(2, 2), 1, DMA_S2MM, &startQueueDesc);
	}

	//Setting memory tile DMA for EG.input_weight.out[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(2, 2));
		XAie_DmaDimDesc aie2DmaDimDesc[2] = {{.AieMlDimDesc = {1, 147}}, {.AieMlDimDesc = {147, 8}}, };
		XAie_DmaTensor aie2DmaTensor = {2, aie2DmaDimDesc};
		driverStatus |= XAie_DmaSetMultiDimAddr(&DmaInst, &aie2DmaTensor, 617888, 4704); //adjust address with 524288 offset to refer to memory space in local memory tile
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(66, 1), XAie_LockInit(67, 1)); //adjust lock id with 64 offset to refer to local memory tile lock
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 27, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(2, 2), 26);
	}
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(2, 2));
		XAie_DmaDimDesc aie2DmaDimDesc[2] = {{.AieMlDimDesc = {1, 147}}, {.AieMlDimDesc = {147, 8}}, };
		XAie_DmaTensor aie2DmaTensor = {2, aie2DmaDimDesc};
		driverStatus |= XAie_DmaSetMultiDimAddr(&DmaInst, &aie2DmaTensor, 617888, 4704); //adjust address with 524288 offset to refer to memory space in local memory tile
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(66, 0), XAie_LockInit(67, -1)); //adjust lock id with 64 offset to refer to local memory tile lock
		driverStatus |= XAie_DmaSetNextBd(&DmaInst, 26, XAIE_ENABLE);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(2, 2), 27);
	}
	{
		driverStatus |= XAie_DmaChannelSetStartQueue(&DevInst, XAie_TileLoc(2, 2), 1, DMA_MM2S, 26, 1, XAIE_DISABLE);
	}

	//Setting shim tile DMA for EG.ddrin.out[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(2, 0));
		XAie_DmaDimDesc aie2DmaDimDesc[1] = {{.AieMlDimDesc = {1, 0}}, };
		XAie_DmaTensor aie2DmaTensor = {1, aie2DmaDimDesc};
		driverStatus |= XAie_DmaSetMultiDimAddr(&DmaInst, &aie2DmaTensor, 0, 30360);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(0, 0), XAie_LockInit(0, 0));
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(2, 0), 0);
	}

	//Setting shim tile DMA for EG.ddrout.in[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(2, 0));
		XAie_DmaDimDesc aie2DmaDimDesc[1] = {{.AieMlDimDesc = {1, 0}}, };
		XAie_DmaTensor aie2DmaTensor = {1, aie2DmaDimDesc};
		driverStatus |= XAie_DmaSetMultiDimAddr(&DmaInst, &aie2DmaTensor, 0, 21504);
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(2, 0), 1);
	}

	//Setting shim tile DMA for EG.ddr_weights.out[0]
	{
		XAie_DmaDesc DmaInst;
		driverStatus |= XAie_DmaDescInit(&DevInst, &DmaInst, XAie_TileLoc(2, 0));
		XAie_DmaDimDesc aie2DmaDimDesc[1] = {{.AieMlDimDesc = {1, 0}}, };
		XAie_DmaTensor aie2DmaTensor = {1, aie2DmaDimDesc};
		driverStatus |= XAie_DmaSetMultiDimAddr(&DmaInst, &aie2DmaTensor, 0, 4704);
		driverStatus |= XAie_DmaSetLock(&DmaInst, XAie_LockInit(4, 0), XAie_LockInit(4, 0));
		driverStatus |= XAie_DmaEnableBd(&DmaInst);
		driverStatus |= XAie_DmaWriteBd(&DevInst, &DmaInst, XAie_TileLoc(2, 0), 2);
	}


	std::cout<<"Configuring PL-Interface for graph EG..."<<std::endl;

    #endif
	if(driverStatus != AieRC::XAIE_OK)
	{
		return adf::aie_driver_error;
	}

	return adf::ok;
  }

 void EG_core_debug_halt()
  {
	printf("Putting core(s) of graph EG on halt state for debugging...\n");
	XAie_CoreDebugHalt(&DevInst, XAie_TileLoc(0, 3));
	XAie_CoreDebugHalt(&DevInst, XAie_TileLoc(0, 4));
	XAie_CoreDebugHalt(&DevInst, XAie_TileLoc(0, 5));
	XAie_CoreDebugHalt(&DevInst, XAie_TileLoc(0, 6));
	return;
  }

  void EG_core_enable()
  {
	printf("Enabling core(s) of graph EG...\n");
	XAie_CoreEnable(&DevInst, XAie_TileLoc(0,3 ));
	XAie_CoreEnable(&DevInst, XAie_TileLoc(0,4 ));
	XAie_CoreEnable(&DevInst, XAie_TileLoc(0,5 ));
	XAie_CoreEnable(&DevInst, XAie_TileLoc(0,6 ));
	return;
  }

/************************** Graph Configurations  *****************************/

  adf::GraphConfig GraphConfigurations[] = {
  //{id, name, graphLoadElfFunc, graphInitFunc, graphDebugHalt, coreColumns, coreRows, iterMemColumns, iterMemRows, iterMemAddrs, triggered, plKernelInstanceNames, plAxiLiteModes, plDriverStartFuncs, plDriverCheckIPDoneFuncs}
    {0, "EG", &EG_load_elf, &EG_init, &EG_core_debug_halt, {0, 0, 0, 0}, {0, 1, 2, 3}, {0, 0, 0, 0}, {0, 1, 2, 4}, {0x4004, 0x3b04, 0x24, 0x38a4}, {0, 0, 0, 0}, {}, {}, {}, {},  }, 
  };
  const int NUM_GRAPH = 1;


/************************** RTP Configurations  *****************************/

  adf::RTPConfig RTPConfigurations[] = {
  //{portId, aliasId, portName, aliasName, graphId, isInput, isAsync, isConnect, elemType, numBytes, isPL, hasLock, blocking , isSlaveRTP, selectorColumn, selectorRow, selectorAddr, selectorLockId, pingColumn, pingRow, pingAddr, pongColumn, pongRow, pongAddr, pongLockId, plKernelInstanceName, plParameterIndex, plDriverWriteRTP, plDriverReadRTP}
    {18, 0, "EG.conv[0].in[2]", "EG.wgtcount_port[0]", 0, true, true, false, (adf::RTPConfig::elementType)4, 4, false, true, false, false, 0, 0, 0, 0, 0, 1, 0x9b20, 4, 0, 1, 0x7fe0, 5, "", -1, nullptr, nullptr},
    {22, 1, "EG.conv[1].in[2]", "EG.wgtcount_port[1]", 0, true, true, false, (adf::RTPConfig::elementType)4, 4, false, true, false, false, 0, 0, 0x8000, 1, 0, 2, 0xbfe0, 4, 0, 0, 0xc000, 2, "", -1, nullptr, nullptr},
    {26, 2, "EG.conv[2].in[2]", "EG.wgtcount_port[2]", 0, true, true, false, (adf::RTPConfig::elementType)4, 4, false, true, false, false, 0, 3, 0x20, 4, 0, 3, 0, 5, 0, 3, 0x8280, 6, "", -1, nullptr, nullptr},
    {30, 3, "EG.conv[3].in[2]", "EG.wgtcount_port[3]", 0, true, true, false, (adf::RTPConfig::elementType)4, 4, false, true, false, false, 0, 4, 0x20, 4, 0, 4, 0xc000, 5, 0, 4, 0, 6, "", -1, nullptr, nullptr},
  };
  const int NUM_RTP = 4;


/************************** Shared Buffer Configurations  *****************************/

  adf::SharedBufferConfig SharedBufferConfigurations[] = {
  //{id, name, graphId, numBytes, column, row, numInputs, numOutputs, elemType, initialized, addr, producerLockId, consumerLockId}
    {0, "EG.input", 0, 30360, 2, 1, 1, 2,(adf::RTPConfig::elementType)9, false, { 0, }, { 0, }, { 1, }}, 
    {1, "EG.input_weight", 0, 4704, 2, 1, 1, 2,(adf::RTPConfig::elementType)9, false, { 28064, }, { 2, }, { 3, }}, 
  };
  const int NUM_SHARED_BUFFERS = 2;


/************************** Shared Buffer DMA Ch Configurations  *****************************/

  adf::DMAChannelConfig DMAChConfigurations[] = {
  //{portId, portName, parentId, tileType, column, row, dmaType, channel}
    {6, "EG.input.in[0]", 0, 2, 2, 1, 0, 0},
    {7, "EG.input.out[0]", 0, 2, 2, 1, 1, 0},
    {8, "EG.input_weight.in[0]", 1, 2, 2, 1, 0, 1},
    {9, "EG.input_weight.out[0]", 1, 2, 2, 1, 1, 1},
  };
  const int NUM_DMA_CH_CONFIGS = 4;


/************************** External Buffer Configurations  *****************************/

  adf::ExternalBufferConfig ExternalBufferConfigurations[] = {
  //{id, name, [{portId, portName, column, dmaType, channel, taskRepetition, enable_task_complete_token, [{bd_id, buf_idx, offset, transaction_size}]}]}
    {0, "EG.ddrin", {{4, "EG.ddrin.out[0]", 2, 1, 0, 1, 0, {{0, 0, 0, 30360, }, }, }, }},
    {1, "EG.ddrout", {{5, "EG.ddrout.in[0]", 2, 0, 0, 1, 0, {{1, 0, 0, 21504, }, }, }, }},
    {2, "EG.ddr_weights", {{10, "EG.ddr_weights.out[0]", 2, 1, 1, 1, 0, {{2, 0, 0, 4704, }, }, }, }},
  };
  const int NUM_EXTERNAL_BUFFERS = 3;


/************************** AIE driver and ADF API initializer *****************************/

  class InitializeAIEControl
  {
  public:
    InitializeAIEControl()
    {
      printf("Initializing AIE driver...\n");
      XAie_SetupConfig(ConfigPtr, HW_GEN, XAIE_BASE_ADDR, XAIE_COL_SHIFT,
                       XAIE_ROW_SHIFT, XAIE_NUM_COLS, XAIE_NUM_ROWS,
                       XAIE_SHIM_ROW, XAIE_MEM_TILE_ROW_START,
                       XAIE_MEM_TILE_NUM_ROWS, XAIE_AIE_TILE_ROW_START,
                       XAIE_AIE_TILE_NUM_ROWS);

      XAie_CfgInitialize(&(DevInst), &ConfigPtr);

#if defined(__CDO__)
      XAie_SetIOBackend(&(DevInst), XAIE_IO_BACKEND_CDO); // Set aiengine driver library to run for CDO Mode
      XAie_UpdateNpiAddr(&(DevInst), 0xf6d10000);
#elif !defined(__AIESIM__) && defined(__AIECONTROLCODE__)
      XAie_SetIOBackend(&(DevInst), XAIE_IO_BACKEND_CONTROLCODE); // Set aiengine driver library to run for CONTROLCODE Mode
      XAie_UpdateNpiAddr(&(DevInst), 0xf6d10000);
#endif

#if defined(__AIESIM__)
      XAie_TurnEccOff(&DevInst);
#endif

      printf("Initializing ADF API...\n");

#if defined(__AIESIM__)
      extern unsigned ess_debug;
#else
      unsigned ess_debug = false;
#endif

#ifdef __EXCLUDE_PL_CONTROL__
      bool exclude_pl_control = true;
#else
      bool exclude_pl_control = false;
#endif

#ifdef __CDO__
      int trace_config_stream_option = 2;
#else
      int trace_config_stream_option = 0;
#endif

      adf::initializeConfigurations(&DevInst, XAIE_NUM_COLS, XAIE_AIE_TILE_NUM_ROWS, XAIE_MEM_TILE_NUM_ROWS,
                                        GraphConfigurations, NUM_GRAPH,
                                        RTPConfigurations, NUM_RTP,
                                        nullptr, 0,
                                        nullptr, 0,
                                        DMAChConfigurations, NUM_DMA_CH_CONFIGS,
                                        nullptr, 0,
                                        SharedBufferConfigurations, NUM_SHARED_BUFFERS,
                                        ExternalBufferConfigurations, NUM_EXTERNAL_BUFFERS,
                                        nullptr, 0,
                                        nullptr, 0,
                                        nullptr, 0, trace_config_stream_option, nullptr,
                                        ess_debug, exclude_pl_control, true, &broadcastConfigForCoreEnable, true, 0, 0, 2);

    }
  } initAIEControl;


#if defined(__CDO__) || defined(__AIECONTROLCODE__)

/******************* Helper Function to Request Tiles **********************/
/** used in enableErrorHandling, enableClockGating, timerSynchronization ***/

  void requestTiles()
  {
    XAie_LocType locs[14] = {XAie_TileLoc(0, 3), XAie_TileLoc(0, 4), XAie_TileLoc(0, 5), XAie_TileLoc(0, 6), XAie_TileLoc(0, 7), XAie_TileLoc(1, 3), XAie_TileLoc(2, 3), XAie_TileLoc(0, 0), XAie_TileLoc(1, 0), XAie_TileLoc(2, 0), XAie_TileLoc(0, 1), XAie_TileLoc(0, 2), XAie_TileLoc(2, 1), XAie_TileLoc(2, 2)};
    XAie_PmRequestTiles(&DevInst, locs, 14);
  }


/************************** Partition reset *****************************/

  void resetPartition()
  {
    XAie_PartitionInitialize(&DevInst, nullptr);
  }


/************************** Error handling *****************************/

  void enableErrorHandling()
  {
    requestTiles();
    auto spXAieDev = fal_util::get_spXAieDev();
    if (spXAieDev == nullptr)
    {
        printf("s_pXAieDev is null, enableErrorHandling failed\n");
        return;
    }
    spXAieDev->reserveErrorHandling();
    XAie_ErrorHandlingInit(&DevInst);
  }


/************************** Clock gating *****************************/

  void enableClockGating()
  {
    requestTiles();
    auto spXAieDev = fal_util::get_spXAieDev();
    if (spXAieDev == nullptr)
    {
        printf("s_pXAieDev is null, enableClockGating failed\n");
        return;
    }
    spXAieDev->reserveEcc();
    XAie_TurnEccOn(&DevInst);
  }


/************************** Clear Partition Memories *****************************/

  void clearPartitionMems()
  {
    XAie_ClearPartitionMems(&DevInst);
  }
#endif

#if defined(__CDO__) || defined(__AIECONTROLCODE__)
/************************** Collect Statically Allocated Resources *****************************/

  void dumpAllocatedRscsToFile(const std::string aieRscsFilePath)
  {
    auto spXAieDev = fal_util::get_spXAieDev();
    if (spXAieDev == nullptr)
    {
        printf("s_pXAieDev is null, dumpAllocatedRscsToFile failed\n");
        return;
    }
    spXAieDev->saveAllocatedRscsToFile(aieRscsFilePath);
  }
#endif



#if defined(__AIESIM__) || defined(__PS_BARE_METAL__)

  using namespace adf;

// Kernel Stub Definition

#include "kernel_stubs.h"
#endif
