#!/usr/bin/env bash
# Copyright (C) 2026 Advanced Micro Devices, Inc. All Rights Reserved.
# SPDX-License-Identifier: MIT

set -euo pipefail

SIM_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SIM_DIR}/../.." && pwd)"

OUT="${1:-${REPO_ROOT}/aiehlc_aiesimulator}"

STOCK=""
if [ -n "${XILINX_VITIS_AIETOOLS:-}" ] && [ -f "${XILINX_VITIS_AIETOOLS}/bin/aiesimulator" ]; then
    STOCK="${XILINX_VITIS_AIETOOLS}/bin/aiesimulator"
elif [ -n "${XILINX_VITIS:-}" ] && [ -f "${XILINX_VITIS}/aietools/bin/aiesimulator" ]; then
    STOCK="${XILINX_VITIS}/aietools/bin/aiesimulator"
elif command -v aiesimulator >/dev/null 2>&1; then
    STOCK="$(command -v aiesimulator)"
else
    echo "gen_aiesimulator: cannot locate stock Vitis aiesimulator." >&2
    echo "  Set XILINX_VITIS_AIETOOLS or XILINX_VITIS (source Vitis settings first)." >&2
    exit 1
fi

echo "gen_aiesimulator: patching ${STOCK}"
echo "gen_aiesimulator: writing  ${OUT}"

REPL="$(mktemp)"
trap 'rm -f "${REPL}"' EXIT
cat > "${REPL}" <<'EOF'
# AIEHLC: Change 1 (auto-generated by script/sim/gen_aiesimulator.sh)
# Replace `. setupEnv.sh` relative-source with direct RDI_* derivation from
# $XILINX_VITIS_AIETOOLS, because setupEnv.sh uses `dirname "$0"` to locate
# itself, which breaks when this launcher lives outside the Vitis bin dir.
if [ -z "${XILINX_VITIS_AIETOOLS:-}" ]; then
    if [ -n "${XILINX_VITIS:-}" ] && [ -d "${XILINX_VITIS}/aietools" ]; then
        export XILINX_VITIS_AIETOOLS="${XILINX_VITIS}/aietools"
    else
        echo "AEG: XILINX_VITIS_AIETOOLS is not set and XILINX_VITIS not found." >&2
        echo "     Source script/envaie2pst50.sh (or equivalent) first." >&2
        exit 1
    fi
fi
export RDI_BINROOT="${XILINX_VITIS_AIETOOLS}/bin"
export RDI_APPROOT="${XILINX_VITIS_AIETOOLS}"
export RDI_BASEROOT="$(dirname "${XILINX_VITIS_AIETOOLS}")"
export RDI_INSTALLROOT="$(dirname "${RDI_BASEROOT}")"
export RDI_INSTALLVER="$(basename "${RDI_APPROOT}")"
export _RDI_SETENV_RUN=1
# (end AIEHLC change 1)
EOF

matched="$(awk '/^[[:space:]]*\..*setupEnv\.sh/{c++} END{print c+0}' "${STOCK}")"
if [ "${matched}" != "1" ]; then
    echo "gen_aiesimulator: expected exactly 1 setupEnv.sh source line, found ${matched}." >&2
    echo "  Stock script layout may have changed; update this generator." >&2
    exit 1
fi

awk -v replfile="${REPL}" '
    /^[[:space:]]*\..*setupEnv\.sh/ {
        while ((getline line < replfile) > 0) print line
        close(replfile)
        next
    }
    { print }
' "${STOCK}" > "${OUT}"

chmod +x "${OUT}"
echo "gen_aiesimulator: done."
