#!/usr/bin/env bash
###############################################################################
# Copyright (C) 2026 Advanced Micro Devices, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
###############################################################################

write_sim_config() {
    local out_dir="$1" host_src="$2" kernel_objs="$3" kernel_names="$4"
    local gen="$5" sim_tiles="$6"
    local runsim
    runsim="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/runsim.sh"

    mkdir -p "$out_dir"
    local cfg="${out_dir}/sim_config.sh"
    {
        echo "# Auto-generated by aiehlc -- do not edit; re-run aiehlc to regenerate."
        echo "HOST_SRC=\"${host_src}\""
        echo "KERNEL_OBJS=\"${kernel_objs}\""
        echo "KERNEL_NAMES=\"${kernel_names}\""
        echo "AIE_GEN=\"${gen}\""
        if [ -n "$sim_tiles" ]; then
            echo "STUB_TILES=\"${sim_tiles}\""
        else
            echo "STUB_ALL=1"
        fi
    } > "$cfg"
    echo ""
    echo "[sim] Artifacts + sim config written to ${out_dir}"
    echo "[sim] Run the simulator with:"
    echo "        bash ${runsim} ${out_dir}"
    echo ""
}
